package com.fractalx.core.datamanagement;

import com.fractalx.core.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * RENAMED: DataIsolationGenerator
 * Research Area: Data Isolation (Task 1)
 * Purpose: Generates Spring configuration to strictly confine JPA/Entity scanning
 * to the specific module's package, preventing shared-state leakage.
 */
public class DataIsolationGenerator {

    private static final Logger log = LoggerFactory.getLogger(DataIsolationGenerator.class);

    public void generateIsolationConfig(FractalModule module, Path srcMainJava) throws IOException {
        log.info("🛡️ [DataIsolation] Enforcing data boundaries for: {}", module.getServiceName());

        String basePackage = "com.fractalx.generated." + module.getServiceName().replace("-", "");
        String configPackage = basePackage + ".config";

        Path configPath = createPackagePath(srcMainJava, configPackage);

        // Generate the 'IsolationConfig' class (Renamed from DatabaseConfig for clarity)
        String classContent = generateConfigClass(configPackage, module.getPackageName());

        // File name matches the generated class name
        Path filePath = configPath.resolve("IsolationConfig.java");
        Files.writeString(filePath, classContent);

        log.info("   ✓ Created IsolationConfig.java");
    }

    private Path createPackagePath(Path srcMainJava, String packageName) throws IOException {
        String[] parts = packageName.split("\\.");
        Path path = srcMainJava;
        for (String part : parts) {
            path = path.resolve(part);
        }
        Files.createDirectories(path);
        return path;
    }

    private String generateConfigClass(String configPackage, String sourcePackage) {
        return """
            package %s;

            import org.springframework.context.annotation.Configuration;
            import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
            import org.springframework.boot.autoconfigure.domain.EntityScan;

            /**
             * Auto-Generated by FractalX.
             * COMPONENT: Data Isolation Enforcer.
             * PURPOSE: Explicitly restricts DB scanning to %s to prevent leakages.
             */
            @Configuration
            @EnableJpaRepositories(basePackages = "%s")
            @EntityScan(basePackages = "%s")
            public class IsolationConfig {
                // Bounds the data context to this specific microservice
            }
            """.formatted(configPackage, sourcePackage, sourcePackage, sourcePackage);
    }
}