package com.fractalx.core.datamanagement;

import com.fractalx.core.model.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

/**
 * Generates or updates application.yml for microservices.
 * Merges Database and JPA configurations into the existing YAML, preserving
 * settings like Service Discovery and Actuator generated by other components.
 * Enforces 'ddl-auto: update' to allow Hibernate to generate schema from decoupled entities.
 */
public class DbConfigurationGenerator {

    private static final Logger log = LoggerFactory.getLogger(DbConfigurationGenerator.class);

    public String generateDbConfig(FractalModule module, Path sourceRoot, Path serviceResourcesPath) {
        // 1. Read existing YAML to preserve current configuration
        Path ymlPath = serviceResourcesPath.resolve("application.yml");
        Map<String, Object> existingConfig = readYaml(ymlPath);

        if (existingConfig == null) {
            existingConfig = new HashMap<>();
        }

        // 2. Read Monolith database configuration
        Map<String, Object> monolithConfig = readConfigFromMonolith(module.getServiceName(), sourceRoot);
        String driverClassName = null;

        try {
            // 3. Merge appropriate configuration
            if (monolithConfig != null) {
                log.info("⚙️ [Config] Merging custom DB config for '{}'...", module.getServiceName());

                Map<String, Object> datasource = (Map<String, Object>) monolithConfig.get("datasource");
                if (datasource != null) {
                    driverClassName = (String) datasource.get("driver-class-name");
                }

                // Merge Monolith DB settings into existing config
                mergeDbConfig(existingConfig, monolithConfig, module);

            } else {
                log.info("ℹ️ [Config] No custom config found. Merging default H2 config for '{}'.", module.getServiceName());
                // Merge default H2 settings into existing config
                mergeDefaultH2(existingConfig, module);
            }

            // 4. Write merged configuration back to file
            writeYaml(ymlPath, existingConfig);
            log.info("   ✓ Updated application.yml");

            return driverClassName;

        } catch (IOException e) {
            log.error("Failed to write application.yml", e);
            return null;
        }
    }

    // --- MERGE LOGIC ---

    private void mergeDbConfig(Map<String, Object> target, Map<String, Object> source, FractalModule module) {
        Map<String, Object> spring = (Map<String, Object>) target.computeIfAbsent("spring", k -> new HashMap<>());

        // Inject Datasource
        Map<String, Object> sourceDs = (Map<String, Object>) source.get("datasource");
        processDatasourceUrl(sourceDs);
        spring.put("datasource", sourceDs);

        // Inject JPA with update mode forced
        Map<String, Object> sourceJpa = (Map<String, Object>) source.get("jpa");
        if (sourceJpa == null) sourceJpa = new HashMap<>();

        configureUpdateMode(sourceJpa);
        spring.put("jpa", sourceJpa);

        // Inject SQL initialization settings
        Map<String, Object> sql = new HashMap<>();
        Map<String, Object> init = new HashMap<>();
        init.put("mode", "always");
        init.put("platform", detectPlatform((String) sourceDs.get("driver-class-name")));
        sql.put("init", init);
        spring.put("sql", sql);
    }

    private void mergeDefaultH2(Map<String, Object> target, FractalModule module) {
        Map<String, Object> spring = (Map<String, Object>) target.computeIfAbsent("spring", k -> new HashMap<>());

        // Datasource: jdbc:h2:mem:service_name
        Map<String, Object> datasource = new HashMap<>();
        String dbName = module.getServiceName().replace("-", "_");

        datasource.put("url", "jdbc:h2:mem:" + dbName);
        datasource.put("driver-class-name", "org.h2.Driver");
        datasource.put("username", "sa");
        datasource.put("password", "");
        spring.put("datasource", datasource);

        // SQL initialization
        Map<String, Object> sql = new HashMap<>();
        Map<String, Object> init = new HashMap<>();
        init.put("mode", "always");
        init.put("platform", "h2");
        sql.put("init", init);
        spring.put("sql", sql);

        // JPA: Force update mode
        Map<String, Object> jpa = new HashMap<>();
        jpa.put("show-sql", true);

        Map<String, Object> hibernate = new HashMap<>();
        hibernate.put("ddl-auto", "update");
        jpa.put("hibernate", hibernate);

        Map<String, Object> properties = new HashMap<>();
        Map<String, Object> hibProps = new HashMap<>();
        hibProps.put("format_sql", true);
        properties.put("hibernate", hibProps);
        jpa.put("properties", properties);

        spring.put("jpa", jpa);

        // Enable H2 Console
        Map<String, Object> h2 = new HashMap<>();
        Map<String, Object> console = new HashMap<>();
        console.put("enabled", true);
        h2.put("console", console);
        spring.put("h2", h2);
    }

    // --- HELPERS ---

    private void processDatasourceUrl(Map<String, Object> datasource) {
        if (datasource == null) return;
        String driver = (String) datasource.get("driver-class-name");
        String url = (String) datasource.get("url");

        // Append createDatabaseIfNotExist for MySQL to prevent startup errors
        if (driver != null && driver.contains("mysql") && url != null) {
            if (!url.contains("createDatabaseIfNotExist=true")) {
                String separator = url.contains("?") ? "&" : "?";
                datasource.put("url", url + separator + "createDatabaseIfNotExist=true");
            }
        }
    }

    private void configureUpdateMode(Map<String, Object> jpaConfig) {
        Map<String, Object> hibernate = (Map<String, Object>) jpaConfig.get("hibernate");
        if (hibernate == null) {
            hibernate = new HashMap<>();
            jpaConfig.put("hibernate", hibernate);
        }
        // Force 'update' to allow Hibernate to generate schema from Java entities
        hibernate.put("ddl-auto", "update");
    }

    private String detectPlatform(String driver) {
        if (driver == null) return "all";
        if (driver.contains("mysql")) return "mysql";
        if (driver.contains("postgresql")) return "postgresql";
        if (driver.contains("h2")) return "h2";
        return "all";
    }

    // --- IO & YAML UTILS ---

    private Map<String, Object> readYaml(Path path) {
        if (!Files.exists(path)) return new HashMap<>();
        try (FileInputStream inputStream = new FileInputStream(path.toFile())) {
            return new Yaml().load(inputStream);
        } catch (Exception e) {
            log.warn("Could not parse existing YAML: {}", e.getMessage());
            return new HashMap<>();
        }
    }

    private void writeYaml(Path path, Map<String, Object> data) throws IOException {
        DumperOptions options = new DumperOptions();
        options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        options.setPrettyFlow(true);
        options.setIndent(2);

        Yaml yaml = new Yaml(options);
        String output = yaml.dump(data);
        Files.writeString(path, output);
    }

    /**
     * Reads per-service database configuration from {@code fractalx-config.yml} in the
     * monolith's resources directory.
     *
     * <p>Expected structure:
     * <pre>
     * fractalx:
     *   services:
     *     order-service:
     *       datasource:
     *         url: jdbc:mysql://localhost:3306/order_db
     *         username: root
     *         password: secret
     *     payment-service:
     *       datasource:
     *         url: jdbc:postgresql://localhost:5432/payment_db
     *         username: postgres
     *         password: secret
     * </pre>
     *
     * <p>Falls back to {@code application.yml} under the same directory for the legacy
     * {@code fractalx.modules.<name>} layout, then returns {@code null} if neither is found.
     */
    @SuppressWarnings("unchecked")
    private Map<String, Object> readConfigFromMonolith(String serviceName, Path sourceRoot) {
        Path resourcesDir = sourceRoot.getParent().resolve("resources");

        // Primary: fractalx-config.yml with fractalx.services.<name> layout
        Path fractalxConfig = resourcesDir.resolve("fractalx-config.yml");
        if (Files.exists(fractalxConfig)) {
            try (FileInputStream fis = new FileInputStream(fractalxConfig.toFile())) {
                Map<String, Object> root = new Yaml().load(fis);
                if (root != null) {
                    Map<String, Object> fractalx = (Map<String, Object>) root.get("fractalx");
                    if (fractalx != null) {
                        Map<String, Object> services = (Map<String, Object>) fractalx.get("services");
                        if (services != null && services.containsKey(serviceName)) {
                            log.info("⚙️ [Config] Found fractalx-config.yml entry for '{}'", serviceName);
                            return (Map<String, Object>) services.get(serviceName);
                        }
                    }
                }
            } catch (Exception e) {
                log.warn("Could not parse fractalx-config.yml: {}", e.getMessage());
            }
        }

        // Legacy fallback: application.yml with fractalx.modules.<name> layout
        Path legacyConfig = resourcesDir.resolve("application.yml");
        if (Files.exists(legacyConfig)) {
            try (FileInputStream fis = new FileInputStream(legacyConfig.toFile())) {
                Map<String, Object> root = new Yaml().load(fis);
                if (root != null) {
                    Map<String, Object> fractalx = (Map<String, Object>) root.get("fractalx");
                    if (fractalx != null) {
                        Map<String, Object> modules = (Map<String, Object>) fractalx.get("modules");
                        if (modules != null && modules.containsKey(serviceName)) {
                            log.info("⚙️ [Config] Found legacy application.yml module config for '{}'", serviceName);
                            return (Map<String, Object>) modules.get(serviceName);
                        }
                    }
                }
            } catch (Exception e) {
                log.warn("Could not parse monolith application.yml: {}", e.getMessage());
            }
        }

        return null;
    }
}