package com.fractalx.core.datamanagement;

import com.fractalx.core.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * RENAMED: StateStoreGenerator
 * Research Area: State Management (Task 3)
 * Purpose: Configures the distributed state store (Redis).
 * This enables the microservice to persist transient transaction states (Sagas).
 */
public class StateStoreGenerator {

    private static final Logger log = LoggerFactory.getLogger(StateStoreGenerator.class);

    public void generateStateStoreConfig(FractalModule module, Path srcMainJava) throws IOException {
        log.info("⚡ [StateManagement] Initializing Distributed State Store (Redis) for: {}", module.getServiceName());

        String basePackage = "com.fractalx.generated." + module.getServiceName().replace("-", "");
        String configPackage = basePackage + ".config";

        Path configPath = createPackagePath(srcMainJava, configPackage);
        String classContent = generateRedisConfigClass(configPackage);

        // We rename the output file to 'DistributedStateConfig' to be more descriptive
        Path filePath = configPath.resolve("DistributedStateConfig.java");
        Files.writeString(filePath, classContent);

        log.info("   ✓ Created DistributedStateConfig.java");
    }

    private Path createPackagePath(Path srcMainJava, String packageName) throws IOException {
        String[] parts = packageName.split("\\.");
        Path path = srcMainJava;
        for (String part : parts) {
            path = path.resolve(part);
        }
        Files.createDirectories(path);
        return path;
    }

    private String generateRedisConfigClass(String packageName) {
        return """
            package %s;

            import org.springframework.context.annotation.Bean;
            import org.springframework.context.annotation.Configuration;
            import org.springframework.data.redis.connection.RedisConnectionFactory;
            import org.springframework.data.redis.core.RedisTemplate;
            import org.springframework.data.redis.serializer.StringRedisSerializer;

            /**
             * Auto-Generated by FractalX.
             * COMPONENT: Distributed State Store Interface.
             * PURPOSE: Provides access to Redis for Saga transaction logging.
             */
            @Configuration
            public class DistributedStateConfig {

                @Bean
                public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory connectionFactory) {
                    RedisTemplate<String, Object> template = new RedisTemplate<>();
                    template.setConnectionFactory(connectionFactory);
                    template.setKeySerializer(new StringRedisSerializer());
                    template.setHashKeySerializer(new StringRedisSerializer());
                    return template;
                }
            }
            """.formatted(packageName);
    }
}