package org.fractalx.core.generator.service;

import org.fractalx.core.generator.GenerationContext;
import org.fractalx.core.generator.ServiceFileGenerator;
import org.fractalx.core.model.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates the Spring Boot Application class for a microservice.
 */
public class ApplicationGenerator implements ServiceFileGenerator {

    private static final Logger log = LoggerFactory.getLogger(ApplicationGenerator.class);

    @Override
    public void generate(GenerationContext context) throws IOException {
        FractalModule module = context.getModule();
        log.debug("Generating Application class for {}", module.getServiceName());

        String basePackage = context.servicePackage();
        Path packagePath = createPackagePath(context.getSrcMainJava(), basePackage);

        String className = toPascalCase(module.getServiceName()) + "Application";
        Files.writeString(packagePath.resolve(className + ".java"),
                buildContent(module, basePackage, className, context));

        log.info("Generated Application class: {}", className);
    }

    private String buildContent(FractalModule module, String basePackage, String className,
                                GenerationContext context) {
        String originalPackage = extractBasePackage(module.getPackageName(), context);
        String scanPackages = "\"%s\", \"%s\", \"org.fractalx.runtime\"".formatted(basePackage, originalPackage);

        String clientAnnotation = module.getDependencies().isEmpty()
                ? ""
                : "\n@EnableNetScopeClient(basePackages = {" + scanPackages + "})";

        String clientImport = module.getDependencies().isEmpty()
                ? ""
                : "\nimport org.fractalx.netscope.client.annotation.EnableNetScopeClient;";

        return """
                package %s;

                import org.springframework.boot.SpringApplication;
                import org.springframework.boot.autoconfigure.SpringBootApplication;
                import org.springframework.context.annotation.ComponentScan;
                import org.fractalx.netscope.server.annotation.EnableNetScopeServer;%s

                /**
                 * Main application class for %s
                 * Generated by FractalX Framework
                 */
                @SpringBootApplication
                @EnableNetScopeServer
                @ComponentScan(basePackages = {%s})%s
                public class %s {

                    public static void main(String[] args) {
                        SpringApplication.run(%s.class, args);
                    }
                }
                """.formatted(basePackage, clientImport, module.getServiceName(), scanPackages, clientAnnotation, className, className);
    }

    /** Strips the last package segment: {@code com.example.order} → {@code com.example}. */
    private String extractBasePackage(String packageName, GenerationContext context) {
        if (packageName == null || packageName.isBlank()) {
            return context.basePackage();
        }
        int lastDot = packageName.lastIndexOf('.');
        return lastDot > 0 ? packageName.substring(0, lastDot) : packageName;
    }

    private Path createPackagePath(Path srcMainJava, String packageName) throws IOException {
        Path path = srcMainJava;
        for (String part : packageName.split("\\.")) {
            path = path.resolve(part);
        }
        Files.createDirectories(path);
        return path;
    }

    private String toPascalCase(String kebabCase) {
        StringBuilder result = new StringBuilder();
        boolean capitalizeNext = true;
        for (char c : kebabCase.toCharArray()) {
            if (c == '-') {
                capitalizeNext = true;
            } else if (capitalizeNext) {
                result.append(Character.toUpperCase(c));
                capitalizeNext = false;
            } else {
                result.append(c);
            }
        }
        return result.toString();
    }
}
