package org.fractalx.core.generator.service;

import org.fractalx.core.generator.GenerationContext;
import org.fractalx.core.generator.ServiceFileGenerator;
import org.fractalx.core.model.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Pipeline step that generates per-service correlation ID infrastructure.
 *
 * <p>The {@link org.fractalx.runtime.TraceFilter} in {@code fractalx-runtime} already
 * handles reading {@code X-Correlation-Id} from HTTP headers and populating the MDC.
 * The {@link org.fractalx.runtime.NetScopeContextInterceptor} propagates it through
 * gRPC calls. This generator adds the final missing piece:
 *
 * <ul>
 *   <li>{@code logback-spring.xml} — structured log pattern that includes
 *       {@code [%X{correlationId}]} on every log line, enabling cross-service log
 *       aggregation by a single correlation ID.</li>
 * </ul>
 *
 * <p>Generated log format (merged Spring Boot + correlation-ID style):
 * <pre>
 * 2026-03-08T13:11:17.533+05:30 [NO_CORR] DEBUG 15204 --- [order-service] [   scheduling-1] o.f.order.OrderService                   : Processing order
 * </pre>
 *
 * <p>Auto-generated by FractalX — Layer 5 (Correlation ID / Distributed Tracing).
 */
public class CorrelationIdGenerator implements ServiceFileGenerator {

    private static final Logger log = LoggerFactory.getLogger(CorrelationIdGenerator.class);

    @Override
    public void generate(GenerationContext context) throws IOException {
        if (!context.getFractalxConfig().features().observability()) return;
        FractalModule module = context.getModule();
        Path resourcesDir = context.getSrcMainResources();
        Files.createDirectories(resourcesDir);

        Path logbackFile = resourcesDir.resolve("logback-spring.xml");
        if (Files.exists(logbackFile)) {
            log.debug("logback-spring.xml already exists for {} — skipping", module.getServiceName());
            return;
        }

        Files.writeString(logbackFile, buildLogbackXml(module.getServiceName()));
        log.info("Generated logback-spring.xml for {}", module.getServiceName());
    }

    // -------------------------------------------------------------------------
    // logback-spring.xml
    // -------------------------------------------------------------------------

    private String buildLogbackXml(String serviceName) {
        // Merged pattern — Spring Boot standard columns + FractalX correlationId MDC key.
        // Columns (left to right):
        //   timestamp (ISO-8601 + zone offset) | correlationId | level | PID | --- | [app-name] | [thread] | logger | : message
        // Example:
        //   2026-03-08T13:11:17.533+05:30 [NO_CORR] DEBUG 15204 --- [order-service] [   scheduling-1] o.f.order.OrderService                   : Processing order
        //
        // Notes on Logback pattern tokens (NOT Java format specifiers):
        //   %d{...}          — timestamp with Logback date pattern
        //   %X{key:-default} — MDC value (correlationId set by TraceFilter / NetScopeContextInterceptor)
        //   ${PID:-????}     — Spring Boot sets PID as a system property at startup; Logback substitutes it.
        //                      ProcessIdConverter (%pid) was removed in Spring Boot 3.x — use ${PID} instead.
        //   ${APP_NAME}      — Logback context property resolved from <springProperty>
        //   %15.15t          — thread name, right-padded / truncated to 15 chars
        //   %-40.40logger{39}— logger name abbreviated to 39 chars, left-padded to 40
        String logPattern =
            "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} [%X{correlationId:-NO_CORR}] %-5level ${PID:-????} --- [${APP_NAME}] [%15.15t] %-40.40logger{39} : %msg%n";

        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "<!--\n"
            + "  Auto-generated by FractalX — Correlation ID logging configuration.\n"
            + "  Every log line includes [correlationId] so you can grep a single\n"
            + "  ID across all service logs to reconstruct the full distributed request path.\n"
            + "  Service: " + serviceName + "\n"
            + "-->\n"
            + "<configuration>\n"
            + "\n"
            + "    <!-- Bind spring.application.name -> APP_NAME Logback context property -->\n"
            + "    <springProperty scope=\"context\" name=\"APP_NAME\"\n"
            + "                    source=\"spring.application.name\" defaultValue=\"" + serviceName + "\"/>\n"
            + "\n"
            + "    <!-- Shared pattern — defined once, referenced by both appenders -->\n"
            + "    <property name=\"LOG_PATTERN\" value=\"" + logPattern + "\"/>\n"
            + "\n"
            + "    <!-- Console appender -->\n"
            + "    <appender name=\"CONSOLE\" class=\"ch.qos.logback.core.ConsoleAppender\">\n"
            + "        <encoder>\n"
            + "            <pattern>${LOG_PATTERN}</pattern>\n"
            + "        </encoder>\n"
            + "    </appender>\n"
            + "\n"
            + "    <!-- Rolling file appender — keeps 30 days of logs -->\n"
            + "    <appender name=\"FILE\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\">\n"
            + "        <file>logs/" + serviceName + ".log</file>\n"
            + "        <rollingPolicy class=\"ch.qos.logback.core.rolling.TimeBasedRollingPolicy\">\n"
            + "            <fileNamePattern>logs/" + serviceName + "-%d{yyyy-MM-dd}.log</fileNamePattern>\n"
            + "            <maxHistory>30</maxHistory>\n"
            + "        </rollingPolicy>\n"
            + "        <encoder>\n"
            + "            <pattern>${LOG_PATTERN}</pattern>\n"
            + "        </encoder>\n"
            + "    </appender>\n"
            + "\n"
            + "    <!-- Suppress noisy framework loggers -->\n"
            + "    <logger name=\"org.fractalx\" level=\"INFO\"/>\n"
            + "    <logger name=\"org.springframework\" level=\"WARN\"/>\n"
            + "    <logger name=\"io.grpc\" level=\"WARN\"/>\n"
            + "\n"
            + "    <root level=\"INFO\">\n"
            + "        <appender-ref ref=\"CONSOLE\"/>\n"
            + "        <appender-ref ref=\"FILE\"/>\n"
            + "    </root>\n"
            + "\n"
            + "</configuration>\n";
    }
}
