package org.fractalx.core.generator.service;

import org.fractalx.core.generator.GenerationContext;
import org.fractalx.core.generator.ServiceFileGenerator;
import org.fractalx.core.model.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Pipeline step that generates per-service correlation ID infrastructure.
 *
 * <p>The {@link org.fractalx.runtime.TraceFilter} in {@code fractalx-runtime} already
 * handles reading {@code X-Correlation-Id} from HTTP headers and populating the MDC.
 * The {@link org.fractalx.runtime.NetScopeContextInterceptor} propagates it through
 * gRPC calls. This generator adds the final missing piece:
 *
 * <ul>
 *   <li>{@code logback-spring.xml} — structured log pattern that includes
 *       {@code [%X{correlationId}]} on every log line, enabling cross-service log
 *       aggregation by a single correlation ID.</li>
 * </ul>
 *
 * <p>Generated log format:
 * <pre>
 * 2026-03-04 12:00:00.123 [abc-123] INFO  o.f.g.orderservice.OrderService - Processing order
 * </pre>
 *
 * <p>Auto-generated by FractalX — Layer 5 (Correlation ID / Distributed Tracing).
 */
public class CorrelationIdGenerator implements ServiceFileGenerator {

    private static final Logger log = LoggerFactory.getLogger(CorrelationIdGenerator.class);

    @Override
    public void generate(GenerationContext context) throws IOException {
        FractalModule module = context.getModule();
        Path resourcesDir = context.getSrcMainResources();
        Files.createDirectories(resourcesDir);

        Path logbackFile = resourcesDir.resolve("logback-spring.xml");
        if (Files.exists(logbackFile)) {
            log.debug("logback-spring.xml already exists for {} — skipping", module.getServiceName());
            return;
        }

        Files.writeString(logbackFile, buildLogbackXml(module.getServiceName()));
        log.info("Generated logback-spring.xml for {}", module.getServiceName());
    }

    // -------------------------------------------------------------------------
    // logback-spring.xml
    // -------------------------------------------------------------------------

    private String buildLogbackXml(String serviceName) {
        // Use plain string concatenation to avoid conflicts between Java format specifiers
        // (e.g. %X, %d, %n) and Logback's own MDC/pattern syntax.
        String logPattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{correlationId:-NO_CORR}] %-5level %logger{36} - %msg%n";
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "<!--\n"
            + "  Auto-generated by FractalX — Correlation ID logging configuration.\n"
            + "  Every log line includes [%X{correlationId}] so you can grep a single\n"
            + "  ID across all service logs to reconstruct the full request path.\n"
            + "  Service: " + serviceName + "\n"
            + "-->\n"
            + "<configuration>\n"
            + "\n"
            + "    <!-- Console appender with correlationId in every log line -->\n"
            + "    <appender name=\"CONSOLE\" class=\"ch.qos.logback.core.ConsoleAppender\">\n"
            + "        <encoder>\n"
            + "            <pattern>" + logPattern + "</pattern>\n"
            + "        </encoder>\n"
            + "    </appender>\n"
            + "\n"
            + "    <!-- Rolling file appender — keeps 30 days of logs -->\n"
            + "    <appender name=\"FILE\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\">\n"
            + "        <file>logs/" + serviceName + ".log</file>\n"
            + "        <rollingPolicy class=\"ch.qos.logback.core.rolling.TimeBasedRollingPolicy\">\n"
            + "            <fileNamePattern>logs/" + serviceName + "-%d{yyyy-MM-dd}.log</fileNamePattern>\n"
            + "            <maxHistory>30</maxHistory>\n"
            + "        </rollingPolicy>\n"
            + "        <encoder>\n"
            + "            <pattern>" + logPattern + "</pattern>\n"
            + "        </encoder>\n"
            + "    </appender>\n"
            + "\n"
            + "    <!-- Framework internals at INFO level -->\n"
            + "    <logger name=\"org.fractalx\" level=\"INFO\"/>\n"
            + "    <logger name=\"org.springframework\" level=\"WARN\"/>\n"
            + "    <logger name=\"io.grpc\" level=\"WARN\"/>\n"
            + "\n"
            + "    <root level=\"INFO\">\n"
            + "        <appender-ref ref=\"CONSOLE\"/>\n"
            + "        <appender-ref ref=\"FILE\"/>\n"
            + "    </root>\n"
            + "\n"
            + "</configuration>\n";
    }
}
