package com.fractalx.core.generator;

import com.fractalx.core.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates Spring Boot Application class for each microservice
 */
public class ApplicationGenerator {

    private static final Logger log = LoggerFactory.getLogger(ApplicationGenerator.class);

    public void generateApplicationClass(FractalModule module, Path srcMainJava) throws IOException {
        log.debug("Generating Application class for {}", module.getServiceName());

        // Create package directory
        String basePackage = "com.fractalx.generated." + module.getServiceName().replace("-", "");
        Path packagePath = createPackagePath(srcMainJava, basePackage);

        // Generate Application.java with correct class name
        String className = toPascalCase(module.getServiceName()) + "Application";
        String applicationContent = generateApplicationContent(module, basePackage, className);
        Path applicationPath = packagePath.resolve(className + ".java");
        Files.writeString(applicationPath, applicationContent);

        log.info("✓ Generated Application class: {}", className);
    }

    private Path createPackagePath(Path srcMainJava, String packageName) throws IOException {
        String[] parts = packageName.split("\\.");
        Path packagePath = srcMainJava;
        for (String part : parts) {
            packagePath = packagePath.resolve(part);
        }
        Files.createDirectories(packagePath);
        return packagePath;
    }

    private String generateApplicationContent(FractalModule module, String basePackage, String className) {
        String originalPackage = extractOriginalPackage(module);

        // Build component scan packages
        String componentScanPackages = String.format("\"%s\", \"%s\"", basePackage, originalPackage);

        // Generate complete Java class with imports
        StringBuilder content = new StringBuilder();

        // Package declaration
        content.append("package ").append(basePackage).append(";\n\n");

        // Import statements
        content.append("import org.springframework.boot.SpringApplication;\n");
        content.append("import org.springframework.boot.autoconfigure.SpringBootApplication;\n");
        content.append("import org.springframework.cloud.openfeign.EnableFeignClients;\n");
        content.append("import org.springframework.context.annotation.ComponentScan;\n\n");

        // JavaDoc comment
        content.append("/**\n");
        content.append(" * Main application class for ").append(module.getServiceName()).append("\n");
        content.append(" * Generated by FractalX Framework\n");
        content.append(" */\n");

        // Class declaration with annotations
        content.append("@SpringBootApplication\n");
        content.append("@EnableFeignClients(basePackages = {").append(componentScanPackages).append("})\n");
        content.append("@ComponentScan(basePackages = {").append(componentScanPackages).append("})\n");
        content.append("public class ").append(className).append(" {\n\n");

        // Main method
        content.append("    public static void main(String[] args) {\n");
        content.append("        SpringApplication.run(").append(className).append(".class, args);\n");
        content.append("    }\n");
        content.append("}\n");

        return content.toString();
    }

    private String extractOriginalPackage(FractalModule module) {
        // Extract base package from the module's package name
        // e.g., "com.fractalx.testapp.order" -> "com.fractalx.testapp"
        String packageName = module.getPackageName();
        if (packageName != null && !packageName.isEmpty()) {
            int lastDot = packageName.lastIndexOf('.');
            if (lastDot > 0) {
                return packageName.substring(0, lastDot);
            }
            return packageName;
        }
        return "com.fractalx.testapp";
    }

    private String toPascalCase(String kebabCase) {
        StringBuilder result = new StringBuilder();
        boolean capitalizeNext = true;

        for (char c : kebabCase.toCharArray()) {
            if (c == '-') {
                capitalizeNext = true;
            } else if (capitalizeNext) {
                result.append(Character.toUpperCase(c));
                capitalizeNext = false;
            } else {
                result.append(c);
            }
        }

        return result.toString();
    }
}