//package com.fractalx.core.generator;
//
//import com.fractalx.core.FractalModule;
//import org.slf4j.Logger;
//import org.slf4j.LoggerFactory;
//
//import java.io.IOException;
//import java.nio.file.Files;
//import java.nio.file.Path;
//
///**
// * Generates discovery client configuration for services
// */
//public class DiscoveryClientGenerator {
//    private static final Logger log = LoggerFactory.getLogger(DiscoveryClientGenerator.class);
//
//    public void generateDiscoveryClient(FractalModule module, Path srcMainJava) throws IOException {
//        log.info("Generating discovery client for: {}", module.getServiceName());
//
//        // Create package directory
//        String basePackage = "com.fractalx.generated." + module.getServiceName().replace("-", "");
//        Path packagePath = createPackagePath(srcMainJava, basePackage);
//
//        // Generate DiscoveryClientConfig.java
//        String configContent = generateDiscoveryConfigContent(module, basePackage);
//        Path configPath = packagePath.resolve("DiscoveryClientConfig.java");
//        Files.writeString(configPath, configContent);
//
//        // Generate DiscoveryHealthIndicator.java
//        String healthIndicatorContent = generateHealthIndicatorContent(module, basePackage);
//        Path healthIndicatorPath = packagePath.resolve("DiscoveryHealthIndicator.java");
//        Files.writeString(healthIndicatorPath, healthIndicatorContent);
//
//        log.info("✓ Generated discovery client for {}", module.getServiceName());
//    }
//
//    private Path createPackagePath(Path srcMainJava, String packageName) throws IOException {
//        String[] parts = packageName.split("\\.");
//        Path packagePath = srcMainJava;
//        for (String part : parts) {
//            packagePath = packagePath.resolve(part);
//        }
//        Files.createDirectories(packagePath);
//        return packagePath;
//    }
//
//    private String generateDiscoveryConfigContent(FractalModule module, String basePackage) {
//        // Create the template with PROPERLY ESCAPED % signs
//        String template =
//                "package " + basePackage + ";\n" +
//                        "\n" +
//                        "import com.fractalx.core.discovery.DiscoveryInitializer;\n" +
//                        "import com.fractalx.core.discovery.DiscoveryClient;\n" +
//                        "import org.springframework.beans.factory.annotation.Value;\n" +
//                        "import org.springframework.context.annotation.Bean;\n" +
//                        "import org.springframework.context.annotation.Configuration;\n" +
//                        "import org.springframework.boot.context.event.ApplicationReadyEvent;\n" +
//                        "import org.springframework.context.event.EventListener;\n" +
//                        "import org.springframework.web.client.RestTemplate;\n" +
//                        "import org.springframework.http.HttpEntity;\n" +
//                        "import org.springframework.http.HttpHeaders;\n" +
//                        "import org.springframework.http.MediaType;\n" +
//                        "import org.springframework.http.ResponseEntity;\n" +
//                        "import java.util.HashMap;\n" +
//                        "import java.util.Map;\n" +
//                        "import javax.annotation.PreDestroy;\n" +
//                        "\n" +
//                        "/**\n" +
//                        " * Discovery client configuration for " + module.getServiceName() + "\n" +
//                        " * Generated by FractalX Framework\n" +
//                        " */\n" +
//                        "@Configuration\n" +
//                        "public class DiscoveryClientConfig {\n" +
//                        "    \n" +
//                        "    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(DiscoveryClientConfig.class);\n" +
//                        "    \n" +
//                        "    @Value(\"${spring.application.name}\")\n" +
//                        "    private String serviceName;\n" +
//                        "    \n" +
//                        "    @Value(\"${fractalx.discovery.host:localhost}\")\n" +
//                        "    private String serviceHost;\n" +
//                        "    \n" +
//                        "    @Value(\"${server.port:8080}\")\n" +
//                        "    private int serverPort;\n" +
//                        "    \n" +
//                        "    @Value(\"${fractalx.discovery.heartbeat-interval:30000}\")\n" +
//                        "    private long heartbeatInterval;\n" +
//                        "    \n" +
//                        "    @Value(\"${fractalx.discovery.instance-ttl:90000}\")\n" +
//                        "    private long instanceTtl;\n" +
//                        "    \n" +
//                        "    @Value(\"${fractalx.discovery.registry-url:http://localhost:8761}\")\n" +
//                        "    private String registryUrl;\n" +
//                        "    \n" +
//                        "    @Value(\"${fractalx.discovery.auto-register:true}\")\n" +
//                        "    private boolean autoRegister;\n" +
//                        "    \n" +
//                        "    private DiscoveryInitializer discoveryInitializer;\n" +
//                        "    \n" +
//                        "    @Bean\n" +
//                        "    public DiscoveryInitializer discoveryInitializer() {\n" +
//                        "        discoveryInitializer = new DiscoveryInitializer(heartbeatInterval, instanceTtl);\n" +
//                        "        discoveryInitializer.setRegistryUrl(registryUrl);\n" +
//                        "        discoveryInitializer.initialize(serviceName, serviceHost, serverPort);\n" +
//                        "        \n" +
//                        "        // Register with discovery service\n" +
//                        "        if (autoRegister) {\n" +
//                        "            log.info(\"Auto-registering {} with discovery service\", serviceName);\n" +
//                        "            discoveryInitializer.registerWithDiscoveryService();\n" +
//                        "        }\n" +
//                        "        \n" +
//                        "        return discoveryInitializer;\n" +
//                        "    }\n" +
//                        "    \n" +
//                        "    @Bean\n" +
//                        "    public DiscoveryClient discoveryClient(DiscoveryInitializer initializer) {\n" +
//                        "        return initializer.getClient();\n" +
//                        "    }\n" +
//                        "    \n" +
//                        "    // Auto-register on application start\n" +
//                        "    @EventListener(ApplicationReadyEvent.class)\n" +
//                        "    public void registerWithDiscoveryService() {\n" +
//                        "        if (!autoRegister) {\n" +
//                        "            log.info(\"Auto-registration disabled for {}\", serviceName);\n" +
//                        "            return;\n" +
//                        "        }\n" +
//                        "        \n" +
//                        "        try {\n" +
//                        "            log.info(\"Registering {} with discovery service at {}\", serviceName, registryUrl);\n" +
//                        "            \n" +
//                        "            RestTemplate restTemplate = new RestTemplate();\n" +
//                        "            String registerUrl = registryUrl + \"/api/discovery/register\";\n" +
//                        "            \n" +
//                        "            // Create registration payload as Map (Spring will convert to JSON)\n" +
//                        "            Map<String, Object> payload = new HashMap<>();\n" +
//                        "            payload.put(\"serviceName\", serviceName);\n" +
//                        "            payload.put(\"host\", serviceHost);\n" +
//                        "            payload.put(\"port\", serverPort);\n" +
//                        "            payload.put(\"status\", \"UP\");\n" +
//                        "            \n" +
//                        "            // Create headers with proper Content-Type\n" +
//                        "            HttpHeaders headers = new HttpHeaders();\n" +
//                        "            headers.setContentType(MediaType.APPLICATION_JSON);\n" +
//                        "            \n" +
//                        "            HttpEntity<Map<String, Object>> request = new HttpEntity<>(payload, headers);\n" +
//                        "            \n" +
//                        "            // Make registration request\n" +
//                        "            ResponseEntity<String> response = restTemplate.postForEntity(registerUrl, request, String.class);\n" +
//                        "            log.info(\"Registration response for {}: {}\", serviceName, response.getBody());\n" +
//                        "            \n" +
//                        "        } catch (Exception e) {\n" +
//                        "            log.error(\"Failed to register {} with discovery service: {}\", serviceName, e.getMessage());\n" +
//                        "            log.debug(\"Registration error details:\", e);\n" +
//                        "        }\n" +
//                        "    }\n" +
//                        "    \n" +
//                        "    @PreDestroy\n" +
//                        "    public void cleanup() {\n" +
//                        "        if (discoveryInitializer != null) {\n" +
//                        "            discoveryInitializer.cleanup();\n" +
//                        "        }\n" +
//                        "    }\n" +
//                        "}\n";
//
//        return template;
//    }
//
//    private String generateHealthIndicatorContent(FractalModule module, String basePackage) {
//        String serviceName = module.getServiceName();
//        return """
//        package %s;
//
//        import com.fractalx.core.discovery.DiscoveryInitializer;
//        import org.springframework.boot.actuate.health.Health;
//        import org.springframework.boot.actuate.health.HealthIndicator;
//        import org.springframework.stereotype.Component;
//
//        /**
//         * Health indicator for %s discovery
//         * Generated by FractalX Framework
//         */
//        @Component
//        public class DiscoveryHealthIndicator implements HealthIndicator {
//
//            private final DiscoveryInitializer discoveryInitializer;
//
//            public DiscoveryHealthIndicator(DiscoveryInitializer discoveryInitializer) {
//                this.discoveryInitializer = discoveryInitializer;
//            }
//
//            @Override
//            public Health health() {
//                if (discoveryInitializer == null) {
//                    return Health.down()
//                            .withDetail("message", "Discovery not initialized")
//                            .withDetail("service", "%s")
//                            .build();
//                }
//
//                if (discoveryInitializer.isHealthy()) {
//                    return Health.up()
//                            .withDetail("message", "Discovery system is healthy")
//                            .withDetail("service", "%s")
//                            .withDetail("initialized", true)
//                            .withDetail("selfRegistered", true)
//                            .build();
//                } else {
//                    return Health.down()
//                            .withDetail("message", "Discovery system is unhealthy")
//                            .withDetail("service", "%s")
//                            .withDetail("initialized", true)
//                            .build();
//                }
//            }
//        }
//        """.formatted(
//                basePackage,
//                serviceName,  // For line 8
//                serviceName,  // For line 29
//                serviceName,  // For line 36
//                serviceName   // For line 42
//        );
//    }
//}

package com.fractalx.core.generator;

import com.fractalx.core.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates discovery client configuration for services
 */
public class DiscoveryClientGenerator {
    private static final Logger log = LoggerFactory.getLogger(DiscoveryClientGenerator.class);

    public void generateDiscoveryClient(FractalModule module, Path srcMainJava) throws IOException {
        log.info("Generating discovery client for: {}", module.getServiceName());

        // Create package directory
        String basePackage = "com.fractalx.generated." + module.getServiceName().replace("-", "");
        Path packagePath = createPackagePath(srcMainJava, basePackage);

        // Generate DiscoveryClientConfig.java
        String configContent = generateDiscoveryConfigContent(module, basePackage);
        Path configPath = packagePath.resolve("DiscoveryClientConfig.java");
        Files.writeString(configPath, configContent);

        // Generate DiscoveryHealthIndicator.java
        String healthIndicatorContent = generateHealthIndicatorContent(module, basePackage);
        Path healthIndicatorPath = packagePath.resolve("DiscoveryHealthIndicator.java");
        Files.writeString(healthIndicatorPath, healthIndicatorContent);

        log.info("✓ Generated discovery client for {}", module.getServiceName());
    }

    private Path createPackagePath(Path srcMainJava, String packageName) throws IOException {
        String[] parts = packageName.split("\\.");
        Path packagePath = srcMainJava;
        for (String part : parts) {
            packagePath = packagePath.resolve(part);
        }
        Files.createDirectories(packagePath);
        return packagePath;
    }

    private String generateDiscoveryConfigContent(FractalModule module, String basePackage) {
        // FIXED: Removed duplicate registration logic
        String template =
                "package " + basePackage + ";\n" +
                        "\n" +
                        "import com.fractalx.core.discovery.DiscoveryInitializer;\n" +
                        "import com.fractalx.core.discovery.DiscoveryClient;\n" +
                        "import org.springframework.beans.factory.annotation.Value;\n" +
                        "import org.springframework.context.annotation.Bean;\n" +
                        "import org.springframework.context.annotation.Configuration;\n" +
                        "import javax.annotation.PreDestroy;\n" +
                        "\n" +
                        "/**\n" +
                        " * Discovery client configuration for " + module.getServiceName() + "\n" +
                        " * Generated by FractalX Framework\n" +
                        " * NOTE: Service registration is handled by DiscoveryInitializer\n" +
                        " */\n" +
                        "@Configuration\n" +
                        "public class DiscoveryClientConfig {\n" +
                        "    \n" +
                        "    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(DiscoveryClientConfig.class);\n" +
                        "    \n" +
                        "    @Value(\"${spring.application.name}\")\n" +
                        "    private String serviceName;\n" +
                        "    \n" +
                        "    @Value(\"${fractalx.discovery.host:localhost}\")\n" +
                        "    private String serviceHost;\n" +
                        "    \n" +
                        "    @Value(\"${server.port:8080}\")\n" +
                        "    private int serverPort;\n" +
                        "    \n" +
                        "    @Value(\"${fractalx.discovery.heartbeat-interval:30000}\")\n" +
                        "    private long heartbeatInterval;\n" +
                        "    \n" +
                        "    @Value(\"${fractalx.discovery.instance-ttl:90000}\")\n" +
                        "    private long instanceTtl;\n" +
                        "    \n" +
                        "    @Value(\"${fractalx.discovery.registry-url:http://localhost:8761}\")\n" +
                        "    private String registryUrl;\n" +
                        "    \n" +
                        "    private DiscoveryInitializer discoveryInitializer;\n" +
                        "    \n" +
                        "    @Bean\n" +
                        "    public DiscoveryInitializer discoveryInitializer() {\n" +
                        "        log.info(\"Initializing DiscoveryInitializer for {}\", serviceName);\n" +
                        "        discoveryInitializer = new DiscoveryInitializer(heartbeatInterval, instanceTtl);\n" +
                        "        discoveryInitializer.setRegistryUrl(registryUrl);\n" +
                        "        discoveryInitializer.initialize(serviceName, serviceHost, serverPort);\n" +
                        "        \n" +
                        "        // Auto-registration is handled by DiscoveryInitializer.initialize() method\n" +
                        "        // Do NOT call registerWithDiscoveryService() here\n" +
                        "        \n" +
                        "        return discoveryInitializer;\n" +
                        "    }\n" +
                        "    \n" +
                        "    @Bean\n" +
                        "    public DiscoveryClient discoveryClient(DiscoveryInitializer initializer) {\n" +
                        "        return initializer.getClient();\n" +
                        "    }\n" +
                        "    \n" +
                        "    @PreDestroy\n" +
                        "    public void cleanup() {\n" +
                        "        if (discoveryInitializer != null) {\n" +
                        "            discoveryInitializer.cleanup();\n" +
                        "        }\n" +
                        "    }\n" +
                        "}\n";

        return template;
    }

    private String generateHealthIndicatorContent(FractalModule module, String basePackage) {
        String serviceName = module.getServiceName();
        return """
        package %s;
        
        import com.fractalx.core.discovery.DiscoveryInitializer;
        import org.springframework.boot.actuate.health.Health;
        import org.springframework.boot.actuate.health.HealthIndicator;
        import org.springframework.stereotype.Component;
        
        /**
         * Health indicator for %s discovery
         * Generated by FractalX Framework
         */
        @Component
        public class DiscoveryHealthIndicator implements HealthIndicator {
            
            private final DiscoveryInitializer discoveryInitializer;
            
            public DiscoveryHealthIndicator(DiscoveryInitializer discoveryInitializer) {
                this.discoveryInitializer = discoveryInitializer;
            }
            
            @Override
            public Health health() {
                if (discoveryInitializer == null) {
                    return Health.down()
                            .withDetail("message", "Discovery not initialized")
                            .withDetail("service", "%s")
                            .build();
                }
                
                if (discoveryInitializer.isHealthy()) {
                    return Health.up()
                            .withDetail("message", "Discovery system is healthy")
                            .withDetail("service", "%s")
                            .withDetail("initialized", true)
                            .withDetail("selfRegistered", true)
                            .build();
                } else {
                    return Health.down()
                            .withDetail("message", "Discovery system is unhealthy")
                            .withDetail("service", "%s")
                            .withDetail("initialized", true)
                            .build();
                }
            }
        }
        """.formatted(
                basePackage,
                serviceName,
                serviceName,
                serviceName,
                serviceName
        );
    }
}