package com.fractalx.core.generator;

import com.fractalx.core.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates discovery configuration for services
 */
public class DiscoveryConfigGenerator {

    private static final Logger log = LoggerFactory.getLogger(DiscoveryConfigGenerator.class);

    public void generateDiscoveryConfig(List<FractalModule> modules, Path outputRoot) throws IOException {
        log.info("Generating discovery configuration for {} services", modules.size());

        // Generate central discovery configuration
        Path configDir = outputRoot.resolve("config");
        Files.createDirectories(configDir);

        // Generate discovery-config.yml
        String yamlContent = generateDiscoveryYaml(modules);
        Path yamlPath = configDir.resolve("discovery-config.yml");
        Files.writeString(yamlPath, yamlContent);

        // Generate service-specific discovery properties
        for (FractalModule module : modules) {
            generateServiceDiscoveryConfig(module, outputRoot);
        }

        log.info("✓ Generated discovery configuration");
    }

    private String generateDiscoveryYaml(List<FractalModule> modules) {
        StringBuilder yaml = new StringBuilder();
        yaml.append("# FractalX Discovery Configuration\n");
        yaml.append("# Auto-generated by FractalX Framework\n\n");

        yaml.append("fractalx:\n");
        yaml.append("  discovery:\n");
        yaml.append("    enabled: true\n");
        yaml.append("    mode: HYBRID\n");
        yaml.append("    heartbeat-interval: 30000\n");
        yaml.append("    instance-ttl: 90000\n\n");

        yaml.append("# Static service configuration\n");
        yaml.append("services:\n");

        for (FractalModule module : modules) {
            yaml.append("  ").append(module.getServiceName()).append(":\n");
            yaml.append("    - host: localhost\n");
            yaml.append("      port: ").append(module.getPort()).append("\n");

            if (!module.getDependencies().isEmpty()) {
                yaml.append("    dependencies:\n");
                for (String dep : module.getDependencies()) {
                    yaml.append("      - ").append(dep).append("\n");
                }
            }
            yaml.append("\n");
        }

        return yaml.toString();
    }

    private void generateServiceDiscoveryConfig(FractalModule module, Path outputRoot) throws IOException {
        Path serviceRoot = outputRoot.resolve(module.getServiceName());
        Path srcMainResources = serviceRoot.resolve("src/main/resources");

        // Ensure resources directory exists
        Files.createDirectories(srcMainResources);

        // Generate application-discovery.yml
        String discoveryYml = generateServiceDiscoveryYml(module);
        Path discoveryPath = srcMainResources.resolve("application-discovery.yml");
        Files.writeString(discoveryPath, discoveryYml);

        log.debug("Generated discovery config for: {}", module.getServiceName());
    }

    private String generateServiceDiscoveryYml(FractalModule module) {
        return String.format("""
            # Discovery Configuration for %s
            fractalx:
              discovery:
                enabled: true
                host: localhost
                port: %d
                mode: HYBRID
                config-file: classpath:discovery-config.yml
                
            # Service Info
            service:
              name: %s
              version: 1.0.0
              description: Generated by FractalX Framework
              
            # Health Check
            management:
              endpoints:
                web:
                  exposure:
                    include: health,discovery
              endpoint:
                health:
                  show-details: always
            """,
                module.getServiceName(),
                module.getPort(),
                module.getServiceName()
        );
    }
}