package com.fractalx.core.generator;

import com.fractalx.core.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates discovery client configuration for services
 */
public class DiscoveryClientGenerator {
    private static final Logger log = LoggerFactory.getLogger(DiscoveryClientGenerator.class);

    public void generateDiscoveryClient(FractalModule module, Path srcMainJava) throws IOException {
        log.info("Generating discovery client for: {}", module.getServiceName());

        // Create package directory
        String basePackage = "com.fractalx.generated." + module.getServiceName().replace("-", "");
        Path packagePath = createPackagePath(srcMainJava, basePackage);

        // Generate DiscoveryClientConfig.java
        String configContent = generateDiscoveryConfigContent(module, basePackage);
        Path configPath = packagePath.resolve("DiscoveryClientConfig.java");
        Files.writeString(configPath, configContent);

        // Generate DiscoveryHealthIndicator.java
        String healthIndicatorContent = generateHealthIndicatorContent(module, basePackage);
        Path healthIndicatorPath = packagePath.resolve("DiscoveryHealthIndicator.java");
        Files.writeString(healthIndicatorPath, healthIndicatorContent);

        log.info("✓ Generated discovery client for {}", module.getServiceName());
    }

    private Path createPackagePath(Path srcMainJava, String packageName) throws IOException {
        String[] parts = packageName.split("\\.");
        Path packagePath = srcMainJava;
        for (String part : parts) {
            packagePath = packagePath.resolve(part);
        }
        Files.createDirectories(packagePath);
        return packagePath;
    }

    private String generateDiscoveryConfigContent(FractalModule module, String basePackage) {
        return String.format("""
            package %s;
            
            import com.fractalx.core.discovery.DiscoveryInitializer;
            import com.fractalx.core.discovery.DiscoveryClient;
            import org.springframework.beans.factory.annotation.Value;
            import org.springframework.context.annotation.Bean;
            import org.springframework.context.annotation.Configuration;
            import javax.annotation.PreDestroy;
            
            /**
             * Discovery client configuration for %s
             * Generated by FractalX Framework
             */
            @Configuration
            public class DiscoveryClientConfig {
                
                @Value("${spring.application.name}")
                private String serviceName;
                
                @Value("${fractalx.discovery.host:localhost}")
                private String serviceHost;
                
                @Value("${server.port:8080}")
                private int serverPort;
                
                @Value("${fractalx.discovery.heartbeat-interval:30000}")
                private long heartbeatInterval;
                
                @Value("${fractalx.discovery.instance-ttl:90000}")
                private long instanceTtl;
                
                private DiscoveryInitializer discoveryInitializer;
                
                @Bean
                public DiscoveryInitializer discoveryInitializer() {
                    discoveryInitializer = new DiscoveryInitializer(heartbeatInterval, instanceTtl);
                    discoveryInitializer.initialize(serviceName, serviceHost, serverPort);
                    return discoveryInitializer;
                }
                
                @Bean
                public DiscoveryClient discoveryClient(DiscoveryInitializer initializer) {
                    return initializer.getClient();
                }
                
                @PreDestroy
                public void cleanup() {
                    if (discoveryInitializer != null) {
                        discoveryInitializer.cleanup();
                    }
                }
            }
            """, basePackage, module.getServiceName());
    }

    private String generateHealthIndicatorContent(FractalModule module, String basePackage) {
        return String.format("""
            package %s;
            
            import com.fractalx.core.discovery.DiscoveryInitializer;
            import org.springframework.boot.actuate.health.Health;
            import org.springframework.boot.actuate.health.HealthIndicator;
            import org.springframework.stereotype.Component;
            
            /**
             * Health indicator for %s discovery
             * Generated by FractalX Framework
             */
            @Component
            public class DiscoveryHealthIndicator implements HealthIndicator {
                
                private final DiscoveryInitializer discoveryInitializer;
                
                public DiscoveryHealthIndicator(DiscoveryInitializer discoveryInitializer) {
                    this.discoveryInitializer = discoveryInitializer;
                }
                
                @Override
                public Health health() {
                    if (discoveryInitializer == null) {
                        return Health.down()
                                .withDetail("message", "Discovery not initialized")
                                .withDetail("service", "%s")
                                .build();
                    }
                    
                    if (discoveryInitializer.isHealthy()) {
                        return Health.up()
                                .withDetail("message", "Discovery system is healthy")
                                .withDetail("service", "%s")
                                .withDetail("initialized", true)
                                .withDetail("selfRegistered", true)
                                .build();
                    } else {
                        return Health.down()
                                .withDetail("message", "Discovery system is unhealthy")
                                .withDetail("service", "%s")
                                .withDetail("initialized", true)
                                .build();
                    }
                }
            }
            """, basePackage, module.getServiceName(),
                module.getServiceName(), module.getServiceName(), module.getServiceName());
    }
}