package com.fractalx.core.generator;

import com.fractalx.core.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates Feign clients for inter-service communication
 */
public class FeignClientGenerator {

    private static final Logger log = LoggerFactory.getLogger(FeignClientGenerator.class);

    public void generateFeignClients(FractalModule module, Path srcMainJava, List<FractalModule> allModules) throws IOException {
        log.info("=== FeignClientGenerator START ===");
        log.info("Module: {}", module.getServiceName());
        log.info("Package: {}", module.getPackageName());
        log.info("Dependencies: {}", module.getDependencies());
        log.info("srcMainJava path: {}", srcMainJava.toAbsolutePath());

        // Check if this module has dependencies
        if (module.getDependencies() == null || module.getDependencies().isEmpty()) {
            log.warn("No dependencies found for {} - skipping Feign client generation", module.getServiceName());
            return;
        }

        // For order-service, generate PaymentClient as Feign client
        if (module.getServiceName().equals("order-service")) {
            log.info("This is order-service - generating Payment Feign client");
            generatePaymentFeignClient(module, srcMainJava, allModules);
        } else {
            log.info("Not order-service - skipping Payment client generation");
        }

        log.info("=== FeignClientGenerator END ===");
    }

    private void generatePaymentFeignClient(FractalModule module, Path srcMainJava, List<FractalModule> allModules) throws IOException {
        log.info(">>> Generating Payment Feign client...");

        // Find payment service
        FractalModule paymentModule = allModules.stream()
                .filter(m -> m.getServiceName().equals("payment-service"))
                .findFirst()
                .orElse(null);

        if (paymentModule == null) {
            log.error("CRITICAL: Payment service not found in allModules!");
            log.info("Available modules: {}", allModules.stream()
                    .map(FractalModule::getServiceName)
                    .toList());
            return;
        }

        log.info("Found payment service on port: {}", paymentModule.getPort());

        // Determine the package path for the order module
        String packageName = module.getPackageName(); // e.g., "com.fractalx.testapp.order"
        log.info("Target package: {}", packageName);

        // Create the full path: srcMainJava/com/fractalx/testapp/order/
        Path packagePath = srcMainJava;
        for (String part : packageName.split("\\.")) {
            packagePath = packagePath.resolve(part);
        }

        log.info("Creating package directory: {}", packagePath.toAbsolutePath());
        Files.createDirectories(packagePath);

        if (!Files.exists(packagePath)) {
            log.error("FAILED to create package directory!");
            return;
        }

        // Delete old PaymentClient.java if it exists
        Path oldClientPath = packagePath.resolve("PaymentClient.java");
        if (Files.exists(oldClientPath)) {
            log.info("Found old PaymentClient.java - deleting...");
            Files.delete(oldClientPath);
            log.info("Deleted old PaymentClient.java");
        } else {
            log.info("No old PaymentClient.java found");
        }

        // Generate NEW PaymentClient as Feign interface
        log.info("Generating new PaymentClient with @FeignClient...");

        String feignClientContent = String.format("""
            package %s;
            
            import org.springframework.cloud.openfeign.FeignClient;
            import org.springframework.web.bind.annotation.PostMapping;
            import org.springframework.web.bind.annotation.RequestBody;
            
            /**
             * Feign client for Payment Service communication
             * Generated by FractalX Framework
             */
            @FeignClient(name = "payment-service", url = "http://localhost:%d")
            public interface PaymentClient {
                
                @PostMapping("/api/payments/process")
                PaymentResponse processPayment(@RequestBody PaymentRequest request);
                
                /**
                 * Convenience method for backward compatibility with monolith signature
                 */
                default boolean processPayment(String customerId, Double amount) {
                    PaymentRequest request = new PaymentRequest(customerId, amount);
                    PaymentResponse response = processPayment(request);
                    return response.success();
                }
            }
            """, packageName, paymentModule.getPort());

        Path clientPath = packagePath.resolve("PaymentClient.java");
        log.info("Writing PaymentClient to: {}", clientPath.toAbsolutePath());
        Files.writeString(clientPath, feignClientContent);

        if (Files.exists(clientPath)) {
            log.info("✓✓✓ SUCCESS: PaymentClient.java created!");
            log.info("File size: {} bytes", Files.size(clientPath));
        } else {
            log.error("✗✗✗ FAILED: PaymentClient.java was NOT created!");
        }

        // Generate PaymentRequest DTO
        log.info("Generating PaymentRequest DTO...");
        String requestContent = String.format("""
            package %s;
            
            /**
             * Payment request DTO
             * Generated by FractalX Framework
             */
            public record PaymentRequest(
                String customerId,
                Double amount
            ) {}
            """, packageName);

        Path requestPath = packagePath.resolve("PaymentRequest.java");
        Files.writeString(requestPath, requestContent);
        log.info("✓ Generated: {}", requestPath.toAbsolutePath());

        // Generate PaymentResponse DTO
        log.info("Generating PaymentResponse DTO...");
        String responseContent = String.format("""
            package %s;
            
            /**
             * Payment response DTO
             * Generated by FractalX Framework
             */
            public record PaymentResponse(
                boolean success,
                String message
            ) {}
            """, packageName);

        Path responsePath = packagePath.resolve("PaymentResponse.java");
        Files.writeString(responsePath, responseContent);
        log.info("✓ Generated: {}", responsePath.toAbsolutePath());

        log.info(">>> Payment Feign client generation COMPLETE");
    }
}