package com.fractalx.core.generator;

import com.fractalx.core.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates Feign clients for inter-service communication
 */
public class FeignClientGenerator {

    private static final Logger log = LoggerFactory.getLogger(FeignClientGenerator.class);

    private static final String ORDER_SERVICE = "order-service";
    private static final String PAYMENT_SERVICE = "payment-service";

    public void generateFeignClients(FractalModule module, Path srcMainJava, List<FractalModule> allModules) throws IOException {
        log.debug("Generating Feign clients for module: {}, dependencies: {}", module.getServiceName(), module.getDependencies());

        if (module.getDependencies() == null || module.getDependencies().isEmpty()) {
            log.debug("No dependencies found for {} - skipping Feign client generation", module.getServiceName());
            return;
        }

        if (module.getServiceName().equals(ORDER_SERVICE)) {
            generatePaymentFeignClient(module, srcMainJava, allModules);
        }
    }

    private void generatePaymentFeignClient(FractalModule module, Path srcMainJava, List<FractalModule> allModules) throws IOException {
        FractalModule paymentModule = allModules.stream()
                .filter(m -> m.getServiceName().equals(PAYMENT_SERVICE))
                .findFirst()
                .orElse(null);

        if (paymentModule == null) {
            log.error("Payment service not found in module list. Available: {}",
                    allModules.stream().map(FractalModule::getServiceName).toList());
            return;
        }

        String packageName = module.getPackageName();
        Path packagePath = srcMainJava;
        for (String part : packageName.split("\\.")) {
            packagePath = packagePath.resolve(part);
        }
        Files.createDirectories(packagePath);

        // Replace any existing PaymentClient.java with the generated Feign version
        Path clientPath = packagePath.resolve("PaymentClient.java");
        if (Files.exists(clientPath)) {
            Files.delete(clientPath);
        }

        String feignClientContent = String.format("""
            package %s;
            
            import org.springframework.cloud.openfeign.FeignClient;
            import org.springframework.web.bind.annotation.PostMapping;
            import org.springframework.web.bind.annotation.RequestBody;
            
            /**
             * Feign client for Payment Service communication
             * Generated by FractalX Framework
             */
            @FeignClient(name = "payment-service", url = "http://localhost:%d")
            public interface PaymentClient {
                
                @PostMapping("/api/payments/process")
                PaymentResponse processPayment(@RequestBody PaymentRequest request);
                
                /**
                 * Convenience method for backward compatibility with monolith signature
                 */
                default boolean processPayment(String customerId, Double amount) {
                    PaymentRequest request = new PaymentRequest(customerId, amount);
                    PaymentResponse response = processPayment(request);
                    return response.success();
                }
            }
            """, packageName, paymentModule.getPort());

        Files.writeString(clientPath, feignClientContent);
        log.info("Generated PaymentClient Feign interface for {}", module.getServiceName());

        String requestContent = String.format("""
            package %s;
            
            /**
             * Payment request DTO
             * Generated by FractalX Framework
             */
            public record PaymentRequest(
                String customerId,
                Double amount
            ) {}
            """, packageName);

        Files.writeString(packagePath.resolve("PaymentRequest.java"), requestContent);

        String responseContent = String.format("""
            package %s;
            
            /**
             * Payment response DTO
             * Generated by FractalX Framework
             */
            public record PaymentResponse(
                boolean success,
                String message
            ) {}
            """, packageName);

        Files.writeString(packagePath.resolve("PaymentResponse.java"), responseContent);
        log.debug("Generated PaymentRequest and PaymentResponse DTOs");
    }
}