package com.fractalx.core.generator;

import com.fractalx.core.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates Feign clients for inter-service communication
 */
public class FeignClientGenerator {

    private static final Logger log = LoggerFactory.getLogger(FeignClientGenerator.class);

    public void generateFeignClients(FractalModule module, Path srcMainJava, List<FractalModule> allModules) throws IOException {
        log.debug("Generating Feign clients for {}", module.getServiceName());

        // Check if this module has dependencies
        if (module.getDependencies() == null || module.getDependencies().isEmpty()) {
            log.debug("No dependencies found for {}", module.getServiceName());
            return;
        }

        // For order-service, generate PaymentClient as Feign client
        if (module.getServiceName().equals("order-service")) {
            generatePaymentFeignClient(module, srcMainJava, allModules);
        }
    }

    private void generatePaymentFeignClient(FractalModule module, Path srcMainJava, List<FractalModule> allModules) throws IOException {
        // Find payment service
        FractalModule paymentModule = allModules.stream()
                .filter(m -> m.getServiceName().equals("payment-service"))
                .findFirst()
                .orElse(null);

        if (paymentModule == null) {
            log.warn("Payment service not found for Feign client generation");
            return;
        }

        String packageName = module.getPackageName();
        Path packagePath = srcMainJava;
        for (String part : packageName.split("\\.")) {
            packagePath = packagePath.resolve(part);
        }
        Files.createDirectories(packagePath);

        // Generate NEW PaymentClient as Feign interface (replaces old one)
        String feignClientContent = """
            package %s;
            
            import org.springframework.cloud.openfeign.FeignClient;
            import org.springframework.web.bind.annotation.PostMapping;
            import org.springframework.web.bind.annotation.RequestBody;
            
            /**
             * Feign client for Payment Service communication
             * Generated by FractalX Framework
             */
            @FeignClient(name = "payment-service", url = "http://localhost:%d")
            public interface PaymentClient {
                
                @PostMapping("/api/payments/process")
                PaymentResponse processPayment(@RequestBody PaymentRequest request);
                
                /**
                 * Convenience method for backward compatibility
                 */
                default boolean processPayment(String customerId, Double amount) {
                    PaymentRequest request = new PaymentRequest(customerId, amount);
                    PaymentResponse response = processPayment(request);
                    return response.success();
                }
            }
            """.formatted(packageName, paymentModule.getPort());

        Path clientPath = packagePath.resolve("PaymentClient.java");
        Files.writeString(clientPath, feignClientContent);
        log.info("✓ Generated Feign client: PaymentClient (replaced old interface)");

        // Generate PaymentRequest DTO
        String requestContent = """
            package %s;
            
            /**
             * Payment request DTO
             * Generated by FractalX Framework
             */
            public record PaymentRequest(
                String customerId,
                Double amount
            ) {}
            """.formatted(packageName);

        Path requestPath = packagePath.resolve("PaymentRequest.java");
        Files.writeString(requestPath, requestContent);
        log.debug("Generated PaymentRequest DTO");

        // Generate PaymentResponse DTO
        String responseContent = """
            package %s;
            
            /**
             * Payment response DTO
             * Generated by FractalX Framework
             */
            public record PaymentResponse(
                boolean success,
                String message
            ) {}
            """.formatted(packageName);

        Path responsePath = packagePath.resolve("PaymentResponse.java");
        Files.writeString(responsePath, responseContent);
        log.debug("Generated PaymentResponse DTO");
    }
}