package org.fractalx.core.generator.admin;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates the user management sub-system for the admin service:
 * <ul>
 *   <li>{@code UserStoreService}  — interface satisfied by both in-memory and JPA stores</li>
 *   <li>{@code SettingsStoreService} — interface for settings stores</li>
 *   <li>{@code AdminUser}     — JPA entity + user model</li>
 *   <li>{@code UserStore}     — in-memory store, active when {@code db} profile is NOT active</li>
 *   <li>{@code AdminSettings} — JPA entity + settings model</li>
 *   <li>{@code SettingsStore} — in-memory store, active when {@code db} profile is NOT active</li>
 *   <li>{@code UserController} — REST API for user CRUD, password management, settings</li>
 * </ul>
 *
 * <p>JPA-backed stores ({@code JpaUserStore}, {@code JpaSettingsStore}) are generated by
 * {@link AdminDatabaseGenerator} and are active only when {@code -Dspring.profiles.active=db}.
 */
class AdminUserManagementGenerator {

    private static final Logger log = LoggerFactory.getLogger(AdminUserManagementGenerator.class);

    void generate(Path srcMainJava, String basePackage) throws IOException {
        Path pkg = AdminPackageUtil.createPackagePath(srcMainJava, basePackage + ".user");

        generateUserStoreService(pkg);
        generateSettingsStoreService(pkg);
        generateAdminUser(pkg);
        generateUserStore(pkg);
        generateAdminSettings(pkg);
        generateSettingsStore(pkg);
        generateUserController(pkg);

        log.debug("Generated admin user management components");
    }

    // -------------------------------------------------------------------------

    private void generateUserStoreService(Path pkg) throws IOException {
        String content = """
                package org.fractalx.admin.user;

                import java.util.List;
                import java.util.Optional;
                import java.util.Set;

                /**
                 * Abstraction over admin user storage.
                 * <p>Two implementations:
                 * <ul>
                 *   <li>{@link UserStore}    — in-memory (default, no datasource required)</li>
                 *   <li>{@code JpaUserStore} — Spring Data JPA, active with {@code @Profile("db")}</li>
                 * </ul>
                 */
                public interface UserStoreService {

                    Optional<AdminUser> findByUsername(String username);
                    List<AdminUser>     findAll();
                    AdminUser           create(String username, String rawPassword, Set<String> roles);
                    boolean             changePassword(String username, String rawPassword);
                    boolean             updateRoles(String username, Set<String> roles);
                    boolean             setActive(String username, boolean active);
                    boolean             delete(String username);
                    void                recordLogin(String username);
                    int                 count();
                }
                """;
        Files.writeString(pkg.resolve("UserStoreService.java"), content);
    }

    private void generateSettingsStoreService(Path pkg) throws IOException {
        String content = """
                package org.fractalx.admin.user;

                /**
                 * Abstraction over admin settings storage.
                 * <p>Two implementations:
                 * <ul>
                 *   <li>{@link SettingsStore}    — in-memory (default)</li>
                 *   <li>{@code JpaSettingsStore} — Spring Data JPA, active with {@code @Profile("db")}</li>
                 * </ul>
                 */
                public interface SettingsStoreService {

                    AdminSettings get();
                    void          update(AdminSettings settings);
                }
                """;
        Files.writeString(pkg.resolve("SettingsStoreService.java"), content);
    }

    private void generateAdminUser(Path pkg) throws IOException {
        String content = """
                package org.fractalx.admin.user;

                import jakarta.persistence.*;
                import java.util.Set;

                /**
                 * Represents an admin dashboard user.
                 * Annotated as a JPA {@code @Entity} — active in DB mode (profile {@code db}),
                 * harmless in memory mode (JPA autoconfiguration is excluded by default).
                 *
                 * <p>Passwords are stored as BCrypt hashes — never in plaintext.
                 * <p>Supported roles: {@code ROLE_ADMIN}, {@code ROLE_OPERATOR}, {@code ROLE_VIEWER}
                 */
                @Entity
                @Table(name = "admin_users")
                public class AdminUser {

                    @Id
                    @Column(name = "username", nullable = false, length = 100)
                    private String      username;

                    @Column(name = "password_hash", nullable = false)
                    private String      passwordHash;   // BCrypt encoded

                    @ElementCollection(fetch = FetchType.EAGER)
                    @CollectionTable(name = "admin_user_roles",
                                     joinColumns = @JoinColumn(name = "username"))
                    @Column(name = "role")
                    private Set<String> roles;          // e.g. { "ROLE_ADMIN" }

                    @Column(name = "created_at")
                    private String      createdAt;

                    @Column(name = "last_login_at")
                    private String      lastLoginAt;

                    @Column(name = "active")
                    private boolean     active;

                    public AdminUser() {}

                    public AdminUser(String username, String passwordHash,
                                     Set<String> roles, String createdAt) {
                        this.username     = username;
                        this.passwordHash = passwordHash;
                        this.roles        = roles;
                        this.createdAt    = createdAt;
                        this.active       = true;
                    }

                    public String      getUsername()     { return username; }
                    public void        setUsername(String u)  { this.username = u; }

                    public String      getPasswordHash() { return passwordHash; }
                    public void        setPasswordHash(String h) { this.passwordHash = h; }

                    public Set<String> getRoles()        { return roles; }
                    public void        setRoles(Set<String> r) { this.roles = r; }

                    public String      getCreatedAt()    { return createdAt; }
                    public void        setCreatedAt(String c) { this.createdAt = c; }

                    public String      getLastLoginAt()  { return lastLoginAt; }
                    public void        setLastLoginAt(String l) { this.lastLoginAt = l; }

                    public boolean     isActive()        { return active; }
                    public void        setActive(boolean a) { this.active = a; }
                }
                """;
        Files.writeString(pkg.resolve("AdminUser.java"), content);
    }

    private void generateUserStore(Path pkg) throws IOException {
        String content = """
                package org.fractalx.admin.user;

                import jakarta.annotation.PostConstruct;
                import org.springframework.context.annotation.Profile;
                import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
                import org.springframework.security.crypto.password.PasswordEncoder;
                import org.springframework.stereotype.Component;

                import java.time.Instant;
                import java.util.*;
                import java.util.concurrent.CopyOnWriteArrayList;

                /**
                 * Thread-safe in-memory user store. Active when the {@code db} profile is NOT active.
                 *
                 * <p>Pre-seeded at startup with:
                 * <ul>
                 *   <li>{@code admin / admin123} → ROLE_ADMIN</li>
                 *   <li>{@code viewer / viewer123} → ROLE_VIEWER</li>
                 * </ul>
                 * <p><b>Note:</b> Changes are in-memory only and reset on restart.
                 * Activate the {@code db} profile for persistent storage.
                 */
                @Component
                @Profile("!db")
                public class UserStore implements UserStoreService {

                    private final List<AdminUser>   users   = new CopyOnWriteArrayList<>();
                    private final PasswordEncoder   encoder = new BCryptPasswordEncoder();

                    @PostConstruct
                    public void init() {
                        create("admin",  "admin123",  Set.of("ROLE_ADMIN"));
                        create("viewer", "viewer123", Set.of("ROLE_VIEWER"));
                    }

                    @Override
                    public Optional<AdminUser> findByUsername(String username) {
                        return users.stream()
                                .filter(u -> u.getUsername().equals(username))
                                .findFirst();
                    }

                    @Override
                    public List<AdminUser> findAll() {
                        return Collections.unmodifiableList(users);
                    }

                    @Override
                    public AdminUser create(String username, String rawPassword, Set<String> roles) {
                        AdminUser user = new AdminUser(
                                username,
                                encoder.encode(rawPassword),
                                new HashSet<>(roles),
                                Instant.now().toString());
                        users.add(user);
                        return user;
                    }

                    @Override
                    public boolean changePassword(String username, String rawPassword) {
                        return findByUsername(username).map(u -> {
                            u.setPasswordHash(encoder.encode(rawPassword));
                            return true;
                        }).orElse(false);
                    }

                    @Override
                    public boolean updateRoles(String username, Set<String> roles) {
                        return findByUsername(username).map(u -> {
                            u.setRoles(new HashSet<>(roles));
                            return true;
                        }).orElse(false);
                    }

                    @Override
                    public boolean setActive(String username, boolean active) {
                        return findByUsername(username).map(u -> {
                            u.setActive(active);
                            return true;
                        }).orElse(false);
                    }

                    @Override
                    public boolean delete(String username) {
                        return users.removeIf(u -> u.getUsername().equals(username));
                    }

                    @Override
                    public void recordLogin(String username) {
                        findByUsername(username).ifPresent(u ->
                                u.setLastLoginAt(Instant.now().toString()));
                    }

                    @Override
                    public int count() { return users.size(); }
                }
                """;
        Files.writeString(pkg.resolve("UserStore.java"), content);
    }

    private void generateAdminSettings(Path pkg) throws IOException {
        String content = """
                package org.fractalx.admin.user;

                import jakarta.persistence.*;

                /**
                 * Admin-wide settings for the FractalX admin dashboard.
                 * Annotated as a JPA {@code @Entity} — active in DB mode, harmless in memory mode.
                 *
                 * <p>A singleton row with {@code id=1} is maintained in the database.
                 * In memory mode the {@code id} field is ignored.
                 */
                @Entity
                @Table(name = "admin_settings")
                public class AdminSettings {

                    @Id
                    @Column(name = "id")
                    private int     id                = 1;   // singleton row — always 1

                    @Column(name = "site_name")
                    private String  siteName          = "FractalX Admin";

                    @Column(name = "theme")
                    private String  theme             = "light";   // light | dark

                    @Column(name = "session_timeout_min")
                    private int     sessionTimeoutMin = 30;

                    @Column(name = "default_alert_email")
                    private String  defaultAlertEmail = "";

                    @Column(name = "maintenance_mode")
                    private boolean maintenanceMode   = false;

                    public int     getId()                         { return id; }
                    public void    setId(int id)                   { this.id = id; }

                    public String  getSiteName()                   { return siteName; }
                    public void    setSiteName(String s)           { this.siteName = s; }

                    public String  getTheme()                      { return theme; }
                    public void    setTheme(String t)              { this.theme = t; }

                    public int     getSessionTimeoutMin()          { return sessionTimeoutMin; }
                    public void    setSessionTimeoutMin(int m)     { this.sessionTimeoutMin = m; }

                    public String  getDefaultAlertEmail()          { return defaultAlertEmail; }
                    public void    setDefaultAlertEmail(String e)  { this.defaultAlertEmail = e; }

                    public boolean isMaintenanceMode()             { return maintenanceMode; }
                    public void    setMaintenanceMode(boolean m)   { this.maintenanceMode = m; }
                }
                """;
        Files.writeString(pkg.resolve("AdminSettings.java"), content);
    }

    private void generateSettingsStore(Path pkg) throws IOException {
        String content = """
                package org.fractalx.admin.user;

                import org.springframework.context.annotation.Profile;
                import org.springframework.stereotype.Component;

                import java.util.concurrent.atomic.AtomicReference;

                /**
                 * Thread-safe in-memory holder for the singleton {@link AdminSettings} instance.
                 * Active when the {@code db} profile is NOT active.
                 *
                 * <p>Activate the {@code db} profile for persistent settings storage.
                 */
                @Component
                @Profile("!db")
                public class SettingsStore implements SettingsStoreService {

                    private final AtomicReference<AdminSettings> settings =
                            new AtomicReference<>(new AdminSettings());

                    @Override
                    public AdminSettings get()                    { return settings.get(); }

                    @Override
                    public void          update(AdminSettings s)  { settings.set(s); }
                }
                """;
        Files.writeString(pkg.resolve("SettingsStore.java"), content);
    }

    private void generateUserController(Path pkg) throws IOException {
        String content = """
                package org.fractalx.admin.user;

                import org.springframework.http.ResponseEntity;
                import org.springframework.security.core.Authentication;
                import org.springframework.security.core.context.SecurityContextHolder;
                import org.springframework.web.bind.annotation.*;

                import java.util.*;

                /**
                 * REST API for user management and admin settings.
                 *
                 * <pre>
                 * GET    /api/users                        — list all users (passwords masked)
                 * POST   /api/users                        — create a new user
                 * PUT    /api/users/{username}             — update user (active flag)
                 * DELETE /api/users/{username}             — delete a user
                 * PUT    /api/users/{username}/password    — change password
                 * PUT    /api/users/{username}/roles       — update roles
                 * GET    /api/settings                     — get admin settings
                 * PUT    /api/settings                     — update admin settings
                 * GET    /api/auth/profile                 — current authenticated user info
                 * </pre>
                 *
                 * <p>Injected via {@link UserStoreService} / {@link SettingsStoreService} interfaces,
                 * so both in-memory (default) and JPA (db profile) stores are transparently supported.
                 */
                @RestController
                @RequestMapping("/api/users")
                @CrossOrigin(origins = "*")
                public class UserController {

                    private final UserStoreService     userStore;
                    private final SettingsStoreService settingsStore;

                    public UserController(UserStoreService userStore, SettingsStoreService settingsStore) {
                        this.userStore     = userStore;
                        this.settingsStore = settingsStore;
                    }

                    // ---- Users ---------------------------------------------------------------

                    @GetMapping("/api/users")
                    public ResponseEntity<List<Map<String, Object>>> listUsers() {
                        List<Map<String, Object>> result = new ArrayList<>();
                        for (AdminUser u : userStore.findAll()) {
                            Map<String, Object> entry = new LinkedHashMap<>();
                            entry.put("username",    u.getUsername());
                            entry.put("passwordHash","***");         // never expose hash
                            entry.put("roles",       u.getRoles());
                            entry.put("active",      u.isActive());
                            entry.put("createdAt",   u.getCreatedAt());
                            entry.put("lastLoginAt", u.getLastLoginAt());
                            result.add(entry);
                        }
                        return ResponseEntity.ok(result);
                    }

                    @PostMapping("/api/users")
                    public ResponseEntity<Map<String, Object>> createUser(
                            @RequestBody Map<String, Object> body) {
                        String username = (String) body.get("username");
                        String password = (String) body.get("password");
                        @SuppressWarnings("unchecked")
                        List<String> roleList = (List<String>) body.getOrDefault("roles",
                                List.of("ROLE_VIEWER"));

                        if (username == null || username.isBlank() || password == null || password.isBlank()) {
                            return ResponseEntity.badRequest()
                                    .body(Map.of("error", "username and password are required"));
                        }
                        if (userStore.findByUsername(username).isPresent()) {
                            return ResponseEntity.badRequest()
                                    .body(Map.of("error", "User already exists: " + username));
                        }
                        userStore.create(username, password, new HashSet<>(roleList));
                        return ResponseEntity.ok(Map.of("created", username, "roles", roleList));
                    }

                    @PutMapping("/api/users/{username}")
                    public ResponseEntity<Map<String, Object>> updateUser(
                            @PathVariable("username") String username,
                            @RequestBody Map<String, Object> body) {
                        if (body.containsKey("active")) {
                            boolean active = Boolean.parseBoolean(body.get("active").toString());
                            userStore.setActive(username, active);
                        }
                        return ResponseEntity.ok(Map.of("updated", username));
                    }

                    @DeleteMapping("/api/users/{username}")
                    public ResponseEntity<Map<String, Object>> deleteUser(
                            @PathVariable("username") String username) {
                        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
                        if (auth != null && auth.getName().equals(username)) {
                            return ResponseEntity.badRequest()
                                    .body(Map.of("error", "Cannot delete your own account"));
                        }
                        boolean deleted = userStore.delete(username);
                        return deleted
                            ? ResponseEntity.ok(Map.of("deleted", username))
                            : ResponseEntity.notFound().build();
                    }

                    @PutMapping("/api/users/{username}/password")
                    public ResponseEntity<Map<String, Object>> changePassword(
                            @PathVariable("username") String username,
                            @RequestBody Map<String, Object> body) {
                        String newPassword = (String) body.get("newPassword");
                        if (newPassword == null || newPassword.isBlank()) {
                            return ResponseEntity.badRequest()
                                    .body(Map.of("error", "newPassword is required"));
                        }
                        boolean changed = userStore.changePassword(username, newPassword);
                        return changed
                            ? ResponseEntity.ok(Map.of("updated", username))
                            : ResponseEntity.notFound().build();
                    }

                    @PutMapping("/api/users/{username}/roles")
                    public ResponseEntity<Map<String, Object>> updateRoles(
                            @PathVariable("username") String username,
                            @RequestBody Map<String, Object> body) {
                        @SuppressWarnings("unchecked")
                        List<String> roleList = (List<String>) body.getOrDefault("roles", List.of());
                        boolean updated = userStore.updateRoles(username, new HashSet<>(roleList));
                        return updated
                            ? ResponseEntity.ok(Map.of("updated", username, "roles", roleList))
                            : ResponseEntity.notFound().build();
                    }

                    // ---- Settings ------------------------------------------------------------

                    @GetMapping("/api/settings")
                    public ResponseEntity<AdminSettings> getSettings() {
                        return ResponseEntity.ok(settingsStore.get());
                    }

                    @PutMapping("/api/settings")
                    public ResponseEntity<AdminSettings> updateSettings(
                            @RequestBody AdminSettings settings) {
                        settingsStore.update(settings);
                        return ResponseEntity.ok(settingsStore.get());
                    }

                    // ---- Profile -------------------------------------------------------------

                    @GetMapping("/api/auth/profile")
                    public ResponseEntity<Map<String, Object>> getProfile() {
                        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
                        if (auth == null) return ResponseEntity.ok(Map.of("authenticated", false));
                        return userStore.findByUsername(auth.getName()).map(u -> {
                            Map<String, Object> profile = new LinkedHashMap<>();
                            profile.put("username",    u.getUsername());
                            profile.put("roles",       u.getRoles());
                            profile.put("lastLoginAt", u.getLastLoginAt());
                            profile.put("active",      u.isActive());
                            return ResponseEntity.ok(profile);
                        }).orElse(ResponseEntity.ok(Map.of("username", auth.getName())));
                    }
                }
                """;
        Files.writeString(pkg.resolve("UserController.java"), content);
    }
}
