package com.fractalx.core.gateway;

import com.fractalx.core.model.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates unified API documentation
 */
public class ApiDocumentationGenerator {
    private static final Logger log = LoggerFactory.getLogger(ApiDocumentationGenerator.class);

    public void generateDocumentation(Path gatewayRoot,
                                      List<FractalModule> modules,
                                      List<RouteDefinition> routes) throws IOException {
        log.debug("Generating API documentation");

        // Generate simple API catalog only (remove OpenAPI/Swagger and Postman)
        generateApiCatalog(gatewayRoot, modules, routes);

        log.info("✓ Generated API documentation");
    }

    private void generateApiCatalog(Path gatewayRoot, List<FractalModule> modules,
                                    List<RouteDefinition> routes) throws IOException {
        Path docsDir = gatewayRoot.resolve("docs");
        Files.createDirectories(docsDir);

        StringBuilder catalog = new StringBuilder();
        catalog.append("# FractalX Generated Microservices API Catalog\n\n");
        catalog.append("## Overview\n\n");
        catalog.append("This catalog lists all services generated by FractalX framework.\n\n");

        catalog.append("## Services\n\n");
        for (FractalModule module : modules) {
            catalog.append(String.format("### %s\n\n", toDisplayName(module.getServiceName())));
            catalog.append(String.format("- **Service Name**: `%s`\n", module.getServiceName()));
            catalog.append(String.format("- **Port**: `%d`\n", module.getPort()));
            catalog.append(String.format("- **Direct URL**: `http://localhost:%d`\n", module.getPort()));
            catalog.append(String.format("- **Gateway URL**: `http://localhost:9999/api/%s`\n",
                    module.getServiceName().replace("-service", "")));

            catalog.append("\n---\n\n");
        }

        Path catalogPath = docsDir.resolve("API_CATALOG.md");
        Files.writeString(catalogPath, catalog.toString());
    }

    private String toDisplayName(String serviceName) {
        String[] words = serviceName.split("-");
        StringBuilder result = new StringBuilder();
        for (String word : words) {
            if (!word.isEmpty()) {
                result.append(Character.toUpperCase(word.charAt(0)))
                        .append(word.substring(1))
                        .append(" ");
            }
        }
        return result.toString().trim();
    }
}