package com.fractalx.core.gateway;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates the main application class for the gateway
 */
public class GatewayApplicationGenerator {
    private static final Logger log = LoggerFactory.getLogger(GatewayApplicationGenerator.class);

    public void generateApplicationClass(Path srcMainJava) throws IOException {
        log.debug("Generating gateway application class");

        // Create package directory
        String basePackage = "com.fractalx.gateway";
        Path packagePath = createPackagePath(srcMainJava, basePackage);

        String applicationContent = """
            package com.fractalx.gateway;
            
            import org.springframework.boot.SpringApplication;
            import org.springframework.boot.autoconfigure.SpringBootApplication;
            
            /**
             * FractalX API Gateway - Auto-generated by FractalX Framework
             */
            @SpringBootApplication
            public class FractalXGatewayApplication {
                
                public static void main(String[] args) {
                    SpringApplication.run(FractalXGatewayApplication.class, args);
                }
            }
            """;

        Path appPath = packagePath.resolve("FractalXGatewayApplication.java");
        Files.writeString(appPath, applicationContent);
        log.info("✓ Generated gateway application class");
    }

    private Path createPackagePath(Path srcMainJava, String packageName) throws IOException {
        String[] parts = packageName.split("\\.");
        Path packagePath = srcMainJava;
        for (String part : parts) {
            packagePath = packagePath.resolve(part);
        }
        Files.createDirectories(packagePath);
        return packagePath;
    }
}