package com.fractalx.core.generator.service;

import com.fractalx.core.generator.GenerationContext;
import com.fractalx.core.generator.ServiceFileGenerator;
import com.fractalx.core.model.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates Feign client interfaces for cross-service communication.
 *
 * <p>For each dependency declared on the module, this step looks up the target
 * module in {@link GenerationContext#getAllModules()} and generates a
 * {@code @FeignClient} interface along with request/response DTOs.
 */
public class FeignClientGenerator implements ServiceFileGenerator {

    private static final Logger log = LoggerFactory.getLogger(FeignClientGenerator.class);

    private static final String ORDER_SERVICE = "order-service";
    private static final String PAYMENT_SERVICE = "payment-service";

    @Override
    public void generate(GenerationContext context) throws IOException {
        FractalModule module = context.getModule();
        List<String> deps = module.getDependencies();

        if (deps == null || deps.isEmpty()) {
            log.debug("No dependencies for {} – skipping Feign client generation", module.getServiceName());
            return;
        }

        log.debug("Generating Feign clients for module: {}, dependencies: {}", module.getServiceName(), deps);

        if (ORDER_SERVICE.equals(module.getServiceName())) {
            generatePaymentFeignClient(context);
        }
    }

    private void generatePaymentFeignClient(GenerationContext context) throws IOException {
        FractalModule module = context.getModule();

        FractalModule paymentModule = context.getAllModules().stream()
                .filter(m -> PAYMENT_SERVICE.equals(m.getServiceName()))
                .findFirst()
                .orElse(null);

        if (paymentModule == null) {
            log.error("Payment service not found. Available modules: {}",
                    context.getAllModules().stream().map(FractalModule::getServiceName).toList());
            return;
        }

        Path packagePath = toPackagePath(context.getSrcMainJava(), module.getPackageName());
        Files.createDirectories(packagePath);

        Path clientPath = packagePath.resolve("PaymentClient.java");
        if (Files.exists(clientPath)) {
            Files.delete(clientPath);
        }

        Files.writeString(clientPath, buildFeignClientSource(module.getPackageName(), paymentModule.getPort()));
        Files.writeString(packagePath.resolve("PaymentRequest.java"),  buildRequestSource(module.getPackageName()));
        Files.writeString(packagePath.resolve("PaymentResponse.java"), buildResponseSource(module.getPackageName()));

        log.info("Generated PaymentClient Feign interface for {}", module.getServiceName());
    }

    private String buildFeignClientSource(String packageName, int paymentPort) {
        return """
                package %s;

                import org.springframework.cloud.openfeign.FeignClient;
                import org.springframework.web.bind.annotation.PostMapping;
                import org.springframework.web.bind.annotation.RequestBody;

                /**
                 * Feign client for Payment Service communication.
                 * Generated by FractalX Framework.
                 */
                @FeignClient(name = "payment-service", url = "http://localhost:%d")
                public interface PaymentClient {

                    @PostMapping("/api/payments/process")
                    PaymentResponse processPayment(@RequestBody PaymentRequest request);

                    /** Convenience overload for backward compatibility with the monolith signature. */
                    default boolean processPayment(String customerId, Double amount) {
                        PaymentResponse response = processPayment(new PaymentRequest(customerId, amount));
                        return response.success();
                    }
                }
                """.formatted(packageName, paymentPort);
    }

    private String buildRequestSource(String packageName) {
        return """
                package %s;

                /** Payment request DTO. Generated by FractalX Framework. */
                public record PaymentRequest(String customerId, Double amount) {}
                """.formatted(packageName);
    }

    private String buildResponseSource(String packageName) {
        return """
                package %s;

                /** Payment response DTO. Generated by FractalX Framework. */
                public record PaymentResponse(boolean success, String message) {}
                """.formatted(packageName);
    }

    private Path toPackagePath(Path root, String packageName) {
        Path path = root;
        for (String part : packageName.split("\\.")) {
            path = path.resolve(part);
        }
        return path;
    }
}
