package org.fractalx.core.generator.transformation;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.ConstructorDeclaration;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.expr.ObjectCreationExpr;
import com.github.javaparser.ast.expr.VariableDeclarationExpr;
import com.github.javaparser.ast.stmt.BlockStmt;
import com.github.javaparser.ast.stmt.ExpressionStmt;
import com.github.javaparser.ast.stmt.Statement;
import org.fractalx.core.generator.GenerationContext;
import org.fractalx.core.generator.ServiceFileGenerator;
import org.fractalx.core.model.MethodParam;
import org.fractalx.core.model.SagaDefinition;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Transforms the body of {@code @DistributedSaga}-annotated methods in generated service files.
 *
 * <p>For each saga owned by this service module, this step:
 * <ol>
 *   <li>Locates the owner class Java file in the generated service source tree.</li>
 *   <li>Removes all cross-service calls (calls on {@code *Client} fields) from the method body.
 *       These are now orchestrated by the saga orchestrator — not executed inline.</li>
 *   <li>Injects an {@code outboxPublisher.publish(...)} call carrying the saga ID and all
 *       method parameters as JSON payload. The orchestrator receives this and executes
 *       the steps in order, with compensation on failure.</li>
 *   <li>Adds {@code OutboxPublisher} as a constructor-injected field.</li>
 * </ol>
 *
 * <p>Must run <em>after</em> {@link NetScopeClientWiringStep} so that cross-service fields
 * are already renamed to {@code *Client} (e.g., {@code paymentServiceClient}).
 *
 * <p>Auto-generated by FractalX.
 */
public class SagaMethodTransformer implements ServiceFileGenerator {

    private static final Logger log = LoggerFactory.getLogger(SagaMethodTransformer.class);

    private final JavaParser javaParser = new JavaParser();

    @Override
    public void generate(GenerationContext context) throws IOException {
        List<SagaDefinition> ownedSagas = context.getSagaDefinitions().stream()
                .filter(s -> s.getOwnerServiceName().equals(context.getModule().getServiceName()))
                .toList();

        if (ownedSagas.isEmpty()) return;

        Path srcMainJava = context.getServiceRoot().resolve("src/main/java");
        String outboxPackage = "org.fractalx.generated."
                + context.getModule().getServiceName().replace("-", "") + ".outbox";

        for (SagaDefinition saga : ownedSagas) {
            Path javaFile = findClassFile(srcMainJava, saga.getOwnerClassName());
            if (javaFile == null) {
                log.warn("SagaMethodTransformer: could not find {}.java for saga '{}'",
                        saga.getOwnerClassName(), saga.getSagaId());
                continue;
            }
            transformFile(javaFile, saga, outboxPackage);
        }
    }

    // -------------------------------------------------------------------------
    // Core transformation
    // -------------------------------------------------------------------------

    private void transformFile(Path javaFile, SagaDefinition saga, String outboxPackage)
            throws IOException {

        CompilationUnit cu = javaParser.parse(javaFile).getResult().orElse(null);
        if (cu == null) {
            log.warn("SagaMethodTransformer: failed to parse {}", javaFile);
            return;
        }

        ClassOrInterfaceDeclaration cls = cu.findAll(ClassOrInterfaceDeclaration.class)
                .stream()
                .filter(c -> c.getNameAsString().equals(saga.getOwnerClassName()))
                .findFirst()
                .orElse(null);

        if (cls == null) return;

        Optional<MethodDeclaration> methodOpt = cls.getMethods().stream()
                .filter(m -> m.getNameAsString().equals(saga.getMethodName()))
                .findFirst();

        if (methodOpt.isEmpty()) {
            log.warn("SagaMethodTransformer: method {}.{} not found",
                    saga.getOwnerClassName(), saga.getMethodName());
            return;
        }

        MethodDeclaration method = methodOpt.get();
        BlockStmt body = method.getBody().orElse(null);
        if (body == null) return;

        // Client field names derived from saga steps (after NetScopeClientWiringStep)
        Set<String> clientFields = saga.getSteps().stream()
                .map(step -> Character.toLowerCase(step.getBeanType().charAt(0))
                           + step.getBeanType().substring(1) + "Client")
                .collect(Collectors.toSet());

        // Find where the first cross-service call sits so we insert publish() there
        int insertIndex = findFirstClientCallIndex(body, clientFields);

        // Collect variable names that were bound to cross-service call return values
        // e.g. "Payment payment = paymentServiceClient.processPayment(...)"
        Set<String> removedVarNames = collectRemovedVarNames(body, clientFields);

        // Remove all cross-service call statements (both void calls AND variable declarations)
        List<Statement> toRemove = body.getStatements().stream()
                .filter(stmt -> isClientCall(stmt, clientFields))
                .toList();
        toRemove.forEach(body::remove);

        // Remove any remaining statements that reference the now-undefined variable names
        // e.g. "order.setPayment(payment)" or "item.setUnitPrice(product.getPrice())"
        // Also detect cascade-tainted locals: local vars (new XYZ()) whose required setters
        // were removed — those vars are now incomplete and must be removed entirely.
        if (!removedVarNames.isEmpty()) {
            List<Statement> dependentStmts = body.getStatements().stream()
                    .filter(stmt -> referencesAnyVar(stmt, removedVarNames))
                    .toList();

            // Cascade taint: find locally-created vars that had setters removed
            Set<String> cascadedVars = findCascadedTaintedLocals(
                    body, dependentStmts, method.getTypeAsString());

            dependentStmts.forEach(body::remove);

            // Remove everything referencing the cascade-tainted vars (decl + remaining setters + adds)
            if (!cascadedVars.isEmpty()) {
                body.getStatements().stream()
                        .filter(stmt -> referencesAnyVar(stmt, cascadedVars)
                                     || isDeclaredVar(stmt, cascadedVars))
                        .toList()
                        .forEach(body::remove);
            }
        }

        // Build the publish() call as a code block and insert at the right position.
        // If the saga has extra local vars (e.g. orderId = draftOrder.getId()), the publish
        // must come AFTER those vars are declared in the remaining body.
        String publishBlock = buildPublishBlock(saga);
        List<Statement> publishStmts = parseStatements(publishBlock);

        Set<String> extraVarNames = saga.getExtraLocalVars().stream()
                .map(MethodParam::getName).collect(Collectors.toSet());
        int finalInsertIndex;
        if (!extraVarNames.isEmpty()) {
            finalInsertIndex = findPositionAfterLocalVars(body, extraVarNames);
        } else {
            finalInsertIndex = insertIndex;
        }

        if (finalInsertIndex < 0 || finalInsertIndex >= body.getStatements().size()) {
            publishStmts.forEach(body::addStatement);
        } else {
            for (int i = publishStmts.size() - 1; i >= 0; i--) {
                body.addStatement(finalInsertIndex, publishStmts.get(i));
            }
        }

        // Add OutboxPublisher field + constructor injection (idempotent)
        if (!hasField(cls, "outboxPublisher")) {
            addOutboxPublisherField(cls, outboxPackage, cu);
        }

        Files.writeString(javaFile, cu.toString());
        log.info("Transformed saga method {}.{} for saga '{}'",
                saga.getOwnerClassName(), saga.getMethodName(), saga.getSagaId());
    }

    // -------------------------------------------------------------------------
    // Publish block builder
    // -------------------------------------------------------------------------

    private String buildPublishBlock(SagaDefinition saga) {
        List<MethodParam> params = saga.getSagaMethodParams();
        List<MethodParam> extraVars = saga.getExtraLocalVars();
        StringBuilder sb = new StringBuilder();

        sb.append("// Saga steps delegated to orchestrator via transactional outbox\n");
        sb.append("java.util.Map<String, Object> sagaPayload = new java.util.LinkedHashMap<>();\n");
        for (MethodParam p : params) {
            sb.append("sagaPayload.put(\"").append(p.getName()).append("\", ")
              .append(p.getName()).append(");\n");
        }
        // Include extra local vars (e.g. orderId) so orchestrator can forward them to step clients
        for (MethodParam extra : extraVars) {
            sb.append("sagaPayload.put(\"").append(extra.getName()).append("\", ")
              .append(extra.getName()).append(");\n");
        }

        String aggregateId;
        if (!params.isEmpty()) {
            aggregateId = "String.valueOf(" + params.get(0).getName() + ")";
        } else {
            aggregateId = "java.util.UUID.randomUUID().toString()";
        }

        sb.append("outboxPublisher.publish(\"").append(saga.getSagaId()).append("\", ")
          .append(aggregateId).append(", sagaPayload);\n");

        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // Field + constructor injection
    // -------------------------------------------------------------------------

    private void addOutboxPublisherField(ClassOrInterfaceDeclaration cls,
                                         String outboxPackage, CompilationUnit cu) {
        // Add import
        cu.addImport(outboxPackage + ".OutboxPublisher");

        // Add field before the first existing field (or at top of class)
        FieldDeclaration field = cls.addField("OutboxPublisher", "outboxPublisher",
                com.github.javaparser.ast.Modifier.Keyword.PRIVATE,
                com.github.javaparser.ast.Modifier.Keyword.FINAL);

        // Find the constructor and inject the parameter + assignment
        List<ConstructorDeclaration> constructors = cls.getConstructors();
        if (constructors.isEmpty()) return;

        // Use the constructor with the most parameters (main constructor)
        ConstructorDeclaration ctor = constructors.stream()
                .max((a, b) -> Integer.compare(a.getParameters().size(), b.getParameters().size()))
                .get();

        // Add parameter
        ctor.addParameter("OutboxPublisher", "outboxPublisher");

        // Add assignment at the end of constructor body
        ctor.getBody().addStatement("this.outboxPublisher = outboxPublisher;");
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private Path findClassFile(Path srcMainJava, String className) throws IOException {
        try (Stream<Path> paths = Files.walk(srcMainJava)) {
            return paths
                    .filter(p -> p.getFileName().toString().equals(className + ".java"))
                    .findFirst()
                    .orElse(null);
        }
    }

    private boolean isClientCall(Statement stmt, Set<String> clientFields) {
        if (!(stmt instanceof ExpressionStmt exprStmt)) return false;
        // Matches both:
        //   paymentServiceClient.processPayment(...)            — void call
        //   Payment payment = paymentServiceClient.process(...) — variable declaration
        return exprStmt.findAll(MethodCallExpr.class).stream()
                .anyMatch(call -> call.getScope()
                        .map(s -> clientFields.contains(s.toString()))
                        .orElse(false));
    }

    /** Collects local variable names whose initializers are cross-service calls. */
    private Set<String> collectRemovedVarNames(BlockStmt body, Set<String> clientFields) {
        Set<String> names = new HashSet<>();
        for (Statement stmt : body.getStatements()) {
            if (!(stmt instanceof ExpressionStmt exprStmt)) continue;
            if (!(exprStmt.getExpression() instanceof VariableDeclarationExpr vde)) continue;
            boolean hasClientCall = vde.findAll(MethodCallExpr.class).stream()
                    .anyMatch(call -> call.getScope()
                            .map(s -> clientFields.contains(s.toString()))
                            .orElse(false));
            if (hasClientCall) {
                vde.getVariables().forEach(v -> names.add(v.getNameAsString()));
            }
        }
        return names;
    }

    /** Returns true if any NameExpr in the statement matches one of the removed variable names. */
    private boolean referencesAnyVar(Statement stmt, Set<String> varNames) {
        return stmt.findAll(NameExpr.class).stream()
                .anyMatch(n -> varNames.contains(n.getNameAsString()));
    }

    /** Returns true if the statement declares one of the given variable names. */
    private boolean isDeclaredVar(Statement stmt, Set<String> varNames) {
        if (!(stmt instanceof ExpressionStmt exprStmt)) return false;
        if (!(exprStmt.getExpression() instanceof VariableDeclarationExpr vde)) return false;
        return vde.getVariables().stream()
                .anyMatch(v -> varNames.contains(v.getNameAsString()));
    }

    private int findFirstClientCallIndex(BlockStmt body, Set<String> clientFields) {
        List<Statement> stmts = body.getStatements();
        for (int i = 0; i < stmts.size(); i++) {
            if (isClientCall(stmts.get(i), clientFields)) return i;
        }
        return -1;
    }

    /**
     * Returns the index immediately AFTER the last declaration of any of the given variable names.
     * Used to insert the publish block after extra local vars (e.g., orderId) are assigned.
     * Returns -1 if none of the vars are declared in the body (caller falls back to addStatement).
     */
    private int findPositionAfterLocalVars(BlockStmt body, Set<String> varNames) {
        List<Statement> stmts = body.getStatements();
        int lastIdx = -1;
        for (int i = 0; i < stmts.size(); i++) {
            Statement stmt = stmts.get(i);
            if (!(stmt instanceof ExpressionStmt exprStmt)) continue;
            if (!(exprStmt.getExpression() instanceof VariableDeclarationExpr vde)) continue;
            boolean declaresTargetVar = vde.getVariables().stream()
                    .anyMatch(v -> varNames.contains(v.getNameAsString()));
            if (declaresTargetVar) lastIdx = i;
        }
        return lastIdx < 0 ? -1 : lastIdx + 1;
    }

    private boolean hasField(ClassOrInterfaceDeclaration cls, String fieldName) {
        return cls.getFields().stream()
                .anyMatch(f -> f.getVariables().stream()
                        .anyMatch(v -> v.getNameAsString().equals(fieldName)));
    }

    /**
     * Finds locally-created variables (via {@code new XYZ()}) that had required setters removed
     * (i.e., one of the {@code removedStmts} was a method call on that variable).
     *
     * <p>These variables are now partially initialised — missing a NOT NULL field that
     * was previously populated from a cross-service call result. Persisting them would cause
     * {@code DataIntegrityViolationException}. We cascade-taint them so the caller can
     * remove the entire var block.
     *
     * <p>Variables whose type matches the method's declared return type are intentionally
     * excluded — they are the primary aggregate being returned and must remain.
     */
    private Set<String> findCascadedTaintedLocals(BlockStmt body,
                                                   List<Statement> removedStmts,
                                                   String methodReturnType) {
        // Collect receiver names from removed statements: "item.setUnitPrice(...)" → "item"
        Set<String> removedReceivers = new HashSet<>();
        for (Statement stmt : removedStmts) {
            stmt.findAll(MethodCallExpr.class).stream()
                    .filter(call -> call.getScope().isPresent())
                    .forEach(call -> {
                        String scope = call.getScope().get().toString();
                        if (!scope.contains(".")) {  // plain variable name, not a chain
                            removedReceivers.add(scope);
                        }
                    });
        }
        if (removedReceivers.isEmpty()) return Set.of();

        Set<String> tainted = new HashSet<>();
        for (Statement stmt : body.getStatements()) {
            if (!(stmt instanceof ExpressionStmt exprStmt)) continue;
            if (!(exprStmt.getExpression() instanceof VariableDeclarationExpr vde)) continue;
            boolean isLocallyCreated = vde.getVariables().stream()
                    .anyMatch(v -> v.getInitializer()
                            .map(init -> init instanceof ObjectCreationExpr)
                            .orElse(false));
            if (!isLocallyCreated) continue;

            String varType = vde.getElementType().asString();
            vde.getVariables().forEach(v -> {
                String varName = v.getNameAsString();
                if (removedReceivers.contains(varName) && !varType.equals(methodReturnType)) {
                    tainted.add(varName);
                    log.debug("SagaMethodTransformer: cascade-taint '{}' ({}) — setter was removed",
                            varName, varType);
                }
            });
        }
        return tainted;
    }

    /**
     * Parses a block of Java statements by wrapping them in a dummy method, then extracts the statements.
     */
    private List<Statement> parseStatements(String code) {
        String wrapped = "class X { void m() {\n" + code + "\n} }";
        try {
            CompilationUnit cu = javaParser.parse(wrapped).getResult().orElse(null);
            if (cu == null) return List.of();
            return cu.findAll(MethodDeclaration.class).stream()
                    .findFirst()
                    .flatMap(MethodDeclaration::getBody)
                    .map(b -> new ArrayList<>(b.getStatements()))
                    .orElse(new ArrayList<>());
        } catch (Exception e) {
            log.warn("SagaMethodTransformer: failed to parse publish block: {}", e.getMessage());
            return List.of();
        }
    }
}
