package org.fractalx.core.generator.transformation;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.ConstructorDeclaration;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.expr.ObjectCreationExpr;
import com.github.javaparser.ast.expr.VariableDeclarationExpr;
import com.github.javaparser.ast.stmt.BlockStmt;
import com.github.javaparser.ast.stmt.ExpressionStmt;
import com.github.javaparser.ast.stmt.Statement;
import org.fractalx.core.generator.GenerationContext;
import org.fractalx.core.generator.ServiceFileGenerator;
import org.fractalx.core.model.MethodParam;
import org.fractalx.core.model.SagaDefinition;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Transforms the body of {@code @DistributedSaga}-annotated methods in generated service files.
 *
 * <p>For each saga owned by this service module, this step:
 * <ol>
 *   <li>Locates the owner class Java file in the generated service source tree.</li>
 *   <li>Removes all cross-service calls (calls on {@code *Client} fields) from the method body.
 *       These are now orchestrated by the saga orchestrator — not executed inline.</li>
 *   <li>Injects an {@code outboxPublisher.publish(...)} call carrying the saga ID and all
 *       method parameters as JSON payload. The orchestrator receives this and executes
 *       the steps in order, with compensation on failure.</li>
 *   <li>Adds {@code OutboxPublisher} as a constructor-injected field.</li>
 * </ol>
 *
 * <p>Must run <em>after</em> {@link NetScopeClientWiringStep} so that cross-service fields
 * are already renamed to {@code *Client} (e.g., {@code paymentServiceClient}).
 *
 * <p>Auto-generated by FractalX.
 */
public class SagaMethodTransformer implements ServiceFileGenerator {

    private static final Logger log = LoggerFactory.getLogger(SagaMethodTransformer.class);

    private final JavaParser javaParser = new JavaParser();

    @Override
    public void generate(GenerationContext context) throws IOException {
        List<SagaDefinition> ownedSagas = context.getSagaDefinitions().stream()
                .filter(s -> s.getOwnerServiceName().equals(context.getModule().getServiceName()))
                .toList();

        if (ownedSagas.isEmpty()) return;

        Path srcMainJava = context.getServiceRoot().resolve("src/main/java");
        String basePackage = context.servicePackage();
        String outboxPackage = basePackage + ".outbox";

        for (SagaDefinition saga : ownedSagas) {
            Path javaFile = findClassFile(srcMainJava, saga.getOwnerClassName());
            if (javaFile == null) {
                log.warn("SagaMethodTransformer: could not find {}.java for saga '{}'",
                        saga.getOwnerClassName(), saga.getSagaId());
                continue;
            }
            transformFile(javaFile, saga, outboxPackage);
        }

        // Generate a SagaCompletionController for each owned saga so the saga orchestrator
        // can call POST /internal/saga-complete/{correlationId} after all steps complete.
        generateSagaCompletionController(srcMainJava, basePackage, ownedSagas,
                context.getModule().getServiceName(), context.getModule().getPackageName());
    }

    /**
     * Generates {@code SagaCompletionController} — REST endpoints that the saga orchestrator
     * calls after saga completion or failure.
     *
     * <p>Injects the owner service's aggregate repository (derived from the owner class name,
     * e.g. {@code OrderService} → {@code OrderRepository}) to implement the actual
     * CONFIRMED / CANCELLED state transitions without requiring manual TODO implementation.
     *
     * @param modulePackage original package of the owner service's source classes
     *                      (used to derive the repository FQN)
     */
    private void generateSagaCompletionController(Path srcMainJava, String basePackage,
                                                   List<SagaDefinition> sagas,
                                                   String serviceName,
                                                   String modulePackage) throws IOException {
        // Build a summary of all sagas this service owns
        StringBuilder sagaList = new StringBuilder();
        for (SagaDefinition saga : sagas) {
            sagaList.append(" *   <li>{@code ").append(saga.getSagaId()).append("} — ")
                    .append(saga.getMethodName()).append("()</li>\n");
        }

        // Derive the aggregate repository from the first saga's owner class name.
        // Heuristic: "OrderService" → aggregate "Order" → repository "OrderRepository"
        //            "OrderModule"  → aggregate "Order" → repository "OrderRepository"
        String ownerClass = sagas.get(0).getOwnerClassName(); // e.g. "OrderService" or "OrderModule"
        String aggregateName = ownerClass.endsWith("Service")
                ? ownerClass.substring(0, ownerClass.length() - "Service".length())
                : ownerClass.endsWith("Module")
                    ? ownerClass.substring(0, ownerClass.length() - "Module".length())
                    : ownerClass;
        String repositoryType = aggregateName + "Repository"; // e.g. "OrderRepository"
        String repositoryFqn  = modulePackage + "." + repositoryType;
        String repoField      = Character.toLowerCase(repositoryType.charAt(0)) + repositoryType.substring(1);

        // Look for the aggregate ID field name in any saga's params or extra local vars.
        // e.g. "orderId" in place-order-saga's extraLocalVars.
        String idFieldName = aggregateName.toLowerCase() + "Id"; // e.g. "orderId"
        boolean hasIdField = sagas.stream().anyMatch(s ->
                s.getSagaMethodParams().stream().anyMatch(p -> p.getName().equals(idFieldName))
                || s.getExtraLocalVars().stream().anyMatch(p -> p.getName().equals(idFieldName)));

        String pkg = basePackage + ".saga";
        Path pkgPath = srcMainJava;
        for (String part : pkg.split("\\.")) pkgPath = pkgPath.resolve(part);
        Files.createDirectories(pkgPath);

        // Build the CONFIRMED update block
        String confirmBlock;
        String cancelBlock;
        if (hasIdField) {
            confirmBlock =
                  "            Object idRaw = sagaData.get(\"" + idFieldName + "\");\n"
                + "            if (idRaw != null) {\n"
                + "                Long id = ((Number) idRaw).longValue();\n"
                + "                " + repoField + ".findById(id).ifPresentOrElse(entity -> {\n"
                + "                    entity.setStatus(\"CONFIRMED\");\n"
                + "                    " + repoField + ".save(entity);\n"
                + "                    log.info(\"" + aggregateName + " {} marked CONFIRMED (saga correlationId={})\", id, cid);\n"
                + "                }, () -> log.warn(\"onSagaComplete: " + aggregateName.toLowerCase() + " {} not found\", id));\n"
                + "            }\n";
            cancelBlock =
                  "            Object idRaw = errorData.get(\"" + idFieldName + "\");\n"
                + "            if (idRaw != null) {\n"
                + "                Long id = ((Number) idRaw).longValue();\n"
                + "                " + repoField + ".findById(id).ifPresentOrElse(entity -> {\n"
                + "                    entity.setStatus(\"CANCELLED\");\n"
                + "                    " + repoField + ".save(entity);\n"
                + "                    log.warn(\"" + aggregateName + " {} marked CANCELLED — saga failed: {} (correlationId={})\", id, errorMessage, cid);\n"
                + "                }, () -> log.warn(\"onSagaFailed: " + aggregateName.toLowerCase() + " {} not found\", id));\n"
                + "            }\n";
        } else {
            confirmBlock = "            // TODO: finalize business state (e.g., mark " + aggregateName + " as CONFIRMED)\n";
            cancelBlock  = "            // TODO: revert business state (e.g., mark " + aggregateName + " as CANCELLED)\n";
        }

        // Only inject the repository when we have an ID field to look up.
        // When hasIdField == false the body is TODO stubs — importing a repository that
        // may not even exist would cause a compile error.
        String repoImport    = hasIdField ? "import " + repositoryFqn + ";\n" : "";
        String repoFieldDecl = hasIdField
                ? "    private final " + repositoryType + " " + repoField + ";\n\n"
                : "";
        String repoCtorParam  = hasIdField ? ", " + repositoryType + " " + repoField : "";
        String repoCtorAssign = hasIdField ? "        this." + repoField + " = " + repoField + ";\n" : "";

        String content = "package " + pkg + ";\n\n"
                + repoImport
                + "import com.fasterxml.jackson.core.type.TypeReference;\n"
                + "import com.fasterxml.jackson.databind.ObjectMapper;\n"
                + "import org.slf4j.Logger;\n"
                + "import org.slf4j.LoggerFactory;\n"
                + "import org.slf4j.MDC;\n"
                + "import org.springframework.http.ResponseEntity;\n"
                + "import org.springframework.transaction.annotation.Transactional;\n"
                + "import org.springframework.web.bind.annotation.*;\n\n"
                + "import java.util.Map;\n\n"
                + "/**\n"
                + " * Receives saga-completion callbacks from the FractalX Saga Orchestrator.\n"
                + " * Marks the aggregate as CONFIRMED on success, CANCELLED on failure.\n"
                + " *\n"
                + " * <p>Sagas managed for " + serviceName + ":\n"
                + " * <ul>\n"
                + sagaList
                + " * </ul>\n"
                + " *\n"
                + " * Auto-generated by FractalX.\n"
                + " */\n"
                + "@RestController\n"
                + "@RequestMapping(\"/internal\")\n"
                + "public class SagaCompletionController {\n\n"
                + "    private static final Logger log = LoggerFactory.getLogger(SagaCompletionController.class);\n\n"
                + "    private final ObjectMapper objectMapper;\n"
                + repoFieldDecl
                + "    public SagaCompletionController(ObjectMapper objectMapper"
                + repoCtorParam + ") {\n"
                + "        this.objectMapper = objectMapper;\n"
                + repoCtorAssign
                + "    }\n\n"
                + "    @PostMapping(\"/saga-complete/{correlationId}\")\n"
                + "    @Transactional\n"
                + "    public ResponseEntity<Void> onSagaComplete(\n"
                + "            @PathVariable(\"correlationId\") String correlationId,\n"
                + "            @RequestHeader(value = \"X-Correlation-Id\", required = false) String headerCorrelationId,\n"
                + "            @RequestBody String payload) {\n\n"
                + "        String cid = (headerCorrelationId != null && !headerCorrelationId.isBlank())\n"
                + "                ? headerCorrelationId : correlationId;\n"
                + "        MDC.put(\"correlationId\", cid);\n"
                + "        try {\n"
                + "            Map<String, Object> sagaData = objectMapper.readValue(\n"
                + "                    payload, new TypeReference<Map<String, Object>>() {});\n"
                + "            log.info(\"Saga completed — correlationId={} payload={}\", cid, sagaData);\n"
                + confirmBlock
                + "            return ResponseEntity.ok().build();\n"
                + "        } catch (Exception e) {\n"
                + "            log.error(\"Failed to process saga completion: correlationId={}\", cid, e);\n"
                + "            return ResponseEntity.internalServerError().build();\n"
                + "        } finally {\n"
                + "            MDC.remove(\"correlationId\");\n"
                + "        }\n"
                + "    }\n\n"
                + "    @PostMapping(\"/saga-failed/{correlationId}\")\n"
                + "    @Transactional\n"
                + "    public ResponseEntity<Void> onSagaFailed(\n"
                + "            @PathVariable(\"correlationId\") String correlationId,\n"
                + "            @RequestHeader(value = \"X-Correlation-Id\", required = false) String headerCorrelationId,\n"
                + "            @RequestBody String payload) {\n\n"
                + "        String cid = (headerCorrelationId != null && !headerCorrelationId.isBlank())\n"
                + "                ? headerCorrelationId : correlationId;\n"
                + "        MDC.put(\"correlationId\", cid);\n"
                + "        try {\n"
                + "            Map<String, Object> errorData = objectMapper.readValue(\n"
                + "                    payload, new TypeReference<Map<String, Object>>() {});\n"
                + "            String errorMessage = (String) errorData.getOrDefault(\"errorMessage\", \"unknown\");\n"
                + "            log.warn(\"Saga FAILED — correlationId={} error={}\", cid, errorMessage);\n"
                + cancelBlock
                + "            return ResponseEntity.ok().build();\n"
                + "        } catch (Exception e) {\n"
                + "            log.error(\"Failed to process saga failure notification: correlationId={}\", cid, e);\n"
                + "            return ResponseEntity.internalServerError().build();\n"
                + "        } finally {\n"
                + "            MDC.remove(\"correlationId\");\n"
                + "        }\n"
                + "    }\n"
                + "}\n";

        Path file = pkgPath.resolve("SagaCompletionController.java");
        if (!Files.exists(file)) {
            Files.writeString(file, content);
            log.info("SagaMethodTransformer: generated SagaCompletionController for {}", serviceName);
        }
    }

    // -------------------------------------------------------------------------
    // Core transformation
    // -------------------------------------------------------------------------

    private void transformFile(Path javaFile, SagaDefinition saga, String outboxPackage)
            throws IOException {

        CompilationUnit cu = javaParser.parse(javaFile).getResult().orElse(null);
        if (cu == null) {
            log.warn("SagaMethodTransformer: failed to parse {}", javaFile);
            return;
        }

        ClassOrInterfaceDeclaration cls = cu.findAll(ClassOrInterfaceDeclaration.class)
                .stream()
                .filter(c -> c.getNameAsString().equals(saga.getOwnerClassName()))
                .findFirst()
                .orElse(null);

        if (cls == null) return;

        Optional<MethodDeclaration> methodOpt = cls.getMethods().stream()
                .filter(m -> m.getNameAsString().equals(saga.getMethodName()))
                .findFirst();

        if (methodOpt.isEmpty()) {
            log.warn("SagaMethodTransformer: method {}.{} not found",
                    saga.getOwnerClassName(), saga.getMethodName());
            return;
        }

        MethodDeclaration method = methodOpt.get();
        BlockStmt body = method.getBody().orElse(null);
        if (body == null) return;

        // Client field names derived from saga steps (after NetScopeClientWiringStep)
        Set<String> clientFields = saga.getSteps().stream()
                .map(step -> Character.toLowerCase(step.getBeanType().charAt(0))
                           + step.getBeanType().substring(1) + "Client")
                .collect(Collectors.toSet());

        // Find where the first cross-service call sits so we insert publish() there
        int insertIndex = findFirstClientCallIndex(body, clientFields);

        // Collect variable names that were bound to cross-service call return values
        // e.g. "Payment payment = paymentServiceClient.processPayment(...)"
        Set<String> removedVarNames = collectRemovedVarNames(body, clientFields);

        // Remove all cross-service call statements (both void calls AND variable declarations)
        List<Statement> toRemove = body.getStatements().stream()
                .filter(stmt -> isClientCall(stmt, clientFields))
                .toList();
        toRemove.forEach(body::remove);

        // Remove any remaining statements that reference the now-undefined variable names
        // e.g. "order.setPayment(payment)" or "item.setUnitPrice(product.getPrice())"
        // Also detect cascade-tainted locals: local vars (new XYZ()) whose required setters
        // were removed — those vars are now incomplete and must be removed entirely.
        if (!removedVarNames.isEmpty()) {
            List<Statement> dependentStmts = body.getStatements().stream()
                    .filter(stmt -> referencesAnyVar(stmt, removedVarNames))
                    .toList();

            // Cascade taint: find locally-created vars that had setters removed
            Set<String> cascadedVars = findCascadedTaintedLocals(
                    body, dependentStmts, method.getTypeAsString());

            dependentStmts.forEach(body::remove);

            // Remove everything referencing the cascade-tainted vars (decl + remaining setters + adds)
            if (!cascadedVars.isEmpty()) {
                body.getStatements().stream()
                        .filter(stmt -> referencesAnyVar(stmt, cascadedVars)
                                     || isDeclaredVar(stmt, cascadedVars))
                        .toList()
                        .forEach(body::remove);
            }
        }

        // Build the publish() call as a code block and insert at the right position.
        // If the saga has extra local vars (e.g. orderId = draftOrder.getId()), the publish
        // must come AFTER those vars are declared in the remaining body.
        String publishBlock = buildPublishBlock(saga);
        List<Statement> publishStmts = parseStatements(publishBlock);

        Set<String> extraVarNames = saga.getExtraLocalVars().stream()
                .map(MethodParam::getName).collect(Collectors.toSet());
        int finalInsertIndex;
        if (!extraVarNames.isEmpty()) {
            finalInsertIndex = findPositionAfterLocalVars(body, extraVarNames);
        } else {
            finalInsertIndex = insertIndex;
        }

        if (finalInsertIndex < 0 || finalInsertIndex >= body.getStatements().size()) {
            publishStmts.forEach(body::addStatement);
        } else {
            for (int i = publishStmts.size() - 1; i >= 0; i--) {
                body.addStatement(finalInsertIndex, publishStmts.get(i));
            }
        }

        // Remove orphaned statements that appear after the publish block
        // (e.g., setStatus("CONFIRMED"), second save(), premature state mutations)
        // and fix return-statement references to removed cross-service variables.
        stripOrphanStatementsAfterPublish(body, publishStmts.size(), removedVarNames,
                method.getTypeAsString());

        // Add OutboxPublisher field + constructor injection (idempotent)
        if (!hasField(cls, "outboxPublisher")) {
            addOutboxPublisherField(cls, outboxPackage, cu);
        }

        Files.writeString(javaFile, cu.toString());
        log.info("Transformed saga method {}.{} for saga '{}'",
                saga.getOwnerClassName(), saga.getMethodName(), saga.getSagaId());
    }

    // -------------------------------------------------------------------------
    // Publish block builder
    // -------------------------------------------------------------------------

    private String buildPublishBlock(SagaDefinition saga) {
        List<MethodParam> params = saga.getSagaMethodParams();
        List<MethodParam> extraVars = saga.getExtraLocalVars();
        StringBuilder sb = new StringBuilder();

        sb.append("// Saga steps delegated to orchestrator via transactional outbox\n");
        sb.append("java.util.Map<String, Object> sagaPayload = new java.util.LinkedHashMap<>();\n");
        for (MethodParam p : params) {
            sb.append("sagaPayload.put(\"").append(p.getName()).append("\", ")
              .append(p.getName()).append(");\n");
        }
        // Include extra local vars (e.g. orderId) so orchestrator can forward them to step clients
        for (MethodParam extra : extraVars) {
            sb.append("sagaPayload.put(\"").append(extra.getName()).append("\", ")
              .append(extra.getName()).append(");\n");
        }

        String aggregateId;
        if (!params.isEmpty()) {
            aggregateId = "String.valueOf(" + params.get(0).getName() + ")";
        } else {
            aggregateId = "java.util.UUID.randomUUID().toString()";
        }

        sb.append("outboxPublisher.publish(\"").append(saga.getSagaId()).append("\", ")
          .append(aggregateId).append(", sagaPayload);\n");

        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // Field + constructor injection
    // -------------------------------------------------------------------------

    private void addOutboxPublisherField(ClassOrInterfaceDeclaration cls,
                                         String outboxPackage, CompilationUnit cu) {
        // Add import
        cu.addImport(outboxPackage + ".OutboxPublisher");

        // Add field before the first existing field (or at top of class)
        FieldDeclaration field = cls.addField("OutboxPublisher", "outboxPublisher",
                com.github.javaparser.ast.Modifier.Keyword.PRIVATE,
                com.github.javaparser.ast.Modifier.Keyword.FINAL);

        // Find the constructor and inject the parameter + assignment
        List<ConstructorDeclaration> constructors = cls.getConstructors();
        if (constructors.isEmpty()) return;

        // Use the constructor with the most parameters (main constructor)
        ConstructorDeclaration ctor = constructors.stream()
                .max((a, b) -> Integer.compare(a.getParameters().size(), b.getParameters().size()))
                .get();

        // Add parameter
        ctor.addParameter("OutboxPublisher", "outboxPublisher");

        // Add assignment at the end of constructor body
        ctor.getBody().addStatement("this.outboxPublisher = outboxPublisher;");
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private Path findClassFile(Path srcMainJava, String className) throws IOException {
        try (Stream<Path> paths = Files.walk(srcMainJava)) {
            return paths
                    .filter(p -> p.getFileName().toString().equals(className + ".java"))
                    .findFirst()
                    .orElse(null);
        }
    }

    private boolean isClientCall(Statement stmt, Set<String> clientFields) {
        if (!(stmt instanceof ExpressionStmt exprStmt)) return false;
        // Matches both:
        //   paymentServiceClient.processPayment(...)            — void call
        //   Payment payment = paymentServiceClient.process(...) — variable declaration
        return exprStmt.findAll(MethodCallExpr.class).stream()
                .anyMatch(call -> call.getScope()
                        .map(s -> clientFields.contains(s.toString()))
                        .orElse(false));
    }

    /** Collects local variable names whose initializers are cross-service calls. */
    private Set<String> collectRemovedVarNames(BlockStmt body, Set<String> clientFields) {
        Set<String> names = new HashSet<>();
        for (Statement stmt : body.getStatements()) {
            if (!(stmt instanceof ExpressionStmt exprStmt)) continue;
            if (!(exprStmt.getExpression() instanceof VariableDeclarationExpr vde)) continue;
            boolean hasClientCall = vde.findAll(MethodCallExpr.class).stream()
                    .anyMatch(call -> call.getScope()
                            .map(s -> clientFields.contains(s.toString()))
                            .orElse(false));
            if (hasClientCall) {
                vde.getVariables().forEach(v -> names.add(v.getNameAsString()));
            }
        }
        return names;
    }

    /** Returns true if any NameExpr in the statement matches one of the removed variable names. */
    private boolean referencesAnyVar(Statement stmt, Set<String> varNames) {
        return stmt.findAll(NameExpr.class).stream()
                .anyMatch(n -> varNames.contains(n.getNameAsString()));
    }

    /** Returns true if the statement declares one of the given variable names. */
    private boolean isDeclaredVar(Statement stmt, Set<String> varNames) {
        if (!(stmt instanceof ExpressionStmt exprStmt)) return false;
        if (!(exprStmt.getExpression() instanceof VariableDeclarationExpr vde)) return false;
        return vde.getVariables().stream()
                .anyMatch(v -> varNames.contains(v.getNameAsString()));
    }

    private int findFirstClientCallIndex(BlockStmt body, Set<String> clientFields) {
        List<Statement> stmts = body.getStatements();
        for (int i = 0; i < stmts.size(); i++) {
            if (isClientCall(stmts.get(i), clientFields)) return i;
        }
        return -1;
    }

    /**
     * Returns the index immediately AFTER the last declaration of any of the given variable names.
     * Used to insert the publish block after extra local vars (e.g., orderId) are assigned.
     * Returns -1 if none of the vars are declared in the body (caller falls back to addStatement).
     */
    private int findPositionAfterLocalVars(BlockStmt body, Set<String> varNames) {
        List<Statement> stmts = body.getStatements();
        int lastIdx = -1;
        for (int i = 0; i < stmts.size(); i++) {
            Statement stmt = stmts.get(i);
            if (!(stmt instanceof ExpressionStmt exprStmt)) continue;
            if (!(exprStmt.getExpression() instanceof VariableDeclarationExpr vde)) continue;
            boolean declaresTargetVar = vde.getVariables().stream()
                    .anyMatch(v -> varNames.contains(v.getNameAsString()));
            if (declaresTargetVar) lastIdx = i;
        }
        return lastIdx < 0 ? -1 : lastIdx + 1;
    }

    private boolean hasField(ClassOrInterfaceDeclaration cls, String fieldName) {
        return cls.getFields().stream()
                .anyMatch(f -> f.getVariables().stream()
                        .anyMatch(v -> v.getNameAsString().equals(fieldName)));
    }

    /**
     * Finds locally-created variables (via {@code new XYZ()}) that had required setters removed
     * (i.e., one of the {@code removedStmts} was a method call on that variable).
     *
     * <p>These variables are now partially initialised — missing a NOT NULL field that
     * was previously populated from a cross-service call result. Persisting them would cause
     * {@code DataIntegrityViolationException}. We cascade-taint them so the caller can
     * remove the entire var block.
     *
     * <p>Variables whose type matches the method's declared return type are intentionally
     * excluded — they are the primary aggregate being returned and must remain.
     */
    private Set<String> findCascadedTaintedLocals(BlockStmt body,
                                                   List<Statement> removedStmts,
                                                   String methodReturnType) {
        // Collect receiver names from removed statements: "item.setUnitPrice(...)" → "item"
        Set<String> removedReceivers = new HashSet<>();
        for (Statement stmt : removedStmts) {
            stmt.findAll(MethodCallExpr.class).stream()
                    .filter(call -> call.getScope().isPresent())
                    .forEach(call -> {
                        String scope = call.getScope().get().toString();
                        if (!scope.contains(".")) {  // plain variable name, not a chain
                            removedReceivers.add(scope);
                        }
                    });
        }
        if (removedReceivers.isEmpty()) return Set.of();

        Set<String> tainted = new HashSet<>();
        for (Statement stmt : body.getStatements()) {
            if (!(stmt instanceof ExpressionStmt exprStmt)) continue;
            if (!(exprStmt.getExpression() instanceof VariableDeclarationExpr vde)) continue;
            boolean isLocallyCreated = vde.getVariables().stream()
                    .anyMatch(v -> v.getInitializer()
                            .map(init -> init instanceof ObjectCreationExpr)
                            .orElse(false));
            if (!isLocallyCreated) continue;

            String varType = vde.getElementType().asString();
            vde.getVariables().forEach(v -> {
                String varName = v.getNameAsString();
                if (removedReceivers.contains(varName) && !varType.equals(methodReturnType)) {
                    tainted.add(varName);
                    log.debug("SagaMethodTransformer: cascade-taint '{}' ({}) — setter was removed",
                            varName, varType);
                }
            });
        }
        return tainted;
    }

    /**
     * After the publish block has been inserted, removes any remaining statements
     * that appear after it (orphaned setters, second saves, premature status mutations)
     * except for a trailing {@code return} statement.
     *
     * <p>Also fixes {@code return saved} → {@code return <bestLocalVar>} when {@code saved}
     * was one of the removed cross-service call variables.
     *
     * @param body            the method body to clean up
     * @param publishBlockSize number of statements that were just inserted
     * @param removedVarNames  variable names that were removed (used for return-fixup)
     * @param methodReturnType declared return type of the saga method
     */
    private void stripOrphanStatementsAfterPublish(BlockStmt body,
                                                    int publishBlockSize,
                                                    Set<String> removedVarNames,
                                                    String methodReturnType) {
        List<Statement> stmts = body.getStatements();

        // Find the index of the last publish statement we inserted
        int publishEndIdx = -1;
        for (int i = stmts.size() - 1; i >= 0; i--) {
            Statement s = stmts.get(i);
            // outboxPublisher.publish(...) is an ExpressionStmt containing a MethodCallExpr
            if (s.findAll(MethodCallExpr.class).stream()
                    .anyMatch(call -> "publish".equals(call.getNameAsString())
                            && call.getScope().map(sc -> sc.toString().contains("outboxPublisher")).orElse(false))) {
                publishEndIdx = i;
                break;
            }
        }
        if (publishEndIdx < 0) return;

        // Remove every statement after the publish block that isn't a return
        List<Statement> toRemove = new ArrayList<>();
        for (int i = publishEndIdx + 1; i < stmts.size(); i++) {
            Statement s = stmts.get(i);
            if (!s.isReturnStmt()) {
                toRemove.add(s);
            }
        }
        toRemove.forEach(body::remove);

        // Fix-up: if the return statement references a variable that is no longer declared
        // in the body (either removed directly or cascade-removed), substitute the last
        // declared local variable whose type matches the return type.
        if (!"void".equals(methodReturnType)) {
            Set<String> declaredVars = collectDeclaredVarNames(body);
            stmts.stream()
                    .filter(com.github.javaparser.ast.stmt.Statement::isReturnStmt)
                    .map(s -> s.asReturnStmt())
                    .filter(ret -> ret.getExpression().isPresent())
                    .forEach(ret -> {
                        String retExpr = ret.getExpression().get().toString();
                        // Only attempt substitution for simple names (not method calls or field access)
                        boolean isSimpleName = !retExpr.contains(".") && !retExpr.contains("(")
                                && !retExpr.equals("null") && !retExpr.equals("this");
                        if (isSimpleName && !declaredVars.contains(retExpr)) {
                            String substitute = findLastDeclaredVarOfType(
                                    body, methodReturnType, Set.of(retExpr));
                            if (substitute != null) {
                                ret.setExpression(new NameExpr(substitute));
                                log.debug("SagaMethodTransformer: replaced 'return {}' with 'return {}'",
                                        retExpr, substitute);
                            }
                        }
                    });
        }
    }

    /** Collects the names of all variables currently declared in the method body. */
    private Set<String> collectDeclaredVarNames(BlockStmt body) {
        Set<String> names = new HashSet<>();
        for (Statement stmt : body.getStatements()) {
            if (!(stmt instanceof ExpressionStmt exprStmt)) continue;
            if (!(exprStmt.getExpression() instanceof VariableDeclarationExpr vde)) continue;
            vde.getVariables().forEach(v -> names.add(v.getNameAsString()));
        }
        return names;
    }

    /**
     * Finds the last local variable declared in {@code body} whose simple type name matches
     * {@code targetType}, excluding any names in {@code excludedNames}.
     */
    private String findLastDeclaredVarOfType(BlockStmt body, String targetType, Set<String> excludedNames) {
        String result = null;
        for (Statement stmt : body.getStatements()) {
            if (!(stmt instanceof ExpressionStmt exprStmt)) continue;
            if (!(exprStmt.getExpression() instanceof VariableDeclarationExpr vde)) continue;
            String declaredType = vde.getElementType().asString();
            // Match on simple name (e.g., "Order" matches "Order" or "order")
            if (declaredType.equals(targetType) || declaredType.equalsIgnoreCase(targetType)) {
                vde.getVariables().forEach(v -> {
                    // Use the last candidate that wasn't itself removed
                });
                for (var v : vde.getVariables()) {
                    String name = v.getNameAsString();
                    if (!excludedNames.contains(name)) {
                        result = name;
                    }
                }
            }
        }
        return result;
    }

    /**
     * Parses a block of Java statements by wrapping them in a dummy method, then extracts the statements.
     */
    private List<Statement> parseStatements(String code) {
        String wrapped = "class X { void m() {\n" + code + "\n} }";
        try {
            CompilationUnit cu = javaParser.parse(wrapped).getResult().orElse(null);
            if (cu == null) return List.of();
            return cu.findAll(MethodDeclaration.class).stream()
                    .findFirst()
                    .flatMap(MethodDeclaration::getBody)
                    .map(b -> new ArrayList<>(b.getStatements()))
                    .orElse(new ArrayList<>());
        } catch (Exception e) {
            log.warn("SagaMethodTransformer: failed to parse publish block: {}", e.getMessage());
            return List.of();
        }
    }
}
