package org.fractalx.core.generator.transformation;

import org.fractalx.core.generator.GenerationContext;
import org.fractalx.core.generator.ServiceFileGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

/**
 * Generates per-service Spring Security configuration that integrates with the
 * FractalX API Gateway's Internal Call Token model.
 *
 * <p>When the monolith had Spring Security enabled (detected by
 * {@link org.fractalx.core.gateway.SecurityAnalyzer}), this step generates:
 *
 * <ul>
 *   <li><b>{@code GatewayAuthHeaderFilter.java}</b> — validates the signed
 *       {@code X-Internal-Token} header injected by the API Gateway. The token
 *       is a short-lived HMAC-SHA256 JWT containing the user's ID and roles.
 *       On success it establishes a Spring {@code Authentication} in
 *       {@code SecurityContextHolder}, enabling {@code @PreAuthorize} and
 *       {@code @Secured} method-level security within this service.</li>
 *   <li><b>{@code ServiceSecurityConfig.java}</b> — stateless Spring Security
 *       configuration with {@code @EnableMethodSecurity}. All HTTP endpoints
 *       are permitted at the security filter chain level (authentication is the
 *       gateway's responsibility); method-level authorization is enforced via
 *       the populated {@code SecurityContextHolder}.</li>
 * </ul>
 *
 * <p>Also injects JJWT dependencies into the generated service's {@code pom.xml}
 * and adds the {@code fractalx.security.internal-jwt-secret} property to
 * {@code application-dev.yml}.
 *
 * <p>This step is a no-op when no Spring Security was detected in the monolith
 * ({@link GenerationContext#isSecurityEnabled()} returns {@code false}).
 */
public class ServiceSecurityStep implements ServiceFileGenerator {

    private static final Logger log = LoggerFactory.getLogger(ServiceSecurityStep.class);

    private static final String JJWT_VERSION = "0.12.6";

    @Override
    public void generate(GenerationContext context) throws IOException {
        if (!context.isSecurityEnabled()) {
            log.debug("ServiceSecurityStep: no security detected in monolith — skipping for {}",
                    context.getModule().getServiceName());
            return;
        }

        log.info("  🔒 [Security] Generating gateway-trust security config for: {}",
                context.getModule().getServiceName());

        String pkg = context.servicePackage();
        Path pkgPath = createPackagePath(context.getSrcMainJava(), pkg);

        generateGatewayAuthHeaderFilter(pkgPath, pkg);
        generateServiceSecurityConfig(pkgPath, pkg);
        injectJjwtDependencies(context);
        injectSecurityYaml(context);

        log.info("   ✓ Generated GatewayAuthHeaderFilter.java + ServiceSecurityConfig.java");
    }

    // -------------------------------------------------------------------------
    // File generators
    // -------------------------------------------------------------------------

    private void generateGatewayAuthHeaderFilter(Path pkgPath, String pkg) throws IOException {
        String content = """
                package %s;

                import io.jsonwebtoken.Claims;
                import io.jsonwebtoken.Jwts;
                import io.jsonwebtoken.security.Keys;
                import jakarta.servlet.FilterChain;
                import jakarta.servlet.ServletException;
                import jakarta.servlet.http.HttpServletRequest;
                import jakarta.servlet.http.HttpServletResponse;
                import org.fractalx.runtime.GatewayPrincipal;
                import org.springframework.beans.factory.annotation.Value;
                import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
                import org.springframework.security.core.authority.SimpleGrantedAuthority;
                import org.springframework.security.core.context.SecurityContextHolder;
                import org.springframework.web.filter.OncePerRequestFilter;

                import javax.crypto.SecretKey;

                import java.io.IOException;
                import java.nio.charset.StandardCharsets;
                import java.util.Arrays;
                import java.util.Collections;
                import java.util.HashMap;
                import java.util.List;
                import java.util.Map;
                import java.util.Set;
                import java.util.stream.Collectors;

                /**
                 * Auto-Generated by FractalX.
                 *
                 * Validates the {@code X-Internal-Token} header injected by the FractalX API Gateway —
                 * a short-lived HMAC-SHA256-signed JWT minted after the gateway successfully
                 * authenticated the external user's credential (Bearer JWT / OAuth2 / Basic / API Key).
                 *
                 * <p>On successful validation, constructs an {@link GatewayPrincipal} and establishes
                 * a Spring {@link org.springframework.security.core.Authentication} in
                 * {@link SecurityContextHolder}. The principal is available via:
                 * <ul>
                 *   <li>{@code @AuthenticationPrincipal GatewayPrincipal principal}</li>
                 *   <li>{@code @PreAuthorize("principal.id == #userId")}</li>
                 *   <li>{@code @PreAuthorize("principal.hasRole('ADMIN')")}</li>
                 *   <li>{@code principal.getAttribute("customerId")} — for custom claims</li>
                 * </ul>
                 *
                 * <p>The internal token is verified with {@code fractalx.security.internal-jwt-secret}
                 * (env var {@code FRACTALX_INTERNAL_JWT_SECRET}). This secret MUST match the one
                 * configured in the API Gateway.
                 *
                 * <p><b>IMPORTANT:</b> This service MUST only be reachable via the API Gateway in
                 * production. Direct access bypasses the gateway's authentication step entirely.
                 */
                public class GatewayAuthHeaderFilter extends OncePerRequestFilter {

                    private static final Set<String> RESERVED_CLAIMS = Set.of(
                            "sub", "roles", "iss", "aud", "iat", "exp", "username", "email");

                    @Value("${fractalx.security.internal-jwt-secret:fractalx-internal-secret-change-in-prod-!!}")
                    private String internalJwtSecret;

                    @Override
                    protected void doFilterInternal(HttpServletRequest request,
                                                     HttpServletResponse response,
                                                     FilterChain filterChain)
                            throws ServletException, IOException {

                        String internalToken = request.getHeader("X-Internal-Token");
                        if (internalToken != null && !internalToken.isBlank()) {
                            try {
                                SecretKey key = Keys.hmacShaKeyFor(
                                        internalJwtSecret.getBytes(StandardCharsets.UTF_8));
                                Claims claims = Jwts.parser()
                                        .verifyWith(key).build()
                                        .parseSignedClaims(internalToken).getPayload();

                                String userId   = claims.getSubject();
                                String rolesStr = claims.get("roles", String.class);
                                List<SimpleGrantedAuthority> authorities =
                                        (rolesStr == null || rolesStr.isBlank())
                                                ? List.of()
                                                : Arrays.stream(rolesStr.split(","))
                                                         .map(String::trim)
                                                         .filter(r -> !r.isBlank())
                                                         .map(r -> new SimpleGrantedAuthority("ROLE_" + r))
                                                         .collect(Collectors.toList());

                                // Extract extended claims forwarded by the gateway
                                String username = claims.get("username", String.class);
                                String email    = claims.get("email", String.class);
                                Map<String, Object> attributes = new HashMap<>();
                                claims.forEach((k, v) -> {
                                    if (!RESERVED_CLAIMS.contains(k)) attributes.put(k, v);
                                });

                                GatewayPrincipal principal = new GatewayPrincipal(
                                        userId, username, email, authorities,
                                        Collections.unmodifiableMap(attributes));

                                // Store the raw token as credentials so NetScopeContextInterceptor
                                // can forward it via gRPC metadata for cross-service calls.
                                var auth = new UsernamePasswordAuthenticationToken(
                                        principal, internalToken, authorities);
                                SecurityContextHolder.getContext().setAuthentication(auth);

                            } catch (Exception e) {
                                logger.warn("GatewayAuthHeaderFilter: invalid/expired X-Internal-Token — " + e.getMessage());
                                response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
                                response.setContentType("application/json");
                                response.getWriter().write("{\\"error\\":\\"invalid-internal-token\\"}");
                                return;
                            }
                        }
                        filterChain.doFilter(request, response);
                    }
                }
                """.formatted(pkg);
        Files.writeString(pkgPath.resolve("GatewayAuthHeaderFilter.java"), content);
    }

    private void generateServiceSecurityConfig(Path pkgPath, String pkg) throws IOException {
        String content = """
                package %s;

                import org.springframework.context.annotation.Bean;
                import org.springframework.context.annotation.Configuration;
                import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
                import org.springframework.security.config.annotation.web.builders.HttpSecurity;
                import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
                import org.springframework.security.config.http.SessionCreationPolicy;
                import org.springframework.security.web.SecurityFilterChain;
                import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;

                /**
                 * Auto-Generated by FractalX.
                 *
                 * Security configuration for this microservice — follows the <em>gateway-trust model</em>:
                 * <ol>
                 *   <li>Authentication is performed once at the API Gateway (Bearer JWT / OAuth2 / Basic).</li>
                 *   <li>The gateway mints a short-lived Internal Call Token and forwards it as
                 *       {@code X-Internal-Token}.</li>
                 *   <li>{@link GatewayAuthHeaderFilter} validates the token and populates
                 *       {@code SecurityContextHolder}.</li>
                 *   <li>{@code @PreAuthorize} / {@code @Secured} annotations on service methods are
                 *       enforced against the established {@code Authentication}.</li>
                 *   <li>When this service calls another service via NetScope gRPC, the Internal Call
                 *       Token is automatically forwarded via {@code x-internal-token} gRPC metadata
                 *       by {@code fractalx-runtime}'s {@code NetScopeContextInterceptor}.</li>
                 * </ol>
                 *
                 * <p>All HTTP endpoints are permitted at the filter-chain level — the gateway is the
                 * authentication perimeter. Method-level authorization is handled via
                 * {@code @EnableMethodSecurity}.
                 *
                 * <p><strong>Production requirement:</strong> This service MUST only be reachable via
                 * the API Gateway. Expose it directly only in development/testing.
                 */
                @Configuration
                @EnableWebSecurity
                @EnableMethodSecurity
                public class ServiceSecurityConfig {

                    @Bean
                    public SecurityFilterChain securityFilterChain(HttpSecurity http,
                                                                    GatewayAuthHeaderFilter authFilter)
                            throws Exception {
                        http.csrf(csrf -> csrf.disable())
                            .sessionManagement(sm -> sm
                                    .sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                            .authorizeHttpRequests(auth -> auth
                                    .requestMatchers("/actuator/**").permitAll()
                                    .anyRequest().permitAll()  // gateway enforces auth; @PreAuthorize does method-level
                            )
                            .addFilterBefore(authFilter, UsernamePasswordAuthenticationFilter.class);
                        return http.build();
                    }

                    @Bean
                    public GatewayAuthHeaderFilter gatewayAuthHeaderFilter() {
                        return new GatewayAuthHeaderFilter();
                    }
                }
                """.formatted(pkg);
        Files.writeString(pkgPath.resolve("ServiceSecurityConfig.java"), content);
    }

    // -------------------------------------------------------------------------
    // Pom injection (JJWT + spring-boot-starter-security)
    // -------------------------------------------------------------------------

    private void injectJjwtDependencies(GenerationContext context) throws IOException {
        Path pomFile = context.getServiceRoot().resolve("pom.xml");
        if (!Files.exists(pomFile)) return;

        String pom = Files.readString(pomFile);

        // Security dep must be added independently — jjwt may already be in the monolith pom
        // (cloned from the monolith) but spring-boot-starter-security may still be missing.
        boolean needsSecurity = !pom.contains("<artifactId>spring-boot-starter-security</artifactId>");
        boolean needsJjwt     = !pom.contains("<artifactId>jjwt-api</artifactId>");

        if (!needsSecurity && !needsJjwt) return; // nothing to inject

        String securityBlock = needsSecurity ? """

                        <dependency>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-starter-security</artifactId>
                        </dependency>""" : "";

        if (!needsJjwt) {
            // Only need the security dep — inject it and return
            int lastClose = pom.lastIndexOf("</dependencies>");
            if (lastClose < 0) {
                log.warn("Could not find </dependencies> in pom.xml for {} — security dep not injected",
                        context.getModule().getServiceName());
                return;
            }
            pom = pom.substring(0, lastClose) + securityBlock + "\n                    </dependencies>"
                    + pom.substring(lastClose + "</dependencies>".length());
            Files.writeString(pomFile, pom);
            return;
        }

        String jjwtBlock = securityBlock + """

                        <!-- FractalX Internal Call Token validation (generated by ServiceSecurityStep) -->
                        <dependency>
                            <groupId>io.jsonwebtoken</groupId>
                            <artifactId>jjwt-api</artifactId>
                            <version>%s</version>
                        </dependency>
                        <dependency>
                            <groupId>io.jsonwebtoken</groupId>
                            <artifactId>jjwt-impl</artifactId>
                            <version>%s</version>
                            <scope>runtime</scope>
                        </dependency>
                        <dependency>
                            <groupId>io.jsonwebtoken</groupId>
                            <artifactId>jjwt-jackson</artifactId>
                            <version>%s</version>
                            <scope>runtime</scope>
                        </dependency>
                """.formatted(JJWT_VERSION, JJWT_VERSION, JJWT_VERSION);

        // Insert just before the LAST </dependencies> tag to avoid corrupting
        // <dependencyManagement> blocks that also contain </dependencies>.
        int lastClose = pom.lastIndexOf("</dependencies>");
        if (lastClose < 0) {
            log.warn("Could not find </dependencies> in pom.xml for {} — JJWT dependencies not injected",
                    context.getModule().getServiceName());
            return;
        }
        String updated = pom.substring(0, lastClose)
                + jjwtBlock + "    </dependencies>"
                + pom.substring(lastClose + "</dependencies>".length());
        Files.writeString(pomFile, updated);
    }

    // -------------------------------------------------------------------------
    // YAML injection
    // -------------------------------------------------------------------------

    private void injectSecurityYaml(GenerationContext context) throws IOException {
        Path devYml = context.getSrcMainResources().resolve("application-dev.yml");
        if (!Files.exists(devYml)) return;

        String block = """

                # ---------------------------------------------------------------------------
                # FractalX Internal Security — Internal Call Token validation
                # The gateway mints a short-lived signed JWT after authenticating the user
                # and forwards it as X-Internal-Token to downstream services.
                # This secret MUST match fractalx.gateway.security.internal-jwt-secret
                # in the API Gateway config. Use env var FRACTALX_INTERNAL_JWT_SECRET
                # for production — set the same value on all services and the gateway.
                # ---------------------------------------------------------------------------
                fractalx:
                  security:
                    internal-jwt-secret: ${FRACTALX_INTERNAL_JWT_SECRET:fractalx-internal-secret-change-in-prod-!!}
                """;
        Files.writeString(devYml, block, StandardOpenOption.APPEND);
    }

    // -------------------------------------------------------------------------
    // Utility
    // -------------------------------------------------------------------------

    private Path createPackagePath(Path srcMainJava, String packageName) throws IOException {
        String[] parts = packageName.split("\\.");
        Path path = srcMainJava;
        for (String part : parts) {
            path = path.resolve(part);
        }
        Files.createDirectories(path);
        return path;
    }
}
