package com.fractalx.core.observability;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * RESEARCH COMPONENT: Handles the injection of Observability configurations.
 */
public class ObservabilityInjector {

    private static final Logger log = LoggerFactory.getLogger(ObservabilityInjector.class);
    private static final String LOGGER_SERVICE_URL = "http://localhost:9099/api/logs";

    public String getDependencies() {
        return """
                <!-- Micrometer OpenTelemetry tracing bridge (replaces Brave) -->
                        <dependency>
                            <groupId>io.micrometer</groupId>
                            <artifactId>micrometer-tracing-bridge-otel</artifactId>
                        </dependency>

                        <!-- OpenTelemetry SDK for span creation and OTLP export to Jaeger -->
                        <dependency>
                            <groupId>io.opentelemetry</groupId>
                            <artifactId>opentelemetry-sdk</artifactId>
                            <version>1.32.0</version>
                        </dependency>
                        <dependency>
                            <groupId>io.opentelemetry</groupId>
                            <artifactId>opentelemetry-exporter-otlp</artifactId>
                            <version>1.32.0</version>
                        </dependency>
                        <dependency>
                            <groupId>io.opentelemetry.semconv</groupId>
                            <artifactId>opentelemetry-semconv</artifactId>
                            <version>1.21.0-alpha</version>
                        </dependency>

                        <!-- Prometheus registry for /actuator/prometheus scraping -->
                        <dependency>
                            <groupId>io.micrometer</groupId>
                            <artifactId>micrometer-registry-prometheus</artifactId>
                        </dependency>
                        """;
    }

    /**
     * Safely patches the application.yml file.
     * It checks if the file exists and if the "fractalx" block is present,
     * then appends the logger-url without breaking indentation.
     */
    public void patchConfigurationFile(Path resourcesDir) {
        Path ymlPath = resourcesDir.resolve("application.yml");

        try {
            if (!Files.exists(ymlPath)) {
                log.warn("Cannot patch application.yml: File not found at {}", ymlPath);
                return;
            }

            String content = Files.readString(ymlPath);

            // We look for the standard metrics line generated by ConfigurationGenerator
            String targetLine = "metrics: true";

            // The line we want to insert (aligned with 4 spaces to match the file)
            String insertion = "metrics: true\n    logger-url: " + LOGGER_SERVICE_URL;

            if (content.contains(targetLine) && !content.contains("logger-url:")) {
                String newContent = content.replace(targetLine, insertion);

                // Also add the management endpoints if missing
                if (!newContent.contains("management:")) {
                    newContent += "\n" + getManagementConfig();
                }

                Files.writeString(ymlPath, newContent);
                log.info("✓ Patched application.yml with Central Logger URL");
            }

        } catch (IOException e) {
            log.error("Failed to patch configuration file", e);
        }
    }

    private String getManagementConfig() {
        return """
            management:
              endpoints:
                web:
                  exposure:
                    include: health,info,metrics,prometheus
              tracing:
                sampling:
                  probability: 1.0
            """;
    }
}