package org.fractalx.core.verifier;

import org.fractalx.core.model.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates a {@code @SpringBootTest} smoke test in every generated service.
 *
 * <p>The generated test class loads the full Spring application context with
 * {@code webEnvironment = NONE} (no HTTP server started). If the context loads
 * without errors, the service is correctly wired — all {@code @Bean} definitions
 * resolve, all {@code @Autowired} targets exist, no circular dependencies, and
 * all required properties are present.
 *
 * <p>To run smoke tests after generating them:
 * <pre>
 *   cd target/generated-services/order-service
 *   mvn test
 * </pre>
 *
 * <p>Or use the verify goal to generate and compile-check them:
 * <pre>
 *   mvn fractalx:verify -Dfractalx.verify.compile=true -Dfractalx.verify.smokeTests=true
 * </pre>
 *
 * <p>The generated class intentionally uses only Spring Boot test infrastructure
 * so no extra test dependency is needed beyond what each service already has.
 */
public class SmokeTestGenerator {

    private static final Logger log = LoggerFactory.getLogger(SmokeTestGenerator.class);

    public record GenerationResult(String serviceName, boolean success, String detail) {}

    /**
     * Generates a smoke test in each module service directory.
     *
     * @param outputDir root generated-services directory
     * @param modules   all decomposed modules
     * @return one result per service
     */
    public List<GenerationResult> generate(Path outputDir, List<FractalModule> modules) {
        return generate(outputDir, modules, "generated");
    }

    public List<GenerationResult> generate(Path outputDir, List<FractalModule> modules, String basePackage) {
        List<GenerationResult> results = new ArrayList<>();

        for (FractalModule module : modules) {
            results.add(generateForService(outputDir, module, basePackage));
        }

        return results;
    }

    // ── Per-service generation ─────────────────────────────────────────────────

    private GenerationResult generateForService(Path outputDir, FractalModule module, String basePackage) {
        Path svcDir = outputDir.resolve(module.getServiceName());
        if (!Files.isDirectory(svcDir)) {
            return new GenerationResult(module.getServiceName(), false,
                    "Service directory not found — run fractalx:decompose first");
        }

        // Locate the main application class to derive the package
        String testPackage = deriveTestPackage(svcDir, module, basePackage);
        Path testDir = svcDir.resolve("src/test/java")
                .resolve(testPackage.replace(".", "/"));

        try {
            Files.createDirectories(testDir);
            Path testFile = testDir.resolve("FractalXSmokeTest.java");
            Files.writeString(testFile, buildSmokeTestSource(testPackage, module));
            log.debug("Generated smoke test for {} at {}", module.getServiceName(), testFile);
            return new GenerationResult(module.getServiceName(), true,
                    testFile.toString());
        } catch (IOException e) {
            return new GenerationResult(module.getServiceName(), false,
                    "Could not write smoke test: " + e.getMessage());
        }
    }

    // ── Source generation ──────────────────────────────────────────────────────

    private String buildSmokeTestSource(String pkg, FractalModule module) {
        String serviceName = module.getServiceName();
        return """
                package %s;

                import org.junit.jupiter.api.Test;
                import org.springframework.boot.test.context.SpringBootTest;
                import org.springframework.test.context.ActiveProfiles;

                /**
                 * FractalX-generated Spring context smoke test for %s.
                 *
                 * <p>Loads the full application context without starting an HTTP server.
                 * A successful context load proves:
                 * <ul>
                 *   <li>All @Bean / @Component / @Service / @Repository classes are resolvable</li>
                 *   <li>All @Autowired / constructor-injection targets exist</li>
                 *   <li>No circular bean dependencies</li>
                 *   <li>All required @ConfigurationProperties are present in application.yml</li>
                 *   <li>NetScope client interfaces are correctly registered as beans</li>
                 * </ul>
                 *
                 * <p>This test was generated by FractalX — do not modify by hand.
                 */
                @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
                @ActiveProfiles("dev")
                class FractalXSmokeTest {

                    @Test
                    void contextLoads() {
                        // If Spring context loads without throwing, this test passes.
                        // Any missing bean, unresolved property, or circular dependency
                        // will cause an ApplicationContextException here.
                    }
                }
                """.formatted(pkg, serviceName);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Derives a test package from the module.
     * Uses the generated package {@code org.fractalx.generated.<servicename>}
     * (where OtelConfig / ServiceHealthConfig live) if it exists,
     * otherwise falls back to the original module package.
     */
    private String deriveTestPackage(Path svcDir, FractalModule module, String basePackage) {
        // Prefer the generated sub-package as it is always present post-decomposition
        String simpleName = module.getServiceName().replace("-", "").toLowerCase();
        String candidate = basePackage + "." + simpleName;
        Path candidatePath = svcDir.resolve("src/main/java")
                .resolve(candidate.replace(".", "/"));
        if (Files.isDirectory(candidatePath)) return candidate;

        // Fallback to original package
        return module.getPackageName() != null
                ? module.getPackageName()
                : basePackage + "." + simpleName;
    }
}
