package org.fractalx.core.datamanagement;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.AnnotationExpr;
import com.github.javaparser.ast.expr.MemberValuePair;
import com.github.javaparser.ast.expr.NormalAnnotationExpr;
import org.fractalx.core.model.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.stream.Stream;

/**
 * Generates configuration to restrict JPA scanning to the service's own package.
 *
 * <p>Also detects {@code @Table(schema = "...")} on entity classes — a pattern used
 * when a monolith maps one datasource to multiple schemas. If additional schemas are
 * found beyond the module's own package, a {@code FRACTALX-WARNING} comment block is
 * prepended to {@code IsolationConfig.java} so the developer knows to configure the
 * datasource accordingly.
 */
public class DataIsolationGenerator {

    private static final Logger log = LoggerFactory.getLogger(DataIsolationGenerator.class);

    public void generateIsolationConfig(FractalModule module, Path srcMainJava,
                                         String basePackage) throws IOException {
        log.info("🛡️ [Data] Enforcing data boundaries for: {}", module.getServiceName());
        String configPackage = basePackage + ".config";

        Path configPath = createPackagePath(srcMainJava, configPackage);

        // Detect any @Table(schema = "...") annotations in copied entity files
        Set<String> extraSchemas = detectExtraSchemas(srcMainJava, module.getPackageName());

        String classContent = generateConfigClass(configPackage, basePackage,
                module.getPackageName(), extraSchemas);

        Path filePath = configPath.resolve("IsolationConfig.java");
        Files.writeString(filePath, classContent);

        if (!extraSchemas.isEmpty()) {
            log.warn("   ⚠ Multi-schema entities detected in {} — schemas: {}. " +
                     "Configure datasource to span all required schemas.",
                    module.getServiceName(), extraSchemas);
        }
        log.info("   ✓ Created IsolationConfig.java");
    }

    /**
     * Scans all {@code .java} files under {@code srcMainJava} for
     * {@code @Table(schema = "...")} annotations. Returns the set of non-blank schema
     * names found, excluding the module's own package name (treated as the default schema).
     */
    private Set<String> detectExtraSchemas(Path srcMainJava, String modulePackageName) {
        Set<String> schemas = new LinkedHashSet<>();
        if (!Files.isDirectory(srcMainJava)) return schemas;

        try (Stream<Path> paths = Files.walk(srcMainJava)) {
            paths.filter(p -> p.toString().endsWith(".java")).forEach(p -> {
                try {
                    CompilationUnit cu = new JavaParser().parse(p).getResult().orElse(null);
                    if (cu == null) return;
                    cu.findAll(AnnotationExpr.class).forEach(ann -> {
                        if (!"Table".equals(ann.getNameAsString())) return;
                        if (!(ann instanceof NormalAnnotationExpr nae)) return;
                        for (MemberValuePair pair : nae.getPairs()) {
                            if (!"schema".equals(pair.getNameAsString())) continue;
                            String schema = pair.getValue().toString()
                                    .replace("\"", "").strip();
                            if (!schema.isEmpty()) schemas.add(schema);
                        }
                    });
                } catch (Exception e) {
                    log.debug("Could not parse {} for @Table schema detection", p);
                }
            });
        } catch (IOException e) {
            log.debug("Could not walk {} for schema detection", srcMainJava);
        }
        return schemas;
    }

    private Path createPackagePath(Path srcMainJava, String packageName) throws IOException {
        String[] parts = packageName.split("\\.");
        Path path = srcMainJava;
        for (String part : parts) {
            path = path.resolve(part);
        }
        Files.createDirectories(path);
        return path;
    }

    private String generateConfigClass(String configPackage, String generatedPackage,
                                        String sourcePackage, Set<String> extraSchemas) {
        String warningBlock = extraSchemas.isEmpty() ? "" : buildSchemaWarning(extraSchemas);
        return """
            package %s;

            import org.springframework.context.annotation.Configuration;
            import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
            import org.springframework.boot.autoconfigure.domain.EntityScan;
            %s
            /**
             * Auto-Generated by FractalX.
             * Restricts JPA scanning to this service's own packages to prevent
             * accessing other services' tables. Scans both the generated base
             * package and the original monolith source package.
             */
            @Configuration
            @EnableJpaRepositories(basePackages = {"%s", "%s"})
            @EntityScan(basePackages = {"%s", "%s"})
            public class IsolationConfig {
            }
            """.formatted(configPackage, warningBlock,
                    generatedPackage, sourcePackage, generatedPackage, sourcePackage);
    }

    private String buildSchemaWarning(Set<String> schemas) {
        return """

            /*
             * FRACTALX-WARNING: multi-schema entities detected.
             * The following database schemas were referenced via @Table(schema = "...")
             * in entity classes copied into this service: %s
             *
             * In the monolith these schemas were accessed via a single datasource.
             * After decomposition each service should own exactly one schema.
             * Options:
             *   1. If this service legitimately needs multiple schemas, configure
             *      spring.datasource.url with a schema-search-path / currentSchema
             *      parameter that includes all required schemas.
             *   2. If cross-schema entities belong to another service, replace
             *      the @ManyToOne / @OneToOne relationships with ID fields and
             *      use NetScope clients to fetch the data at runtime.
             */
            """.formatted(schemas);
    }
}
