package org.fractalx.core.datamanagement;

import org.fractalx.core.model.FractalModule;
import org.fractalx.core.model.SagaDefinition;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates the transactional outbox pattern for services that participate in
 * distributed sagas or have cross-module dependencies.
 *
 * <p>The outbox pattern solves the dual-write problem: business state and the
 * intent to notify other services are written atomically in the same local
 * transaction. A scheduled poller then reads unpublished events and forwards
 * them — guaranteed at-least-once delivery without a message broker.
 *
 * <p>Generated files per service:
 * <ul>
 *   <li>{@code OutboxEvent.java} — JPA entity stored in {@code fractalx_outbox}</li>
 *   <li>{@code OutboxRepository.java} — Spring Data repository</li>
 *   <li>{@code OutboxPublisher.java} — bean used inside business {@code @Transactional} methods</li>
 *   <li>{@code OutboxPoller.java} — scheduled publisher that forwards pending events to saga orchestrator</li>
 *   <li>{@code SagaOutboxAspect.java} — AOP aspect that auto-publishes to outbox after each saga method (saga-owning services only)</li>
 * </ul>
 */
public class OutboxGenerator {

    private static final Logger log = LoggerFactory.getLogger(OutboxGenerator.class);

    public void generateOutbox(FractalModule module, Path serviceRoot,
                               List<SagaDefinition> sagaDefinitions) throws IOException {
        String basePackage   = "org.fractalx.generated." + module.getServiceName().replace("-", "");
        String outboxPackage = basePackage + ".outbox";

        Path outboxPath = createPackagePath(serviceRoot.resolve("src/main/java"), outboxPackage);

        writeFile(outboxPath, "OutboxEvent.java",      buildOutboxEvent(outboxPackage));
        writeFile(outboxPath, "OutboxRepository.java", buildOutboxRepository(outboxPackage));
        writeFile(outboxPath, "OutboxPublisher.java",  buildOutboxPublisher(outboxPackage));
        writeFile(outboxPath, "OutboxPoller.java",     buildOutboxPoller(module, outboxPackage));

        log.info("Generated transactional outbox for: {}", module.getServiceName());
    }

    // -------------------------------------------------------------------------
    // OutboxEvent
    // -------------------------------------------------------------------------

    private String buildOutboxEvent(String pkg) {
        return """
                package %s;

                import jakarta.persistence.*;
                import java.time.LocalDateTime;

                /**
                 * Transactional outbox event — written atomically with business state.
                 * Auto-generated by FractalX.
                 */
                @Entity
                @Table(name = "fractalx_outbox",
                       indexes = @Index(name = "idx_outbox_unpublished",
                                        columnList = "published, createdAt"))
                public class OutboxEvent {

                    @Id
                    @GeneratedValue(strategy = GenerationType.IDENTITY)
                    private Long id;

                    /** Logical event type — matches a saga ID (e.g., "place-order-saga"). */
                    @Column(nullable = false)
                    private String eventType;

                    /** ID of the aggregate that produced this event. */
                    @Column(nullable = false)
                    private String aggregateId;

                    /** JSON-serialized event payload. */
                    @Column(columnDefinition = "TEXT")
                    private String payload;

                    /**
                     * Correlation ID from the originating HTTP request.
                     * Captured while still in the HTTP thread (MDC is populated) so it
                     * can be forwarded even when the OutboxPoller runs on a scheduler thread.
                     */
                    @Column
                    private String correlationId;

                    /** Whether this event has been successfully forwarded. */
                    @Column(nullable = false)
                    private boolean published = false;

                    /** How many times publishing has been attempted. */
                    @Column(nullable = false)
                    private int retryCount = 0;

                    @Column(nullable = false)
                    private LocalDateTime createdAt;

                    private LocalDateTime publishedAt;

                    @PrePersist
                    protected void onCreate() { createdAt = LocalDateTime.now(); }

                    public Long getId()                  { return id; }
                    public String getEventType()         { return eventType; }
                    public void setEventType(String v)   { eventType = v; }
                    public String getAggregateId()       { return aggregateId; }
                    public void setAggregateId(String v) { aggregateId = v; }
                    public String getPayload()           { return payload; }
                    public void setPayload(String v)     { payload = v; }
                    public String getCorrelationId()     { return correlationId; }
                    public void setCorrelationId(String v) { correlationId = v; }
                    public boolean isPublished()         { return published; }
                    public void setPublished(boolean v)  { published = v; }
                    public int getRetryCount()           { return retryCount; }
                    public void setRetryCount(int v)     { retryCount = v; }
                    public LocalDateTime getCreatedAt()  { return createdAt; }
                    public LocalDateTime getPublishedAt(){ return publishedAt; }
                    public void setPublishedAt(LocalDateTime v) { publishedAt = v; }
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxRepository
    // -------------------------------------------------------------------------

    private String buildOutboxRepository(String pkg) {
        return """
                package %s;

                import org.springframework.data.jpa.repository.JpaRepository;
                import java.util.List;

                /**
                 * Repository for transactional outbox events.
                 * Auto-generated by FractalX.
                 */
                public interface OutboxRepository extends JpaRepository<OutboxEvent, Long> {

                    /** Returns unpublished events ordered by creation time (oldest first). */
                    List<OutboxEvent> findByPublishedFalseOrderByCreatedAtAsc();

                    /** Returns events that failed more than {@code maxRetries} times. */
                    List<OutboxEvent> findByPublishedFalseAndRetryCountGreaterThan(int maxRetries);
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxPublisher
    // -------------------------------------------------------------------------

    private String buildOutboxPublisher(String pkg) {
        return """
                package %s;

                import com.fasterxml.jackson.core.JsonProcessingException;
                import com.fasterxml.jackson.databind.ObjectMapper;
                import org.slf4j.Logger;
                import org.slf4j.LoggerFactory;
                import org.slf4j.MDC;
                import org.springframework.stereotype.Component;

                /**
                 * Publishes business events to the transactional outbox.
                 *
                 * <p>Must be called inside an active {@code @Transactional} method so the
                 * outbox record is written atomically with the business state change.
                 * Auto-generated by FractalX — called automatically by the saga method transformer.
                 */
                @Component
                public class OutboxPublisher {

                    private static final Logger log = LoggerFactory.getLogger(OutboxPublisher.class);

                    private final OutboxRepository outboxRepository;
                    private final ObjectMapper     objectMapper;

                    public OutboxPublisher(OutboxRepository outboxRepository, ObjectMapper objectMapper) {
                        this.outboxRepository = outboxRepository;
                        this.objectMapper     = objectMapper;
                    }

                    /**
                     * Writes an outbox record for the given event.
                     *
                     * @param eventType   saga ID (e.g., "place-order-saga")
                     * @param aggregateId ID of the aggregate that produced this event
                     * @param payload     the event payload object — will be JSON-serialized
                     */
                    public void publish(String eventType, String aggregateId, Object payload) {
                        OutboxEvent event = new OutboxEvent();
                        event.setEventType(eventType);
                        event.setAggregateId(aggregateId);
                        // Capture correlationId while still in the HTTP thread — MDC is populated here.
                        // The OutboxPoller runs on a @Scheduled thread with an empty MDC, so we must
                        // persist the ID now and read it from the entity later.
                        String correlationId = MDC.get("correlationId");
                        if (correlationId == null) correlationId = MDC.get("traceId");
                        event.setCorrelationId(correlationId);
                        try {
                            event.setPayload(objectMapper.writeValueAsString(payload));
                        } catch (JsonProcessingException e) {
                            log.warn("Failed to serialize payload for event '{}'; storing raw toString", eventType);
                            event.setPayload(String.valueOf(payload));
                        }
                        outboxRepository.save(event);
                        log.debug("Outbox event queued: type={} aggregateId={} correlationId={}",
                                eventType, aggregateId, correlationId);
                    }
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxPoller
    // -------------------------------------------------------------------------

    private String buildOutboxPoller(FractalModule module, String pkg) {
        return """
                package %s;

                import org.slf4j.Logger;
                import org.slf4j.LoggerFactory;
                import org.springframework.beans.factory.annotation.Value;
                import org.springframework.http.HttpEntity;
                import org.springframework.http.HttpHeaders;
                import org.springframework.scheduling.annotation.Scheduled;
                import org.springframework.stereotype.Component;
                import org.springframework.transaction.annotation.Transactional;
                import org.springframework.web.client.RestTemplate;
                import java.time.LocalDateTime;
                import java.util.List;

                /**
                 * Polls the transactional outbox for unpublished events and forwards them
                 * to the FractalX saga orchestrator (http://localhost:8099 by default).
                 *
                 * <p>Runs every second. Retries are capped at {@link #MAX_RETRIES};
                 * events that exceed the cap are left as unpublished for manual inspection.
                 *
                 * Auto-generated by FractalX — service: %s.
                 */
                @Component
                public class OutboxPoller {

                    private static final Logger log        = LoggerFactory.getLogger(OutboxPoller.class);
                    private static final int    MAX_RETRIES = 5;

                    private final OutboxRepository outboxRepository;
                    private final RestTemplate     restTemplate;

                    @Value("${fractalx.saga.orchestrator.url:http://localhost:8099}")
                    private String orchestratorUrl;

                    public OutboxPoller(OutboxRepository outboxRepository) {
                        this.outboxRepository = outboxRepository;
                        this.restTemplate     = new RestTemplate();
                    }

                    @Scheduled(fixedDelay = 1000)
                    @Transactional
                    public void publishPending() {
                        List<OutboxEvent> pending =
                                outboxRepository.findByPublishedFalseOrderByCreatedAtAsc();

                        if (pending.isEmpty()) return;

                        for (OutboxEvent event : pending) {
                            if (event.getRetryCount() >= MAX_RETRIES) {
                                log.error("Outbox event {} exceeded max retries ({}) — manual intervention required",
                                        event.getId(), MAX_RETRIES);
                                continue;
                            }

                            try {
                                forwardEvent(event);
                                event.setPublished(true);
                                event.setPublishedAt(LocalDateTime.now());
                                log.info("Forwarded outbox event id={} type={} aggregateId={}",
                                        event.getId(), event.getEventType(), event.getAggregateId());
                            } catch (Exception e) {
                                event.setRetryCount(event.getRetryCount() + 1);
                                log.warn("Failed to forward outbox event id={} type={} attempt={}: {}",
                                        event.getId(), event.getEventType(), event.getRetryCount(), e.getMessage());
                            }
                        }
                    }

                    /**
                     * Forwards a single outbox event to the saga orchestrator via HTTP POST.
                     * The URL follows the pattern: {orchestratorUrl}/saga/{eventType}/start
                     * where eventType is the saga ID (e.g., "place-order-saga").
                     *
                     * <p>The original correlationId is forwarded as {@code X-Correlation-Id} so
                     * the saga orchestrator and all downstream services share the same trace ID.
                     */
                    protected void forwardEvent(OutboxEvent event) {
                        String url = orchestratorUrl + "/saga/" + event.getEventType() + "/start";
                        HttpHeaders headers = new HttpHeaders();
                        headers.set("Content-Type", "application/json");
                        if (event.getCorrelationId() != null && !event.getCorrelationId().isBlank()) {
                            headers.set("X-Correlation-Id", event.getCorrelationId());
                        }
                        HttpEntity<String> request = new HttpEntity<>(event.getPayload(), headers);
                        restTemplate.postForObject(url, request, String.class);
                        log.debug("Dispatched saga event id={} type={} correlationId={} to {}",
                                event.getId(), event.getEventType(), event.getCorrelationId(), url);
                    }
                }
                """.formatted(pkg, module.getServiceName());
    }

    // -------------------------------------------------------------------------
    // Utilities
    // -------------------------------------------------------------------------

    private Path createPackagePath(Path root, String packageName) throws IOException {
        Path path = root;
        for (String part : packageName.split("\\.")) {
            path = path.resolve(part);
        }
        Files.createDirectories(path);
        return path;
    }

    private void writeFile(Path dir, String filename, String content) throws IOException {
        Files.writeString(dir.resolve(filename), content);
    }
}
