package org.fractalx.core.datamanagement;

import org.fractalx.core.model.FractalModule;
import org.fractalx.core.model.SagaDefinition;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates the transactional outbox pattern for services that participate in
 * distributed sagas or have cross-module dependencies.
 *
 * <p>The outbox pattern solves the dual-write problem: business state and the
 * intent to notify other services are written atomically in the same local
 * transaction. A scheduled poller then reads unpublished events and forwards
 * them — guaranteed at-least-once delivery without a message broker.
 *
 * <p>Generated files per service:
 * <ul>
 *   <li>{@code OutboxEvent.java} — JPA entity stored in {@code fractalx_outbox}</li>
 *   <li>{@code OutboxRepository.java} — Spring Data repository</li>
 *   <li>{@code OutboxPublisher.java} — bean used inside business {@code @Transactional} methods</li>
 *   <li>{@code OutboxPoller.java} — scheduled publisher that forwards pending events to saga orchestrator</li>
 *   <li>{@code SagaOutboxAspect.java} — AOP aspect that auto-publishes to outbox after each saga method (saga-owning services only)</li>
 * </ul>
 */
public class OutboxGenerator {

    private static final Logger log = LoggerFactory.getLogger(OutboxGenerator.class);

    public void generateOutbox(FractalModule module, Path serviceRoot,
                               List<SagaDefinition> sagaDefinitions, String basePackage) throws IOException {
        String outboxPackage = basePackage + ".outbox";

        Path outboxPath = createPackagePath(serviceRoot.resolve("src/main/java"), outboxPackage);

        writeFile(outboxPath, "OutboxEvent.java",         buildOutboxEvent(outboxPackage));
        writeFile(outboxPath, "OutboxRepository.java",    buildOutboxRepository(outboxPackage));
        writeFile(outboxPath, "OutboxDlqEvent.java",      buildOutboxDlqEvent(outboxPackage));
        writeFile(outboxPath, "OutboxDlqRepository.java", buildOutboxDlqRepository(outboxPackage));
        writeFile(outboxPath, "OutboxEventReady.java",    buildOutboxEventReady(outboxPackage));
        writeFile(outboxPath, "OutboxPublisher.java",     buildOutboxPublisher(outboxPackage));
        writeFile(outboxPath, "OutboxPoller.java",        buildOutboxPoller(module, outboxPackage));

        log.info("Generated transactional outbox for: {}", module.getServiceName());
    }

    // -------------------------------------------------------------------------
    // OutboxEvent
    // -------------------------------------------------------------------------

    private String buildOutboxEvent(String pkg) {
        return """
                package %s;

                import jakarta.persistence.*;
                import java.time.LocalDateTime;

                /**
                 * Transactional outbox event — written atomically with business state.
                 * Auto-generated by FractalX.
                 */
                @Entity
                @Table(name = "fractalx_outbox",
                       indexes = @Index(name = "idx_outbox_unpublished",
                                        columnList = "published, createdAt"))
                public class OutboxEvent {

                    @Id
                    @GeneratedValue(strategy = GenerationType.IDENTITY)
                    private Long id;

                    /** Logical event type — matches a saga ID (e.g., "place-order-saga"). */
                    @Column(nullable = false)
                    private String eventType;

                    /** ID of the aggregate that produced this event. */
                    @Column(nullable = false)
                    private String aggregateId;

                    /** JSON-serialized event payload. */
                    @Column(columnDefinition = "TEXT")
                    private String payload;

                    /**
                     * Correlation ID from the originating HTTP request.
                     * Captured while still in the HTTP thread (MDC is populated) so it
                     * can be forwarded even when the OutboxPoller runs on a scheduler thread.
                     */
                    @Column
                    private String correlationId;

                    /**
                     * W3C traceparent header value captured from the active OTel span
                     * at publish time. Forwarded as the {@code traceparent} HTTP header
                     * so the saga-orchestrator's span appears as a child of the original
                     * request trace in Jaeger. Format: {@code 00-{traceId}-{spanId}-01}.
                     */
                    @Column(length = 55)
                    private String traceparent;

                    /** Whether this event has been successfully forwarded. */
                    @Column(nullable = false)
                    private boolean published = false;

                    /** How many times publishing has been attempted. */
                    @Column(nullable = false)
                    private int retryCount = 0;

                    @Column(nullable = false)
                    private LocalDateTime createdAt;

                    private LocalDateTime publishedAt;

                    @PrePersist
                    protected void onCreate() { createdAt = LocalDateTime.now(); }

                    public Long getId()                  { return id; }
                    public String getEventType()         { return eventType; }
                    public void setEventType(String v)   { eventType = v; }
                    public String getAggregateId()       { return aggregateId; }
                    public void setAggregateId(String v) { aggregateId = v; }
                    public String getPayload()           { return payload; }
                    public void setPayload(String v)     { payload = v; }
                    public String getCorrelationId()     { return correlationId; }
                    public void setCorrelationId(String v) { correlationId = v; }
                    public String getTraceparent()       { return traceparent; }
                    public void setTraceparent(String v) { traceparent = v; }
                    public boolean isPublished()         { return published; }
                    public void setPublished(boolean v)  { published = v; }
                    public int getRetryCount()           { return retryCount; }
                    public void setRetryCount(int v)     { retryCount = v; }
                    public LocalDateTime getCreatedAt()  { return createdAt; }
                    public LocalDateTime getPublishedAt(){ return publishedAt; }
                    public void setPublishedAt(LocalDateTime v) { publishedAt = v; }
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxRepository
    // -------------------------------------------------------------------------

    private String buildOutboxRepository(String pkg) {
        return """
                package %s;

                import org.springframework.data.jpa.repository.JpaRepository;
                import java.util.List;

                /**
                 * Repository for transactional outbox events.
                 * Auto-generated by FractalX.
                 */
                public interface OutboxRepository extends JpaRepository<OutboxEvent, Long> {

                    /** Returns unpublished events ordered by creation time (oldest first). */
                    List<OutboxEvent> findByPublishedFalseOrderByCreatedAtAsc();

                    /** Returns events that failed more than {@code maxRetries} times. */
                    List<OutboxEvent> findByPublishedFalseAndRetryCountGreaterThan(int maxRetries);
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxDlqEvent
    // -------------------------------------------------------------------------

    private String buildOutboxDlqEvent(String pkg) {
        return """
                package %s;

                import jakarta.persistence.*;
                import java.time.LocalDateTime;

                /**
                 * Dead-letter queue entry for outbox events that exceeded the maximum retry count.
                 * Monitor this table to detect and investigate persistent saga failures.
                 * Auto-generated by FractalX.
                 */
                @Entity
                @Table(name = "fractalx_outbox_dlq")
                public class OutboxDlqEvent {

                    @Id
                    @GeneratedValue(strategy = GenerationType.IDENTITY)
                    private Long id;

                    /** ID of the original OutboxEvent that failed permanently. */
                    private Long originalEventId;

                    @Column
                    private String eventType;

                    @Column
                    private String aggregateId;

                    @Column(columnDefinition = "TEXT")
                    private String payload;

                    @Column
                    private String correlationId;

                    @Column(length = 500)
                    private String failedReason;

                    @Column(nullable = false)
                    private LocalDateTime failedAt;

                    @PrePersist
                    protected void onCreate() { failedAt = LocalDateTime.now(); }

                    public OutboxDlqEvent() {}

                    public OutboxDlqEvent(OutboxEvent original, String reason) {
                        this.originalEventId = original.getId();
                        this.eventType       = original.getEventType();
                        this.aggregateId     = original.getAggregateId();
                        this.payload         = original.getPayload();
                        this.correlationId   = original.getCorrelationId();
                        this.failedReason    = reason;
                    }

                    public Long getId()              { return id; }
                    public Long getOriginalEventId() { return originalEventId; }
                    public String getEventType()     { return eventType; }
                    public String getAggregateId()   { return aggregateId; }
                    public String getPayload()       { return payload; }
                    public String getCorrelationId() { return correlationId; }
                    public String getFailedReason()  { return failedReason; }
                    public LocalDateTime getFailedAt(){ return failedAt; }
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxDlqRepository
    // -------------------------------------------------------------------------

    private String buildOutboxDlqRepository(String pkg) {
        return """
                package %s;

                import org.springframework.data.jpa.repository.JpaRepository;

                /**
                 * Repository for outbox dead-letter queue entries.
                 * Monitor {@code fractalx_outbox_dlq} to detect persistent saga failures.
                 * Auto-generated by FractalX.
                 */
                public interface OutboxDlqRepository extends JpaRepository<OutboxDlqEvent, Long> {
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxEventReady
    // -------------------------------------------------------------------------

    private String buildOutboxEventReady(String pkg) {
        return """
                package %s;

                import org.springframework.context.ApplicationEvent;

                /**
                 * Signals that a new outbox event has been persisted and the enclosing
                 * transaction has committed. Listeners should attempt immediate delivery.
                 * Auto-generated by FractalX.
                 */
                public class OutboxEventReady extends ApplicationEvent {
                    public OutboxEventReady(Object source) {
                        super(source);
                    }
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxPublisher
    // -------------------------------------------------------------------------

    private String buildOutboxPublisher(String pkg) {
        return """
                package %s;

                import com.fasterxml.jackson.core.JsonProcessingException;
                import com.fasterxml.jackson.databind.ObjectMapper;
                import io.micrometer.tracing.Tracer;
                import org.slf4j.Logger;
                import org.slf4j.LoggerFactory;
                import org.slf4j.MDC;
                import org.springframework.context.ApplicationEventPublisher;
                import org.springframework.stereotype.Component;
                import org.springframework.transaction.support.TransactionSynchronization;
                import org.springframework.transaction.support.TransactionSynchronizationManager;

                /**
                 * Publishes business events to the transactional outbox.
                 *
                 * <p>Must be called inside an active {@code @Transactional} method so the
                 * outbox record is written atomically with the business state change.
                 * After the transaction commits, an {@link OutboxEventReady} event is fired
                 * to trigger immediate delivery — eliminating the polling latency floor.
                 * Auto-generated by FractalX — called automatically by the saga method transformer.
                 */
                @Component
                public class OutboxPublisher {

                    private static final Logger log = LoggerFactory.getLogger(OutboxPublisher.class);

                    private final OutboxRepository         outboxRepository;
                    private final ObjectMapper             objectMapper;
                    private final Tracer                   tracer;
                    private final ApplicationEventPublisher eventPublisher;

                    public OutboxPublisher(OutboxRepository outboxRepository,
                                           ObjectMapper objectMapper,
                                           Tracer tracer,
                                           ApplicationEventPublisher eventPublisher) {
                        this.outboxRepository = outboxRepository;
                        this.objectMapper     = objectMapper;
                        this.tracer           = tracer;
                        this.eventPublisher   = eventPublisher;
                    }

                    /**
                     * Writes an outbox record for the given event.
                     *
                     * @param eventType   saga ID (e.g., "place-order-saga")
                     * @param aggregateId ID of the aggregate that produced this event
                     * @param payload     the event payload object — will be JSON-serialized
                     */
                    public void publish(String eventType, String aggregateId, Object payload) {
                        OutboxEvent event = new OutboxEvent();
                        event.setEventType(eventType);
                        event.setAggregateId(aggregateId);

                        // Capture correlationId while still in the HTTP thread — MDC is populated here.
                        // The OutboxPoller runs on a @Scheduled thread with an empty MDC, so we must
                        // persist the ID now and read it from the entity later.
                        String correlationId = MDC.get("correlationId");
                        if (correlationId == null) correlationId = MDC.get("traceId");
                        event.setCorrelationId(correlationId);

                        // Capture W3C traceparent from the active OTel span so the outbox poller
                        // can forward it as an HTTP header. This links the saga-orchestrator's
                        // span to the original request trace in Jaeger.
                        try {
                            io.micrometer.tracing.Span curSpan = tracer.currentSpan();
                            if (curSpan != null) {
                                io.micrometer.tracing.TraceContext tc = curSpan.context();
                                if (tc != null && tc.traceId() != null && tc.spanId() != null) {
                                    event.setTraceparent("00-" + tc.traceId() + "-" + tc.spanId() + "-01");
                                }
                            }
                        } catch (Exception ignored) {}

                        try {
                            event.setPayload(objectMapper.writeValueAsString(payload));
                        } catch (JsonProcessingException e) {
                            log.warn("Failed to serialize payload for event '{}'; storing raw toString", eventType);
                            event.setPayload(String.valueOf(payload));
                        }
                        outboxRepository.save(event);
                        log.debug("Outbox event queued: type={} aggregateId={} correlationId={} traceparent={}",
                                eventType, aggregateId, correlationId, event.getTraceparent());

                        // Fire OutboxEventReady AFTER the enclosing transaction commits,
                        // so the poller can read the just-persisted event immediately.
                        if (TransactionSynchronizationManager.isSynchronizationActive()) {
                            TransactionSynchronizationManager.registerSynchronization(
                                    new TransactionSynchronization() {
                                        @Override
                                        public void afterCommit() {
                                            eventPublisher.publishEvent(new OutboxEventReady(this));
                                        }
                                    });
                        }
                    }
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxPoller
    // -------------------------------------------------------------------------

    private String buildOutboxPoller(FractalModule module, String pkg) {
        return """
                package %s;

                import org.slf4j.Logger;
                import org.slf4j.LoggerFactory;
                import org.springframework.beans.factory.annotation.Value;
                import org.springframework.http.HttpEntity;
                import org.springframework.http.HttpHeaders;
                import org.springframework.scheduling.annotation.Scheduled;
                import org.springframework.stereotype.Component;
                import org.springframework.transaction.annotation.Transactional;
                import org.springframework.web.client.RestTemplate;
                import java.time.LocalDateTime;
                import java.util.List;

                /**
                 * Polls the transactional outbox for unpublished events and forwards them
                 * to the FractalX saga orchestrator.
                 *
                 * <p>Retries are capped at {@code fractalx.outbox.max-retries} (default 5);
                 * events that exceed the cap are moved to the dead-letter queue
                 * ({@code fractalx_outbox_dlq}) for manual investigation rather than
                 * being left in the outbox table indefinitely.
                 *
                 * <p>Configure the orchestrator URL via:
                 * {@code fractalx.saga.orchestrator.url} (default: {@code http://localhost:8099}).
                 *
                 * Auto-generated by FractalX — service: %s.
                 */
                @Component
                public class OutboxPoller implements org.springframework.context.ApplicationListener<OutboxEventReady> {

                    private static final Logger log = LoggerFactory.getLogger(OutboxPoller.class);

                    private final OutboxRepository    outboxRepository;
                    private final OutboxDlqRepository dlqRepository;
                    private final RestTemplate        restTemplate;

                    @Value("${fractalx.saga.orchestrator.url:http://localhost:8099}")
                    private String orchestratorUrl;

                    @Value("${fractalx.outbox.max-retries:5}")
                    private int maxRetries;

                    public OutboxPoller(OutboxRepository outboxRepository,
                                        OutboxDlqRepository dlqRepository) {
                        this.outboxRepository = outboxRepository;
                        this.dlqRepository    = dlqRepository;
                        this.restTemplate     = new RestTemplate();
                    }

                    @Override
                    public void onApplicationEvent(OutboxEventReady event) {
                        publishPending();
                    }

                    @Scheduled(fixedDelayString = "${fractalx.outbox.poll-interval-ms:10000}")
                    @Transactional
                    public void publishPending() {
                        List<OutboxEvent> pending =
                                outboxRepository.findByPublishedFalseOrderByCreatedAtAsc();

                        if (pending.isEmpty()) return;

                        for (OutboxEvent event : pending) {
                            if (event.getRetryCount() >= maxRetries) {
                                // Move to DLQ — do not leave permanently in the outbox table
                                OutboxDlqEvent dlqEvent = new OutboxDlqEvent(event, "MAX_RETRIES_EXCEEDED");
                                dlqRepository.save(dlqEvent);
                                outboxRepository.delete(event);
                                log.error("Outbox event id={} type={} moved to DLQ after {} retries — " +
                                          "check fractalx_outbox_dlq for manual reprocessing",
                                        event.getId(), event.getEventType(), maxRetries);
                                continue;
                            }

                            try {
                                forwardEvent(event);
                                event.setPublished(true);
                                event.setPublishedAt(LocalDateTime.now());
                                log.info("Forwarded outbox event id={} type={} aggregateId={}",
                                        event.getId(), event.getEventType(), event.getAggregateId());
                            } catch (Exception e) {
                                event.setRetryCount(event.getRetryCount() + 1);
                                log.warn("Failed to forward outbox event id={} type={} attempt={}: {}",
                                        event.getId(), event.getEventType(), event.getRetryCount(), e.getMessage());
                            }
                        }
                    }

                    /**
                     * Forwards a single outbox event to the saga orchestrator via HTTP POST.
                     * The URL follows the pattern: {orchestratorUrl}/saga/{eventType}/start
                     * where eventType is the saga ID (e.g., "place-order-saga").
                     *
                     * <p>The original correlationId is forwarded as {@code X-Correlation-Id} so
                     * the saga orchestrator and all downstream services share the same trace ID.
                     */
                    protected void forwardEvent(OutboxEvent event) {
                        String url = orchestratorUrl + "/saga/" + event.getEventType() + "/start";
                        HttpHeaders headers = new HttpHeaders();
                        headers.set("Content-Type", "application/json");
                        if (event.getCorrelationId() != null && !event.getCorrelationId().isBlank()) {
                            headers.set("X-Correlation-Id", event.getCorrelationId());
                        }
                        // Forward W3C traceparent so the saga-orchestrator creates a child span
                        // under the original request trace, connecting it in Jaeger.
                        if (event.getTraceparent() != null && !event.getTraceparent().isBlank()) {
                            headers.set("traceparent", event.getTraceparent());
                        }
                        HttpEntity<String> request = new HttpEntity<>(event.getPayload(), headers);
                        restTemplate.postForObject(url, request, String.class);
                        log.debug("Dispatched saga event id={} type={} correlationId={} traceparent={} to {}",
                                event.getId(), event.getEventType(), event.getCorrelationId(),
                                event.getTraceparent(), url);
                    }
                }
                """.formatted(pkg, module.getServiceName());
    }

    // -------------------------------------------------------------------------
    // Utilities
    // -------------------------------------------------------------------------

    private Path createPackagePath(Path root, String packageName) throws IOException {
        Path path = root;
        for (String part : packageName.split("\\.")) {
            path = path.resolve(part);
        }
        Files.createDirectories(path);
        return path;
    }

    private void writeFile(Path dir, String filename, String content) throws IOException {
        Files.writeString(dir.resolve(filename), content);
    }
}
