package org.fractalx.core.datamanagement;

import org.fractalx.core.model.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates the transactional outbox pattern for services that participate in
 * distributed sagas or have cross-module dependencies.
 *
 * <p>The outbox pattern solves the dual-write problem: business state and the
 * intent to notify other services are written atomically in the same local
 * transaction. A scheduled poller then reads unpublished events and forwards
 * them — guaranteed at-least-once delivery without a message broker.
 *
 * <p>Generated files per service:
 * <ul>
 *   <li>{@code OutboxEvent.java} — JPA entity stored in {@code fractalx_outbox}</li>
 *   <li>{@code OutboxRepository.java} — Spring Data repository</li>
 *   <li>{@code OutboxPublisher.java} — bean used inside business {@code @Transactional} methods</li>
 *   <li>{@code OutboxPoller.java} — scheduled publisher that forwards pending events</li>
 * </ul>
 */
public class OutboxGenerator {

    private static final Logger log = LoggerFactory.getLogger(OutboxGenerator.class);

    public void generateOutbox(FractalModule module, Path serviceRoot) throws IOException {
        String basePackage    = "org.fractalx.generated." + module.getServiceName().replace("-", "");
        String outboxPackage  = basePackage + ".outbox";

        Path outboxPath = createPackagePath(serviceRoot.resolve("src/main/java"), outboxPackage);

        writeFile(outboxPath, "OutboxEvent.java",     buildOutboxEvent(outboxPackage));
        writeFile(outboxPath, "OutboxRepository.java", buildOutboxRepository(outboxPackage));
        writeFile(outboxPath, "OutboxPublisher.java",  buildOutboxPublisher(outboxPackage));
        writeFile(outboxPath, "OutboxPoller.java",     buildOutboxPoller(module, outboxPackage));

        log.info("Generated transactional outbox for: {}", module.getServiceName());
    }

    // -------------------------------------------------------------------------
    // OutboxEvent
    // -------------------------------------------------------------------------

    private String buildOutboxEvent(String pkg) {
        return """
                package %s;

                import jakarta.persistence.*;
                import java.time.LocalDateTime;

                /**
                 * Transactional outbox event — written atomically with business state.
                 * Auto-generated by FractalX.
                 */
                @Entity
                @Table(name = "fractalx_outbox",
                       indexes = @Index(name = "idx_outbox_unpublished",
                                        columnList = "published, createdAt"))
                public class OutboxEvent {

                    @Id
                    @GeneratedValue(strategy = GenerationType.IDENTITY)
                    private Long id;

                    /** Logical event type (e.g., "OrderCreated", "PaymentProcessed"). */
                    @Column(nullable = false)
                    private String eventType;

                    /** ID of the aggregate that produced this event. */
                    @Column(nullable = false)
                    private String aggregateId;

                    /** JSON-serialized event payload. */
                    @Column(columnDefinition = "TEXT")
                    private String payload;

                    /** Whether this event has been successfully forwarded. */
                    @Column(nullable = false)
                    private boolean published = false;

                    /** How many times publishing has been attempted. */
                    @Column(nullable = false)
                    private int retryCount = 0;

                    @Column(nullable = false)
                    private LocalDateTime createdAt;

                    private LocalDateTime publishedAt;

                    @PrePersist
                    protected void onCreate() { createdAt = LocalDateTime.now(); }

                    public Long getId()                  { return id; }
                    public String getEventType()         { return eventType; }
                    public void setEventType(String v)   { eventType = v; }
                    public String getAggregateId()       { return aggregateId; }
                    public void setAggregateId(String v) { aggregateId = v; }
                    public String getPayload()           { return payload; }
                    public void setPayload(String v)     { payload = v; }
                    public boolean isPublished()         { return published; }
                    public void setPublished(boolean v)  { published = v; }
                    public int getRetryCount()           { return retryCount; }
                    public void setRetryCount(int v)     { retryCount = v; }
                    public LocalDateTime getCreatedAt()  { return createdAt; }
                    public LocalDateTime getPublishedAt(){ return publishedAt; }
                    public void setPublishedAt(LocalDateTime v) { publishedAt = v; }
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxRepository
    // -------------------------------------------------------------------------

    private String buildOutboxRepository(String pkg) {
        return """
                package %s;

                import org.springframework.data.jpa.repository.JpaRepository;
                import java.util.List;

                /**
                 * Repository for transactional outbox events.
                 * Auto-generated by FractalX.
                 */
                public interface OutboxRepository extends JpaRepository<OutboxEvent, Long> {

                    /** Returns unpublished events ordered by creation time (oldest first). */
                    List<OutboxEvent> findByPublishedFalseOrderByCreatedAtAsc();

                    /** Returns events that failed more than {@code maxRetries} times. */
                    List<OutboxEvent> findByPublishedFalseAndRetryCountGreaterThan(int maxRetries);
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxPublisher
    // -------------------------------------------------------------------------

    private String buildOutboxPublisher(String pkg) {
        return """
                package %s;

                import com.fasterxml.jackson.core.JsonProcessingException;
                import com.fasterxml.jackson.databind.ObjectMapper;
                import org.slf4j.Logger;
                import org.slf4j.LoggerFactory;
                import org.springframework.stereotype.Component;

                /**
                 * Publishes business events to the transactional outbox.
                 *
                 * <p>Must be called inside an active {@code @Transactional} method so the
                 * outbox record is written atomically with the business state change.
                 *
                 * <pre>
                 * // Example usage inside a @Transactional service method:
                 * orderRepository.save(order);
                 * outboxPublisher.publish("OrderCreated", order.getId().toString(), order);
                 * </pre>
                 *
                 * Auto-generated by FractalX.
                 */
                @Component
                public class OutboxPublisher {

                    private static final Logger log = LoggerFactory.getLogger(OutboxPublisher.class);

                    private final OutboxRepository outboxRepository;
                    private final ObjectMapper     objectMapper;

                    public OutboxPublisher(OutboxRepository outboxRepository, ObjectMapper objectMapper) {
                        this.outboxRepository = outboxRepository;
                        this.objectMapper     = objectMapper;
                    }

                    /**
                     * Writes an outbox record for the given event.
                     *
                     * @param eventType   logical event name (e.g., "OrderCreated")
                     * @param aggregateId ID of the aggregate that produced this event
                     * @param payload     the event payload object — will be JSON-serialized
                     */
                    public void publish(String eventType, String aggregateId, Object payload) {
                        OutboxEvent event = new OutboxEvent();
                        event.setEventType(eventType);
                        event.setAggregateId(aggregateId);
                        try {
                            event.setPayload(objectMapper.writeValueAsString(payload));
                        } catch (JsonProcessingException e) {
                            log.warn("Failed to serialize payload for event '{}'; storing raw toString", eventType);
                            event.setPayload(String.valueOf(payload));
                        }
                        outboxRepository.save(event);
                        log.debug("Outbox event queued: type={} aggregateId={}", eventType, aggregateId);
                    }
                }
                """.formatted(pkg);
    }

    // -------------------------------------------------------------------------
    // OutboxPoller
    // -------------------------------------------------------------------------

    private String buildOutboxPoller(FractalModule module, String pkg) {
        return """
                package %s;

                import org.slf4j.Logger;
                import org.slf4j.LoggerFactory;
                import org.springframework.scheduling.annotation.Scheduled;
                import org.springframework.stereotype.Component;
                import org.springframework.transaction.annotation.Transactional;
                import java.time.LocalDateTime;
                import java.util.List;

                /**
                 * Polls the transactional outbox for unpublished events and forwards them.
                 *
                 * <p>Runs every second by default. Retries are capped at {@link #MAX_RETRIES};
                 * events that exceed the cap are left as unpublished for manual inspection.
                 *
                 * <p>To integrate with the saga orchestrator or another consumer, inject the
                 * appropriate NetScope client and call it in {@code forwardEvent()}.
                 *
                 * Auto-generated by FractalX — service: %s.
                 */
                @Component
                public class OutboxPoller {

                    private static final Logger log   = LoggerFactory.getLogger(OutboxPoller.class);
                    private static final int MAX_RETRIES = 5;

                    private final OutboxRepository outboxRepository;

                    public OutboxPoller(OutboxRepository outboxRepository) {
                        this.outboxRepository = outboxRepository;
                    }

                    @Scheduled(fixedDelay = 1000)
                    @Transactional
                    public void publishPending() {
                        List<OutboxEvent> pending =
                                outboxRepository.findByPublishedFalseOrderByCreatedAtAsc();

                        if (pending.isEmpty()) return;

                        for (OutboxEvent event : pending) {
                            if (event.getRetryCount() >= MAX_RETRIES) {
                                log.error("Outbox event {} exceeded max retries ({}) — manual intervention required",
                                        event.getId(), MAX_RETRIES);
                                continue;
                            }

                            try {
                                forwardEvent(event);
                                event.setPublished(true);
                                event.setPublishedAt(LocalDateTime.now());
                                log.debug("Published outbox event id={} type={}", event.getId(), event.getEventType());
                            } catch (Exception e) {
                                event.setRetryCount(event.getRetryCount() + 1);
                                log.warn("Failed to publish outbox event id={} type={} attempt={}: {}",
                                        event.getId(), event.getEventType(), event.getRetryCount(), e.getMessage());
                            }
                        }
                    }

                    /**
                     * Forwards a single outbox event to its consumer(s).
                     *
                     * <p>TODO: Inject the saga orchestrator NetScope client (or HTTP client)
                     * and call the appropriate endpoint based on {@code event.getEventType()}.
                     *
                     * <pre>
                     * Example:
                     *   sagaOrchestratorClient.notify(event.getEventType(),
                     *                                  event.getAggregateId(),
                     *                                  event.getPayload());
                     * </pre>
                     */
                    protected void forwardEvent(OutboxEvent event) {
                        // TODO: implement event forwarding — inject the consumer client
                        log.debug("forwardEvent called for type={} aggregateId={}",
                                event.getEventType(), event.getAggregateId());
                    }
                }
                """.formatted(pkg, module.getServiceName());
    }

    // -------------------------------------------------------------------------
    // Utilities
    // -------------------------------------------------------------------------

    private Path createPackagePath(Path root, String packageName) throws IOException {
        Path path = root;
        for (String part : packageName.split("\\.")) {
            path = path.resolve(part);
        }
        Files.createDirectories(path);
        return path;
    }

    private void writeFile(Path dir, String filename, String content) throws IOException {
        Files.writeString(dir.resolve(filename), content);
    }
}
