package org.fractalx.core.gateway;

import org.fractalx.core.auth.AuthPattern;
import org.fractalx.core.model.FractalModule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Generates an OpenAPI 3.0.3 specification (openapi.yaml) for all services
 * routed through the FractalX API Gateway.
 *
 * <p>The file is written to {@code fractalx-gateway/docs/} and can be imported
 * directly into Swagger UI or any OpenAPI-compatible tooling.
 *
 * <p>Endpoints are derived from actual controller annotations in the monolith
 * source (package = module boundary), so cross-resource routes
 * (e.g. {@code GET /api/customers/{id}/orders} owned by order-service) appear
 * in the correct service tag. Only endpoints that existed in the monolith's
 * controllers are exposed — no synthetic CRUD defaults are generated.
 */
public class GatewayOpenApiGenerator {

    private static final Logger log = LoggerFactory.getLogger(GatewayOpenApiGenerator.class);
    private static final int GATEWAY_PORT = 9999;

    private final ControllerPathScanner scanner = new ControllerPathScanner();

    public void generate(Path gatewayRoot, List<FractalModule> modules) throws IOException {
        generate(gatewayRoot, modules, AuthPattern.none(), null);
    }

    public void generate(Path gatewayRoot, List<FractalModule> modules, AuthPattern authPattern) throws IOException {
        generate(gatewayRoot, modules, authPattern, null);
    }

    /**
     * Generates documentation using actual controller paths from the monolith source.
     *
     * @param monolithSrc path to the monolith's {@code src/main/java}; when {@code null}
     *                    or when no endpoints are found, no service paths are emitted
     */
    public void generate(Path gatewayRoot, List<FractalModule> modules,
                         AuthPattern authPattern, Path monolithSrc) throws IOException {
        Path docsDir = gatewayRoot.resolve("docs");
        Files.createDirectories(docsDir);

        Map<FractalModule, Set<ControllerPathScanner.EndpointInfo>> scanned =
                scanAll(modules, monolithSrc);

        Files.writeString(docsDir.resolve("openapi.yaml"),
                buildOpenApi(modules, authPattern, scanned));

        log.info("Generated openapi.yaml for {} services", modules.size());
    }

    // ── Controller scanning ───────────────────────────────────────────────────

    private Map<FractalModule, Set<ControllerPathScanner.EndpointInfo>> scanAll(
            List<FractalModule> modules, Path monolithSrc) {
        Map<FractalModule, Set<ControllerPathScanner.EndpointInfo>> result = new LinkedHashMap<>();
        if (monolithSrc == null) return result;
        for (FractalModule m : modules) {
            Set<ControllerPathScanner.EndpointInfo> endpoints = scanner.scan(monolithSrc, m);
            if (!endpoints.isEmpty()) {
                result.put(m, endpoints);
                log.debug("Scanned {} endpoints for {}", endpoints.size(), m.getServiceName());
            }
        }
        return result;
    }

    // -------------------------------------------------------------------------
    // OpenAPI 3.0.3
    // -------------------------------------------------------------------------

    private String buildOpenApi(List<FractalModule> modules, AuthPattern authPattern,
                                Map<FractalModule, Set<ControllerPathScanner.EndpointInfo>> scanned) {
        StringBuilder sb = new StringBuilder();

        sb.append("openapi: \"3.0.3\"\n");
        sb.append("info:\n");
        sb.append("  title: \"FractalX Generated API\"\n");
        sb.append("  version: \"1.0.0\"\n");
        sb.append("  description: |\n");
        sb.append("    Auto-generated by FractalX decomposition framework.\n");
        sb.append("    All routes are proxied through the API Gateway on port ")
          .append(GATEWAY_PORT).append(".\n");

        sb.append("servers:\n");
        sb.append("  - url: \"http://localhost:").append(GATEWAY_PORT).append("\"\n");
        sb.append("    description: \"API Gateway\"\n");
        if (authPattern.detected()) {
            sb.append("  - url: \"http://localhost:8090\"\n");
            sb.append("    description: \"auth-service (direct)\"\n");
        }
        for (FractalModule m : modules) {
            sb.append("  - url: \"http://localhost:").append(m.getPort()).append("\"\n");
            sb.append("    description: \"").append(displayName(m)).append(" (direct)\"\n");
        }

        sb.append("tags:\n");
        if (authPattern.detected()) {
            sb.append("  - name: \"auth-service\"\n");
            sb.append("    description: \"Authentication — login and registration\"\n");
        }
        for (FractalModule m : modules) {
            sb.append("  - name: \"").append(m.getServiceName()).append("\"\n");
            sb.append("    description: \"").append(displayName(m)).append(" API\"\n");
        }
        sb.append("  - name: \"gateway\"\n");
        sb.append("    description: \"Gateway management endpoints\"\n");

        sb.append("paths:\n");
        if (authPattern.detected()) {
            appendAuthPaths(sb);
        }
        for (FractalModule m : modules) {
            Set<ControllerPathScanner.EndpointInfo> endpoints = scanned.get(m);
            if (endpoints != null && !endpoints.isEmpty()) {
                appendScannedServicePaths(sb, m, endpoints);
            }
        }
        appendGatewayHealthPath(sb);

        appendComponents(sb);
        return sb.toString();
    }

    /**
     * Emits OpenAPI path entries derived from actual scanned controller endpoints.
     * Paths with the same URL but different HTTP methods are merged under one path key.
     */
    private void appendScannedServicePaths(StringBuilder sb, FractalModule m,
                                            Set<ControllerPathScanner.EndpointInfo> endpoints) {
        String tag   = m.getServiceName();
        String opPfx = m.getServiceName();

        // Group by path — preserve insertion order (LinkedHashMap)
        Map<String, Set<ControllerPathScanner.EndpointInfo>> byPath = new LinkedHashMap<>();
        for (ControllerPathScanner.EndpointInfo ep : endpoints) {
            byPath.computeIfAbsent(ep.path(), k -> new LinkedHashSet<>()).add(ep);
        }

        for (Map.Entry<String, Set<ControllerPathScanner.EndpointInfo>> entry : byPath.entrySet()) {
            String path = entry.getKey();

            sb.append("  ").append(path).append(":\n");

            // Path-level parameter block when path contains {id}
            if (path.contains("{")) {
                sb.append("    parameters:\n");
                sb.append("      - name: id\n");
                sb.append("        in: path\n");
                sb.append("        required: true\n");
                sb.append("        description: \"Resource identifier\"\n");
                sb.append("        schema:\n");
                sb.append("          type: string\n");
            }

            for (ControllerPathScanner.EndpointInfo ep : entry.getValue()) {
                String verb = ep.method().toLowerCase();
                String opId = opPfx + "-" + verb + "-" + pathToOpSuffix(path);

                sb.append("    ").append(verb).append(":\n");
                sb.append("      tags: [\"").append(tag).append("\"]\n");
                sb.append("      summary: \"").append(summaryFor(ep)).append("\"\n");
                sb.append("      operationId: \"").append(opId).append("\"\n");
                sb.append("      security:\n");
                sb.append("        - BearerAuth: []\n");
                sb.append("        - ApiKeyAuth: []\n");
                if ("GET".equals(ep.method()) || "DELETE".equals(ep.method())) {
                    sb.append("        - {}\n");
                }

                if ("POST".equals(ep.method()) || "PUT".equals(ep.method()) || "PATCH".equals(ep.method())) {
                    sb.append("      requestBody:\n");
                    sb.append("        required: true\n");
                    sb.append("        content:\n");
                    sb.append("          application/json:\n");
                    sb.append("            schema:\n");
                    sb.append("              $ref: \"#/components/schemas/GenericRequest\"\n");
                }

                sb.append("      responses:\n");
                switch (ep.method()) {
                    case "POST"   -> { appendSuccessResponse(sb, "201"); appendErrorResponses(sb); }
                    case "DELETE" -> {
                        sb.append("        \"204\":\n");
                        sb.append("          description: \"Deleted successfully\"\n");
                        appendErrorResponses(sb);
                    }
                    default       -> { appendSuccessResponse(sb, "200"); appendErrorResponses(sb); }
                }
            }
        }
    }

    /** Derives a human-readable summary from the endpoint method and path. */
    private String summaryFor(ControllerPathScanner.EndpointInfo ep) {
        String[] segs = ep.path().split("/");
        String resource = "Resource";
        for (int i = segs.length - 1; i >= 0; i--) {
            if (!segs[i].isEmpty() && !segs[i].startsWith("{")) {
                resource = capitalize(segs[i]);
                break;
            }
        }
        return switch (ep.method()) {
            case "GET"    -> ep.hasPathVar() ? "Get " + resource : "List " + resource;
            case "POST"   -> "Create " + resource;
            case "PUT"    -> "Update " + resource;
            case "DELETE" -> "Delete " + resource;
            case "PATCH"  -> "Patch " + resource;
            default       -> ep.method() + " " + resource;
        };
    }

    /** Converts a path like {@code /api/customers/{id}/orders} to {@code customers-id-orders}. */
    private String pathToOpSuffix(String path) {
        return path.replaceAll("^/", "")
                   .replaceAll("\\{[^/]+\\}", "id")
                   .replace("/", "-");
    }

    private void appendAuthPaths(StringBuilder sb) {
        sb.append("  /api/auth/login:\n");
        sb.append("    post:\n");
        sb.append("      tags: [\"auth-service\"]\n");
        sb.append("      summary: \"Login and obtain a JWT\"\n");
        sb.append("      operationId: \"auth-login\"\n");
        sb.append("      requestBody:\n");
        sb.append("        required: true\n");
        sb.append("        content:\n");
        sb.append("          application/json:\n");
        sb.append("            schema:\n");
        sb.append("              type: object\n");
        sb.append("              required: [username, password]\n");
        sb.append("              properties:\n");
        sb.append("                username: { type: string, example: alice }\n");
        sb.append("                password: { type: string, example: secret }\n");
        sb.append("      responses:\n");
        sb.append("        '200': { description: JWT issued, content: { application/json: { schema: { $ref: '#/components/schemas/AuthResponse' } } } }\n");
        sb.append("        '401': { description: Bad credentials }\n");

        sb.append("  /api/auth/register:\n");
        sb.append("    post:\n");
        sb.append("      tags: [\"auth-service\"]\n");
        sb.append("      summary: \"Register a new user (role always USER)\"\n");
        sb.append("      operationId: \"auth-register\"\n");
        sb.append("      requestBody:\n");
        sb.append("        required: true\n");
        sb.append("        content:\n");
        sb.append("          application/json:\n");
        sb.append("            schema:\n");
        sb.append("              type: object\n");
        sb.append("              required: [username, password]\n");
        sb.append("              properties:\n");
        sb.append("                username: { type: string, example: alice }\n");
        sb.append("                password: { type: string, example: secret }\n");
        sb.append("      responses:\n");
        sb.append("        '201': { description: User registered, content: { application/json: { schema: { $ref: '#/components/schemas/AuthResponse' } } } }\n");
        sb.append("        '409': { description: Username already taken }\n");
    }

    private void appendGatewayHealthPath(StringBuilder sb) {
        sb.append("  /actuator/health:\n");
        sb.append("    get:\n");
        sb.append("      tags: [\"gateway\"]\n");
        sb.append("      summary: \"Gateway health check\"\n");
        sb.append("      operationId: \"gateway-health\"\n");
        sb.append("      responses:\n");
        sb.append("        \"200\":\n");
        sb.append("          description: \"Gateway is healthy\"\n");
        sb.append("          content:\n");
        sb.append("            application/json:\n");
        sb.append("              schema:\n");
        sb.append("                $ref: \"#/components/schemas/GenericResponse\"\n");
    }

    private void appendSuccessResponse(StringBuilder sb, String code) {
        sb.append("        \"").append(code).append("\":\n");
        sb.append("          description: \"Success\"\n");
        sb.append("          content:\n");
        sb.append("            application/json:\n");
        sb.append("              schema:\n");
        sb.append("                $ref: \"#/components/schemas/GenericResponse\"\n");
    }

    private void appendErrorResponses(StringBuilder sb) {
        sb.append("        \"400\":\n");
        sb.append("          description: \"Bad Request\"\n");
        sb.append("        \"401\":\n");
        sb.append("          description: \"Unauthorized\"\n");
        sb.append("        \"404\":\n");
        sb.append("          description: \"Not Found\"\n");
        sb.append("        \"500\":\n");
        sb.append("          description: \"Internal Server Error\"\n");
    }

    private void appendComponents(StringBuilder sb) {
        sb.append("components:\n");
        sb.append("  schemas:\n");
        sb.append("    AuthResponse:\n");
        sb.append("      type: object\n");
        sb.append("      properties:\n");
        sb.append("        token:    { type: string, description: HMAC-SHA256 JWT }\n");
        sb.append("        username: { type: string }\n");
        sb.append("        role:     { type: string, example: USER }\n");
        sb.append("    GenericRequest:\n");
        sb.append("      type: object\n");
        sb.append("      additionalProperties: true\n");
        sb.append("      description: \"Request payload — replace with your concrete schema\"\n");
        sb.append("    GenericResponse:\n");
        sb.append("      type: object\n");
        sb.append("      additionalProperties: true\n");
        sb.append("      description: \"Response payload — replace with your concrete schema\"\n");
        sb.append("  securitySchemes:\n");
        sb.append("    BearerAuth:\n");
        sb.append("      type: http\n");
        sb.append("      scheme: bearer\n");
        sb.append("      bearerFormat: JWT\n");
        sb.append("    ApiKeyAuth:\n");
        sb.append("      type: apiKey\n");
        sb.append("      in: header\n");
        sb.append("      name: X-Api-Key\n");
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private String displayName(FractalModule m) {
        String[] words = m.getServiceName().split("-");
        StringBuilder result = new StringBuilder();
        for (String word : words) {
            if (!word.isEmpty()) {
                result.append(Character.toUpperCase(word.charAt(0)))
                      .append(word.substring(1)).append(" ");
            }
        }
        return result.toString().trim();
    }
}
