package org.fractalx.initializr.generator;

import org.fractalx.initializr.InitializerContext;
import org.fractalx.initializr.model.EntitySpec;
import org.fractalx.initializr.model.FieldSpec;
import org.fractalx.initializr.model.ProjectSpec;
import org.fractalx.initializr.model.ServiceSpec;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates a Flyway {@code V1__init.sql} migration for each service that uses a
 * relational database other than H2 (i.e. PostgreSQL / MySQL).
 * H2 services use Hibernate {@code create-drop} and don't need Flyway.
 */
public class FlywayMigrationGenerator implements InitializerFileGenerator {

    @Override
    public String label() { return "Flyway migrations"; }

    @Override
    public void generate(InitializerContext ctx) throws IOException {
        ProjectSpec spec = ctx.spec();

        for (ServiceSpec svc : spec.getServices()) {
            if (!svc.usesFlyway()) continue;

            StringBuilder sql = new StringBuilder();
            sql.append("-- V1__init.sql — auto-generated by FractalX Initializr\n");
            sql.append("-- Service: ").append(svc.getName()).append("\n\n");

            for (EntitySpec entity : svc.getEntities()) {
                sql.append("CREATE TABLE IF NOT EXISTS ")
                   .append(toSnakeCase(entity.getName())).append("s (\n");
                sql.append("    id BIGSERIAL PRIMARY KEY,\n");

                for (FieldSpec f : entity.getFields()) {
                    sql.append("    ").append(toSnakeCase(f.getName()))
                       .append(" ").append(sqlType(f.getType())).append(",\n");
                }

                // Cross-service IDs
                for (var xref : entity.getCrossServiceIds()) {
                    sql.append("    ").append(toSnakeCase(xref.getFieldName()))
                       .append(" VARCHAR(255),  -- ref: ").append(xref.getService()).append("\n");
                }

                // Remove trailing comma from last column
                int lastComma = sql.lastIndexOf(",\n");
                if (lastComma == sql.length() - 2) {
                    sql.replace(lastComma, sql.length(), "\n");
                }
                sql.append(");\n\n");
            }

            // Place migrations under resources/db/migration
            Path migDir = ctx.resourcesDir().resolve("db/migration");
            Files.createDirectories(migDir);
            write(migDir.resolve("V1__init.sql"), sql.toString());
        }
    }

    private String sqlType(String javaType) {
        return switch (javaType) {
            case "String"        -> "VARCHAR(255)";
            case "Long", "long"  -> "BIGINT";
            case "Integer", "int"-> "INTEGER";
            case "BigDecimal"    -> "NUMERIC(19, 4)";
            case "Boolean"       -> "BOOLEAN";
            case "LocalDateTime" -> "TIMESTAMP";
            case "LocalDate"     -> "DATE";
            case "UUID"          -> "UUID";
            case "Double"        -> "DOUBLE PRECISION";
            default              -> "VARCHAR(255)";  // enums / unknown
        };
    }

    private String toSnakeCase(String s) {
        return s.replaceAll("([A-Z])", "_$1").toLowerCase().replaceFirst("^_", "");
    }
}
