package org.fractalx.initializr.generator;

import org.fractalx.initializr.InitializerContext;
import org.fractalx.initializr.model.ProjectSpec;
import org.fractalx.initializr.model.SagaSpec;
import org.fractalx.initializr.model.ServiceSpec;

import java.io.IOException;

/**
 * Generates {@code README.md} documenting the generated project, its services,
 * and the decomposition workflow.
 */
public class ReadmeGenerator implements InitializerFileGenerator {

    @Override
    public String label() { return "README.md"; }

    @Override
    public void generate(InitializerContext ctx) throws IOException {
        ProjectSpec spec = ctx.spec();

        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(spec.getArtifactId()).append("\n\n");
        sb.append("> ").append(spec.getDescription()).append("\n\n");
        sb.append("Generated by **FractalX Initializr** — a Spring Initializr–style scaffold\n");
        sb.append("for FractalX-annotated modular monoliths.\n\n");

        sb.append("## Services\n\n");
        sb.append("| Service | Port | Database | Entities |\n");
        sb.append("|---------|------|----------|----------|\n");
        for (ServiceSpec svc : spec.getServices()) {
            String entities = svc.getEntities().stream()
                    .map(e -> e.getName())
                    .reduce((a, b) -> a + ", " + b).orElse("—");
            sb.append("| `").append(svc.getName()).append("` | ")
              .append(svc.getPort()).append(" | ")
              .append(svc.getDatabase()).append(" | ")
              .append(entities).append(" |\n");
        }
        sb.append("\n");

        if (!spec.getSagas().isEmpty()) {
            sb.append("## Distributed Sagas\n\n");
            for (SagaSpec saga : spec.getSagas()) {
                sb.append("### `").append(saga.getId()).append("`\n\n");
                sb.append("Owner: `").append(saga.getOwner()).append("`\n\n");
                sb.append("| Step | Service | Method |\n");
                sb.append("|------|---------|--------|\n");
                int step = 1;
                for (var s : saga.getSteps()) {
                    sb.append("| ").append(step++).append(" | `").append(s.getService())
                      .append("` | `").append(s.getMethod()).append("()` |\n");
                }
                sb.append("\n");
            }
        }

        sb.append("## Getting Started\n\n");
        sb.append("### Prerequisites\n\n");
        sb.append("- Java ").append(spec.getJavaVersion()).append("+\n");
        sb.append("- Maven 3.9+\n");
        sb.append("- Docker (for local databases)\n\n");

        sb.append("### Run locally\n\n");
        sb.append("```bash\n");
        sb.append("# Start database containers\n");
        sb.append("docker compose -f docker-compose.dev.yml up -d\n\n");
        sb.append("# Run the monolith\n");
        sb.append("mvn spring-boot:run -Dspring-boot.run.profiles=dev\n");
        sb.append("```\n\n");

        sb.append("### Decompose into microservices\n\n");
        sb.append("When you're ready to extract independent services:\n\n");
        sb.append("```bash\n");
        sb.append("mvn fractalx:decompose\n");
        sb.append("```\n\n");
        sb.append("FractalX reads the `@DecomposableModule` annotations and generates a\n");
        sb.append("production-ready microservice for each bounded context.\n\n");

        sb.append("### Validate before decomposing\n\n");
        sb.append("```bash\n");
        sb.append("mvn fractalx:decompose -Dfractalx.generate=false\n");
        sb.append("```\n\n");

        sb.append("## Project Structure\n\n");
        sb.append("```\n");
        sb.append(spec.getArtifactId()).append("/\n");
        sb.append("├── pom.xml\n");
        sb.append("├── src/main/java/").append(spec.packagePath()).append("/\n");
        sb.append("│   ├── ").append(spec.applicationClassName()).append(".java\n");
        for (ServiceSpec svc : spec.getServices()) {
            sb.append("│   ├── ").append(svc.javaPackage()).append("/\n");
            sb.append("│   │   ├── ").append(svc.classPrefix()).append("Module.java  (@DecomposableModule)\n");
            for (var e : svc.getEntities()) {
                sb.append("│   │   ├── ").append(e.getName()).append(".java\n");
            }
        }
        sb.append("├── src/main/resources/\n");
        sb.append("│   ├── application.yml\n");
        sb.append("│   └── fractalx-config.yml\n");
        sb.append("└── docker-compose.dev.yml\n");
        sb.append("```\n\n");

        sb.append("## Built with\n\n");
        sb.append("- [FractalX](https://fractalx.org) ").append("— static decomposition framework\n");
        sb.append("- Spring Boot ").append(spec.getSpringBootVersion()).append("\n");
        sb.append("- Java ").append(spec.getJavaVersion()).append("\n");

        write(ctx.outputRoot().resolve("README.md"), sb.toString());
    }
}
